#!/usr/bin/env python3
"""Build TD5_d3d.exe → port confidence map.

Reads Ghidra function_list pages from log/, cross-references against
td5mod/src/td5re/*.c, classifies each function into 5 confidence tiers.

Outputs:
  re/analysis/ghidra_confidence_map_2026-05-18.csv
  re/analysis/ghidra_confidence_map_2026-05-18.summary.json
"""
from __future__ import annotations
import csv
import json
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[2]
LOG_DIR = ROOT / "log"
SRC_DIR = ROOT / "td5mod" / "src" / "td5re"
ANALYSIS_DIR = ROOT / "re" / "analysis"

# -----------------------------------------------------------------------------
# Phase 1: load function list from cached pages
# -----------------------------------------------------------------------------
def load_functions() -> List[Dict]:
    items: Dict[str, Dict] = {}
    pages = sorted(LOG_DIR.glob("ghidra_functions_p*.json"))
    for p in pages:
        text = p.read_text(encoding="utf-8")
        # The persisted output is the raw mcp response JSON, optionally wrapped
        # with a JSON envelope. Try parsing directly first.
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            # try to extract the JSON object
            start = text.find("{")
            data = json.loads(text[start:])
        for it in data.get("items", []):
            addr = it["entry_point"].lower()
            if addr not in items:
                items[addr] = it
    return list(items.values())

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------
AUTO_NAME_RE = re.compile(r"^(FUN_|LAB_|DAT_|SUB_|thunk_FUN_)", re.IGNORECASE)

# Names that look auto-generated by Ghidra's PE loader (CRT / OS imports).
# These are NOT TD5 game code — they should be flagged separately.
CRT_PATTERNS = (
    "_", "__", "$",
)

def is_auto_named(name: str) -> bool:
    return bool(AUTO_NAME_RE.match(name))

def is_crt_or_lib(name: str) -> bool:
    """Heuristic: name starts with _ / __ / $ is almost certainly CRT/lib helper,
    NOT game logic. Also catches MS-specific helpers."""
    if not name:
        return False
    if name.startswith("__") or name.startswith("$"):
        return True
    if name.startswith("_") and len(name) > 1 and name[1].islower():
        # _malloc, _fopen, _printf, etc.
        return True
    # specific known CRT helpers
    if name in {"entry", "RtlUnwind", "DirectSoundCreate"}:
        return True
    return False

def body_size(it: Dict) -> int:
    try:
        return int(it["body_end"], 16) - int(it["body_start"], 16)
    except (KeyError, ValueError):
        return 0

# -----------------------------------------------------------------------------
# Phase 2: scan port source for citations
# -----------------------------------------------------------------------------
def load_port_sources() -> Dict[str, str]:
    """Return {filename: content} for every .c/.h under td5mod/src/td5re."""
    sources = {}
    if not SRC_DIR.exists():
        return sources
    for f in SRC_DIR.glob("*.c"):
        sources[f.name] = f.read_text(encoding="utf-8", errors="replace")
    for f in SRC_DIR.glob("*.h"):
        sources[f.name] = f.read_text(encoding="utf-8", errors="replace")
    return sources

def precision_keywords() -> Tuple[Tuple[str, ...], Tuple[str, ...]]:
    """Return (level5_strong, level5_weak) precision markers.

    NOTE: matching against source code is performed case-insensitively
    (see cross_reference()), so listing keywords in any single case here
    is sufficient. This catches the assorted capitalisations agents use
    in audit headers ("Byte-faithful", "byte-faithful", "BYTE-FAITHFUL",
    "Ghidra-Faithful", etc.) without needing to enumerate every variant.

    ARCH-DIVERGENCE rationale: functions flagged "[ARCH-DIVERGENCE ...]"
    are intentional, audited deviations from the original binary that are
    nevertheless byte-equivalent at the architecture-appropriate level
    (e.g. D3D3 -> D3D11 wheel billboard emission, ddraw stride changes,
    helper-collapsed dispatch tables). For this project's source-port
    architecture they count as "faithful" - the divergence is documented
    and verified, not an outstanding TODO. See Wave H reclassification.
    """
    strong = (
        # Core byte-faithfulness markers
        "byte-faithful", "byte-exact", "byte-equivalent",
        "confirmed byte-faithful",
        # [CONFIRMED ...] audit-header tag (any spacing/casing)
        "[CONFIRMED @", "[CONFIRMED@", "[CONFIRMED ",
        # L5 promotion-wave audit phrasings (2026-05-17/18)
        "L5 promotion sweep audit", "L5 promotion sweep",
        "L5 byte-faithful", "L5 audit",
        # SAR-RZ rounding fixes (Wave D)
        "SAR-RZ rounding fixed",
        # ARCH-DIVERGENCE: intentional, audited port-side deviations
        # (see docstring above). Treated as L5-equivalent.
        "[ARCH-DIVERGENCE",
        # Pilot / precise-port lineage
        "precise-port", "precise port",
        # "matches orig(inal)" pattern from older fix commits
        "matches orig", "matches original",
        # Ghidra cross-reference verifications
        "verified vs ghidra", "Ghidra-verified", "Ghidra verified",
        "Ghidra-faithful", "ghidra-faithful",
        # Generic faithfulness assertions
        "exact match", "verified faithful",
    )
    weak = (
        "approximated", "approximate", "approximation",
        "TODO verify", "TODO: verify",
        "FIXME", "needs audit", "needs verification",
        "stub", "placeholder",
    )
    return strong, weak

def cross_reference(funcs: List[Dict], sources: Dict[str, str]) -> Dict[str, Dict]:
    """For every function, find citations in port source.

    Citation tagged by:
      - hex address (with/without 0x prefix), 6 or 8 hex digits
      - Ghidra symbol name (only if non-auto-named)
    """
    strong_kw, weak_kw = precision_keywords()
    # Lower-case the keywords once; we'll match against a lower-cased view
    # of each source file so capitalisations like "Byte-faithful" vs
    # "byte-faithful" vs "BYTE-FAITHFUL" all count.
    strong_kw_lower = tuple(k.lower() for k in strong_kw)
    weak_kw_lower = tuple(k.lower() for k in weak_kw)
    # Build all-content joined for fast initial pass. Cache lower() per file.
    by_file = [(name, src, src.lower()) for name, src in sources.items()]

    out: Dict[str, Dict] = {}
    for it in funcs:
        addr = it["entry_point"].lower()
        name = it["name"]
        addr_no_lead_zeros = addr.lstrip("0") or "0"
        addr_8 = addr
        # The original game address bias is 0x00400000+; addresses look like 0042b580
        addr_short_6 = addr[2:] if addr.startswith("00") and len(addr) == 8 else addr  # last 6 hex
        # patterns to look for
        addr_patterns = {
            "0x" + addr_8.upper(): None,
            "0x" + addr_8.lower(): None,
            "0X" + addr_8.upper(): None,
            "0x" + addr_short_6.upper(): None,
            "0x" + addr_short_6.lower(): None,
            "@ 0x" + addr_8.lower(): None,
            "@ 0x" + addr_8.upper(): None,
            "@0x" + addr_8.lower(): None,
            "@" + addr_8.lower(): None,
        }
        # Also bare hex possibilities (less reliable — many false positives)
        bare_hex_patterns = (addr_short_6.lower(), addr_short_6.upper())

        citations = []
        precision_strong = 0
        precision_weak = 0
        files_cited = set()
        sample_context = ""

        for fname, src, src_lower in by_file:
            hits = 0
            local_ctx_offsets = []
            # check explicit 0x... patterns
            for pat in addr_patterns:
                if pat in src:
                    hits += src.count(pat)
                    local_ctx_offsets.append(src.find(pat))
            # check name (only if not auto-named and length >= 6 to avoid false hits)
            if not is_auto_named(name) and not is_crt_or_lib(name) and len(name) >= 6:
                # Use word boundary search
                for m in re.finditer(r"\b" + re.escape(name) + r"\b", src):
                    hits += 1
                    local_ctx_offsets.append(m.start())
            # bare hex without 0x prefix - check inside comment lines only to avoid false positives
            if hits == 0:
                for bare in bare_hex_patterns:
                    # look for "// ... 0042b580" or "(0042b580)" or similar
                    for m in re.finditer(r"[(\s/](" + re.escape(bare) + r")\b", src):
                        hits += 1
                        local_ctx_offsets.append(m.start())
            if hits:
                citations.append((fname, hits))
                files_cited.add(fname)
                # capture a small context window for the FIRST citation in any file
                if not sample_context and local_ctx_offsets:
                    off = local_ctx_offsets[0]
                    start = max(0, off - 60)
                    end = min(len(src), off + 100)
                    ctx = src[start:end].replace("\n", " | ").replace("\r", "")
                    sample_context = f"[{fname}] " + ctx.strip()
                # precision check in same file (case-insensitive for STRONG
                # keywords: match against src_lower so "Byte-faithful" /
                # "BYTE-FAITHFUL" / "byte-faithful" all count under a single
                # lower-cased keyword entry).
                for kw in strong_kw_lower:
                    if kw in src_lower:
                        # only count if kw is near a citation
                        for off in local_ctx_offsets:
                            window_start = max(0, off - 300)
                            window_end = min(len(src_lower), off + 300)
                            if kw in src_lower[window_start:window_end]:
                                precision_strong += 1
                                break
                # WEAK keywords stay case-sensitive: words like "stub" /
                # "placeholder" / "approximate" are common substrings of
                # identifiers ("GetDamageRulesStub", "stubs out", ...) and
                # casing was a useful disambiguator. Keep the legacy behaviour.
                for kw in weak_kw:
                    if kw in src:
                        for off in local_ctx_offsets:
                            window_start = max(0, off - 300)
                            window_end = min(len(src), off + 300)
                            if kw in src[window_start:window_end]:
                                precision_weak += 1
                                break

        out[addr] = {
            "address": addr,
            "name": name,
            "body_size": body_size(it),
            "citations": citations,
            "total_citations": sum(c for _, c in citations),
            "files_cited": sorted(files_cited),
            "precision_strong": precision_strong,
            "precision_weak": precision_weak,
            "sample_context": sample_context,
        }
    return out

# -----------------------------------------------------------------------------
# Phase 3: classify
# -----------------------------------------------------------------------------
def classify(rec: Dict, *, ghidra_has_doc: bool) -> int:
    name = rec["name"]
    cites = rec["total_citations"]
    auto = is_auto_named(name)
    crt = is_crt_or_lib(name)

    # CRT/lib helpers don't belong to the port-fidelity denominator regardless
    # of whether they're cited (e.g. __ftol is "cited" by physics but has no
    # port equivalent — it's libc). Return level 0 sentinel; CSV consumers
    # should treat level==0 as "out-of-scope" and exclude from L5 metrics.
    if crt:
        return 0

    if cites > 0:
        strong = rec["precision_strong"]
        weak = rec["precision_weak"]
        if strong > 0 and weak == 0:
            return 5
        # Mixed strong+weak: incidental "stub"/"approximation" mentions are
        # common in historical comments next to a fresh audit header
        # (e.g. "Prior port used a linear approximation [...] Now byte-faithful").
        # If the strong signal clearly outweighs the weak (>=2x), the function
        # is functionally L5; the weak hits are residue from historical notes.
        if strong >= 2 * weak and strong >= 2:
            return 5
        if strong > 0 and weak > 0:
            return 4   # mixed, prefer weak interpretation
        if weak > 0:
            return 4
        # Cited without precision keywords
        # Heavy citation likely = full port: assume Level 5 only if name AND any
        # word like "ported"/"matches" appears; otherwise treat as Level 4.
        return 4

    # No citations
    if auto:
        return 2 if ghidra_has_doc else 1
    if crt:
        # CRT/lib helpers — treat as Level 3 (named but obviously not port code)
        # Will be flagged in CSV.
        return 3
    return 3  # named but not ported

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
def main(args):
    funcs = load_functions()
    print(f"Loaded {len(funcs)} functions from cached pages", file=sys.stderr)
    sources = load_port_sources()
    print(f"Loaded {len(sources)} port source files", file=sys.stderr)

    refs = cross_reference(funcs, sources)

    # Initial classification: ghidra_has_doc unknown for now -> default False.
    # We'll layer bookmark/comment data on top in a separate pass.
    rows = []
    for addr, rec in refs.items():
        rec["level"] = classify(rec, ghidra_has_doc=False)
        rec["is_auto_named"] = is_auto_named(rec["name"])
        rec["is_crt"] = is_crt_or_lib(rec["name"])
        rows.append(rec)

    # sort by address
    rows.sort(key=lambda r: r["address"])

    # write JSON for later enrichment
    out_json = ANALYSIS_DIR / "ghidra_confidence_map_2026-05-18.intermediate.json"
    out_json.write_text(json.dumps(rows, indent=2))
    print(f"Wrote intermediate -> {out_json}", file=sys.stderr)

    # Aggregate stats
    by_level = {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0}
    auto_named = 0
    crt = 0
    cited = 0
    for r in rows:
        by_level[r["level"]] += 1
        if r["is_auto_named"]:
            auto_named += 1
        if r["is_crt"]:
            crt += 1
        if r["total_citations"]:
            cited += 1
    stats = {
        "total_functions": len(rows),
        "auto_named": auto_named,
        "named": len(rows) - auto_named,
        "crt_or_lib": crt,
        "cited_in_port": cited,
        "by_level": by_level,
    }
    print(json.dumps(stats, indent=2), file=sys.stderr)
    return stats

if __name__ == "__main__":
    main(sys.argv[1:])
