#!/usr/bin/env python3
"""
extract_light_zones_table.py -- Rip the per-track light-zone records from
original/TD5_d3d.exe for the port's environs-projection dispatch.

Source data:
  * 0x00469c78  per-track pointer table (parallel to the environs table @ 0x0046bb1c).
                Each non-null pointer leads to a contiguous array of 0x24-byte
                zone records. The zone count per track is derived from the
                pointer delta (next - curr) / 0x24.
  * Last populated track (40) runs up to the environs-struct pool start @
    0x00469d20 (the next data section).

Per-zone struct (0x24 bytes) — only the fields the port uses for environs
projection are captured. The remaining fields drive track-lighting direction
contribution (ApplyTrackLightingForVehicleSegment @ 0x00430150), a separate
subsystem the port does not implement yet.

  +0x00  int16  span_lo     -- zone spans [span_lo, span_hi] on the track ring
  +0x02  int16  span_hi
  +0x1c  int32  light_index -- 0..3, indexes the per-track environs struct's
                               entry[]/page_slot[] arrays.
"""
import os
import struct
import sys

try:
    import pefile
except ImportError:
    print("ERROR: pefile required. pip install pefile", file=sys.stderr)
    sys.exit(1)

EXE_PATH           = "original/TD5_d3d.exe"
OUT_PATH           = "td5mod/src/td5re/td5_light_zones_table.inc"
POINTER_TABLE_VA   = 0x00469c78
ZONE_POOL_START_VA = 0x004673d8      # first zone-pool pointee (track 1)
ZONE_POOL_END_VA   = 0x00469d20      # environs struct pool starts here
ZONE_STRUCT_SIZE   = 0x24
TRACK_SLOT_MAX     = 42              # matches TD5_ENVIRONS_TRACK_COUNT


def va_to_fo(pe, va):
    rva = va - pe.OPTIONAL_HEADER.ImageBase
    return pe.get_offset_from_rva(rva)


def parse_zone(buf, off):
    span_lo     = struct.unpack_from("<h", buf, off + 0x00)[0]
    span_hi     = struct.unpack_from("<h", buf, off + 0x02)[0]
    light_index = struct.unpack_from("<i", buf, off + 0x1c)[0]
    return span_lo, span_hi, light_index


def main():
    pe = pefile.PE(EXE_PATH, fast_load=True)
    with open(EXE_PATH, "rb") as f:
        raw = f.read()

    # --- Read the per-track pointer table ---
    tbl = va_to_fo(pe, POINTER_TABLE_VA)
    pointers = []
    for i in range(TRACK_SLOT_MAX):
        p = struct.unpack_from("<I", raw, tbl + 4 * i)[0]
        if p == 0:
            pointers.append(None)
        elif not (ZONE_POOL_START_VA <= p < ZONE_POOL_END_VA):
            # Out of pool range -> treat as end-of-table
            pointers.append(None)
        else:
            pointers.append(p)

    # --- Derive per-track zone count from pointer deltas ---
    non_null = sorted({p for p in pointers if p is not None})
    next_ptr = {}
    for i, p in enumerate(non_null):
        next_ptr[p] = non_null[i + 1] if i + 1 < len(non_null) else ZONE_POOL_END_VA

    # --- Flatten all zones into one array, emit per-track [start, count] ---
    # The pointer-delta upper bound can overcount the last track (there's padding/
    # other data between the last zone pool and the environs struct pool). Guard
    # by validating each record before accepting it: span_lo <= span_hi, span
    # range within plausible bounds, light_index in 0..3.
    all_zones = []
    track_offsets = []
    for p in pointers:
        if p is None:
            track_offsets.append((0, 0))
            continue
        max_candidates = (next_ptr[p] - p) // ZONE_STRUCT_SIZE
        start = len(all_zones)
        kept = 0
        for z in range(max_candidates):
            lo, hi, li = parse_zone(raw, va_to_fo(pe, p) + z * ZONE_STRUCT_SIZE)
            if not (0 <= li <= 3 and -1 <= lo <= 20000 and lo <= hi <= 20000):
                break
            all_zones.append((lo, hi, li))
            kept += 1
        track_offsets.append((start, kept))

    # --- Emit C header ---
    lines = []
    lines.append("/* td5_light_zones_table.inc -- GENERATED by re/tools/extract_light_zones_table.py")
    lines.append(" * Source: original/TD5_d3d.exe per-track light-zone table @ 0x00469c78.")
    lines.append(" * Do not edit by hand; re-run the extractor if the source changes.")
    lines.append(" *")
    lines.append(" * Each track has 0..N zones. Each zone covers track spans [span_lo, span_hi]")
    lines.append(" * inclusive; when the actor's track_span_raw enters a zone, its light_index")
    lines.append(" * selects which of the track's 4 environs entries gets projected onto the car's")
    lines.append(" * reflection mesh (see td5_environs_table.inc). */")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    short span_lo;")
    lines.append("    short span_hi;")
    lines.append("    int   light_index;    /* 0..3 into TD5_EnvironsTrack.page_slot[] / e[] */")
    lines.append("} TD5_LightZone;")
    lines.append("")
    lines.append(f"#define TD5_LIGHT_ZONE_COUNT   {len(all_zones)}")
    lines.append(f"#define TD5_LIGHT_ZONE_TRACK_COUNT {len(track_offsets)}")
    lines.append("")
    lines.append("static const TD5_LightZone td5_light_zones[TD5_LIGHT_ZONE_COUNT] = {")
    for i, (lo, hi, li) in enumerate(all_zones):
        lines.append(f"    /* {i:4d} */ {{ {lo:>5}, {hi:>5}, {li} }},")
    lines.append("};")
    lines.append("")
    lines.append("/* Per-track [first_zone, zone_count] offsets. track 0 and end padding are zero. */")
    lines.append("static const struct { short first; short count; } td5_light_zone_track[TD5_LIGHT_ZONE_TRACK_COUNT] = {")
    for slot, (start, count) in enumerate(track_offsets):
        lines.append(f"    /* track {slot:2d} */ {{ {start:>5}, {count:>3} }},")
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    non_null_tracks = sum(1 for _, c in track_offsets if c > 0)
    print(f"wrote {OUT_PATH}: {len(all_zones)} zones across {non_null_tracks} tracks")


if __name__ == "__main__":
    main()
