#!/usr/bin/env python3
"""
extract_environs_table.py -- Rip the per-track environs descriptor table
from original/TD5_d3d.exe and emit td5_environs_table.inc for the port.

Table layout in the exe:
  * 0x0046bb1c -- DWORD[] per-track pointer table (null first entry).
                  Each valid pointer leads to a 0xC0 byte struct.
  * 0x00469d20+ -- densely packed struct bodies, 0xC0 bytes each.

Per-track struct (0xC0):
  +0x00  int32  count           (1..4)
  +0x14  int32  effect_flags[4] (1 or 3 per entry)
  +0x40  entry[4]
         +0x00  char  name[16] or 17? (null-terminated TGA filename)
         +0x10  byte  width_shift   (0x80 = 128, 0x40 = 64, etc.)
         +0x14  byte  height_shift  (same encoding)
         (trailing bytes zero)

The struct body is 0xC0, entries span +0x40..+0xC0 at 0x20 stride.
"""
import os
import struct
import sys

try:
    import pefile
except ImportError:
    print("ERROR: pefile required. pip install pefile", file=sys.stderr)
    sys.exit(1)

EXE_PATH         = "original/TD5_d3d.exe"
OUT_PATH         = "td5mod/src/td5re/td5_environs_table.inc"
TABLE_VA         = 0x0046bb1c
STRUCT_POOL_VA   = 0x00469d20
STRUCT_POOL_END  = 0x0046bb1c   # pool ends where the pointer table starts
STRUCT_SIZE      = 0xC0
ENTRY_COUNT_MAX  = 4
ENTRY_STRIDE     = 0x20
HEADER_SIZE      = 0x40


def va_to_fo(pe, va):
    rva = va - pe.OPTIONAL_HEADER.ImageBase
    return pe.get_offset_from_rva(rva)


def read_cstr(buf, off, maxlen):
    end = buf.find(b"\x00", off, off + maxlen)
    if end < 0:
        end = off + maxlen
    return buf[off:end].decode("ascii", errors="replace")


def compute_flag(name):
    """
    Effect flag rule from InitializeTrackStripMetadata @ 0x0042FAD0:
      _strnicmp(name, "sun", 3) == 0  -> flag = 3 (sun-texture transparency preset)
      otherwise                        -> flag = 1 (opaque/default)
    Computed at load time by the original; we bake it into the table.
    """
    return 3 if name.lower().startswith("sun") else 1


def parse_track_struct(buf, off):
    count = struct.unpack_from("<i", buf, off + 0x00)[0]
    # page_slot[] at +0x04, +0x08, +0x0C, +0x10 — destination environs page index.
    # Entries can share a slot (e.g. Kenya has page_slot = [0,1,1,2] so KTRE1 and
    # KTUN1 overlay the same upload page; last-upload wins at runtime).
    page_slot = [struct.unpack_from("<i", buf, off + 0x04 + 4 * i)[0] for i in range(ENTRY_COUNT_MAX)]
    entries = []
    for i in range(ENTRY_COUNT_MAX):
        eoff = off + HEADER_SIZE + i * ENTRY_STRIDE
        name = read_cstr(buf, eoff, 0x10)
        w = buf[eoff + 0x10]
        h = buf[eoff + 0x14]
        # Flag is WRITTEN by InitializeTrackStripMetadata for ALL 4 slots regardless
        # of count: strnicmp(name, "sun", 3) == 0 -> 3 else -> 1. Empty names get 1.
        flag = compute_flag(name)
        entries.append((name, w, h, flag))
    return count, page_slot, entries


def main():
    pe  = pefile.PE(EXE_PATH, fast_load=True)
    with open(EXE_PATH, "rb") as f:
        raw = f.read()

    # --- Read the per-track pointer table until we hit a pointer that's clearly
    # outside the struct pool range.
    tbl_fo = va_to_fo(pe, TABLE_VA)
    pointers = []
    for i in range(256):  # hard cap; real count should be <40
        p = struct.unpack_from("<I", raw, tbl_fo + 4 * i)[0]
        if p == 0:
            pointers.append(None)
            continue
        if not (STRUCT_POOL_VA <= p < STRUCT_POOL_END):
            break
        pointers.append(p)

    # --- Parse each struct.
    tracks = []
    for slot, ptr in enumerate(pointers):
        if ptr is None:
            tracks.append(None)
            continue
        off = va_to_fo(pe, ptr)
        tracks.append(parse_track_struct(raw, off))

    # --- Emit the C header.
    lines = []
    lines.append("/* td5_environs_table.inc -- GENERATED by re/tools/extract_environs_table.py")
    lines.append(" * Source: original/TD5_d3d.exe per-track environs pointer table @ 0x0046bb1c.")
    lines.append(" * Do not edit by hand; re-run the extractor if the source changes. */")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    const char *name;   /* TGA stem as it appears in environs.zip (may be empty) */")
    lines.append("    int         w;      /* width in pixels */")
    lines.append("    int         h;      /* height in pixels */")
    lines.append("    int         flag;   /* projection mode: 3 = world-pos (SUN*), 1 = planar, 2 = yaw-UV (dead branch) */")
    lines.append("} TD5_EnvironsEntry;")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    int count;          /* entries 0..count-1 have valid names */")
    lines.append("    int page_slot[4];   /* destination environs-page index per entry (entries can alias) */")
    lines.append("    TD5_EnvironsEntry e[4];")
    lines.append("} TD5_EnvironsTrack;")
    lines.append("")
    lines.append(f"#define TD5_ENVIRONS_TRACK_COUNT {len(tracks)}")
    lines.append("static const TD5_EnvironsTrack td5_environs_per_track[TD5_ENVIRONS_TRACK_COUNT] = {")
    for slot, t in enumerate(tracks):
        if t is None:
            lines.append(f"    /* track {slot:2d} */ {{ 0, {{0,0,0,0}}, {{{{0}}}} }},")
            continue
        count, page_slot, entries = t
        es = []
        for i in range(ENTRY_COUNT_MAX):
            name, w, h, flag = entries[i]
            if i < count and name:
                es.append(f'{{ "{name}", {w}, {h}, {flag} }}')
            else:
                es.append(f"{{ 0, 0, 0, {flag} }}")
        ps = "{ " + ", ".join(str(s) for s in page_slot) + " }"
        lines.append(f"    /* track {slot:2d} */ {{ {count}, {ps}, {{ {', '.join(es)} }} }},")
    lines.append("};")
    lines.append("")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    non_null = sum(1 for t in tracks if t is not None)
    total_entries = sum(t[0] for t in tracks if t is not None)
    print(f"wrote {OUT_PATH}: {len(tracks)} slots, {non_null} populated, {total_entries} entries total")


if __name__ == "__main__":
    main()
