#!/usr/bin/env python3
"""Extract the per-track trackside (replay/cinematic) camera profile tables from
TD5_d3d.exe and emit a C source fragment for the source port.

RE basis (CONFIRMED via Ghidra):
  - g_perTrackTracksideCameraProfilePtrs @ VA 0x00473780 : 40 little-endian
    4-byte pointers to per-track profile arrays (writer LoadTrackRuntimeData
    @0x0042fd4b: gTracksideCameraProfiles = table[track_pool_index - 1]).
  - Each profile array = 8 signed int16 per entry:
      [behavior, spanMin, spanMax, anchorStrip, vtxOfs, heightBias,
       splineTmpl, splineAdv]
    terminated by behavior == -1 (0xFFFF).

The port indexes this with (world_x - 1) where world_x =
gTrackPoolSpanCountTable[gScheduleToPoolIndex[track]] (reverse uses the reverse
table). Image base is 0x00400000 (non-ASLR).

Usage:  python extract_trackside_cam_profiles.py [path-to-TD5_d3d.exe] > out.c
Default exe path: original/TD5_d3d.exe relative to repo root.
"""
import struct
import sys
import os

IMAGE_BASE = 0x00400000
PTR_TABLE_VA = 0x00473780
PTR_COUNT = 40
MAX_ENTRIES = 256  # safety cap per table


def load_pe(path):
    with open(path, "rb") as f:
        data = f.read()
    # DOS header -> e_lfanew
    e_lfanew = struct.unpack_from("<I", data, 0x3C)[0]
    assert data[e_lfanew:e_lfanew + 4] == b"PE\0\0", "not a PE"
    coff = e_lfanew + 4
    num_sections = struct.unpack_from("<H", data, coff + 2)[0]
    size_opt = struct.unpack_from("<H", data, coff + 16)[0]
    opt = coff + 20
    sect = opt + size_opt
    sections = []
    for i in range(num_sections):
        base = sect + i * 40
        name = data[base:base + 8].rstrip(b"\0").decode("latin1")
        vsize = struct.unpack_from("<I", data, base + 8)[0]
        vaddr = struct.unpack_from("<I", data, base + 12)[0]
        rawsize = struct.unpack_from("<I", data, base + 16)[0]
        rawptr = struct.unpack_from("<I", data, base + 20)[0]
        sections.append((name, vaddr, vsize, rawptr, rawsize))
    return data, sections


def va_to_off(sections, va):
    rva = va - IMAGE_BASE
    for name, vaddr, vsize, rawptr, rawsize in sections:
        if vaddr <= rva < vaddr + max(vsize, rawsize):
            return rawptr + (rva - vaddr)
    raise ValueError("VA 0x%08X not in any section" % va)


def read_i16(data, off):
    v = struct.unpack_from("<h", data, off)[0]
    return v


def main():
    exe = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(__file__), "..", "..", "original", "TD5_d3d.exe")
    data, sections = load_pe(exe)

    ptr_off = va_to_off(sections, PTR_TABLE_VA)
    ptrs = [struct.unpack_from("<I", data, ptr_off + 4 * i)[0]
            for i in range(PTR_COUNT)]

    tables = []  # list of list-of-entries (each entry = 8 ints)
    for idx, p in enumerate(ptrs):
        try:
            off = va_to_off(sections, p)
        except ValueError:
            tables.append(None)
            continue
        entries = []
        for e in range(MAX_ENTRIES):
            vals = [read_i16(data, off + e * 16 + s * 2) for s in range(8)]
            entries.append(vals)
            if vals[0] == -1:
                break
        tables.append(entries)

    # ---- Verify against the known sample (idx0 entry0) ----
    assert ptrs[0] == 0x0046D010, "ptr[0]=0x%08X" % ptrs[0]
    assert tables[0][0] == [0, 0, 75, 54, 1, 900, 0, 0], tables[0][0]
    sys.stderr.write("OK: ptr[0]=0x%08X, table0 entry0 verified, %d tables\n"
                     % (ptrs[0], len(tables)))
    sys.stderr.write("entry counts: %s\n"
                     % ", ".join(str(len(t) - 1) if t else "NULL" for t in tables))

    # ---- Emit C header (static linkage; include from exactly one TU) ----
    out = []
    out.append("/* AUTO-GENERATED by re/tools/extract_trackside_cam_profiles.py")
    out.append(" * from original/TD5_d3d.exe. Do not edit by hand. Re-run the script to refresh.")
    out.append(" * Per-track trackside (replay/cinematic) camera profile tables,")
    out.append(" * transcribed from g_perTrackTracksideCameraProfilePtrs @0x00473780.")
    out.append(" * Each entry = 8 int16: behavior, spanMin, spanMax, anchorStrip,")
    out.append(" * vtxOfs, heightBias, splineTmpl, splineAdv; terminated by behavior=-1.")
    out.append(" * Indexed by (world_x - 1); see td5_camera_bind_trackside_profiles(). */")
    out.append("#ifndef TD5_CAMERA_PROFILES_H")
    out.append("#define TD5_CAMERA_PROFILES_H")
    out.append("")
    for idx, t in enumerate(tables):
        if t is None:
            continue
        flat = []
        for entry in t:
            flat.extend(entry)
        out.append("static const short s_cam_prof_%02d[] = {" % idx)
        # 8 shorts per line (one entry per line)
        line = "    "
        for ei, entry in enumerate(t):
            line += "".join("%5d," % v for v in entry)
            out.append(line)
            line = "    "
        out.append("};")
    out.append("")
    out.append("/* Indexed by (world_x - 1); world_x = gTrackPoolSpanCountTable[...]. */")
    out.append("static const short *const s_per_track_camera_profiles[%d] = {" % PTR_COUNT)
    for idx, t in enumerate(tables):
        if t is None:
            out.append("    /* %2d */ 0," % idx)
        else:
            out.append("    /* %2d */ s_cam_prof_%02d," % (idx, idx))
    out.append("};")
    out.append("#define TD5_PER_TRACK_CAMERA_PROFILE_COUNT %d" % PTR_COUNT)
    out.append("")
    out.append("#endif /* TD5_CAMERA_PROFILES_H */")
    print("\n".join(out))


if __name__ == "__main__":
    main()
