#!/usr/bin/env python3
"""Generate td5_tg_real_tex_city.h -- extra CITY facade pages for the auto-track.

The auto-track's real-texture mode borrows shipped TD5 pages instead of drawing
procedural art. The first pass took every page from ONE track (level014, Sydney),
so a generated city was a single town repeated for the whole ring. This adds
facades from three more shipped city levels, which is what "use building textures
from different tracks on the same biome" asks for, and splits them into low-rise
and TOWER classes so downtown blocks can be glass high-rise while the rest of the
street stays masonry.

Source is re/assets/levels/<level>/textures.src: `textures.json` carries a
palette per page as BGR hex (the same order the TEXTURES.DAT container wants) and
`indices.bin` carries the 64x64 index bytes, page i at i*4096. The pair is copied
out verbatim -- no recolouring, no resampling.

Usage:  python re/tools/gen_trackgen_city_tex.py [levels_dir]
Writes: td5mod/src/td5re/td5_tg_real_tex_city.h
"""

import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# A worktree only copies part of re/assets, so allow the level data to be taken
# from the main checkout: gen_trackgen_city_tex.py [levels_dir].
LEVELS = sys.argv[1] if len(sys.argv) > 1 \
    else os.path.join(ROOT, "re", "assets", "levels")
OUT = os.path.join(ROOT, "td5mod", "src", "td5re", "td5_tg_real_tex_city.h")

# (level, page, comment). Picked by eye from a contact sheet of every page in
# each level, ranked by window-grid periodicity.
LOW = [
    ("level002", 64, "San Francisco: tan render, sash windows"),
    ("level002", 92, "San Francisco: brick with painted bay windows"),
    ("level023", 129, "Moscow: pink apartment block"),
    ("level023", 208, "Moscow: cream stucco, pedimented windows"),
]
TOWER = [
    ("level015", 60, "Tokyo: white office curtain wall"),
    ("level015", 111, "Tokyo: dark glass high-rise"),
    ("level015", 149, "Tokyo: pale ribbon-window tower"),
]
STORE = [
    ("level002", 133, "San Francisco: shopfront, awning and curtains"),
    ("level002", 363, "San Francisco: painted timber shopfront"),
    ("level015", 11, "Tokyo: ground-floor sign wall"),
]

TEXELS = 64 * 64


def page(level, num):
    src = os.path.join(LEVELS, level, "textures.src")
    meta = json.load(open(os.path.join(src, "textures.json")))
    if num >= meta["page_count"]:
        sys.exit("%s has no page %d" % (level, num))
    pal = bytes.fromhex(meta["pages"][num]["palette_hex"])
    with open(os.path.join(src, "indices.bin"), "rb") as f:
        f.seek(num * TEXELS)
        idx = f.read(TEXELS)
    if len(idx) != TEXELS:
        sys.exit("%s page %d: short index block" % (level, num))
    return pal, idx


def emit_array(out, decl, data, per_line=32):
    out.write("static const unsigned char %s[%d] = {" % (decl, len(data)))
    for i, v in enumerate(data):
        out.write(("\n" if i % per_line == 0 else "") + "%d," % v)
    out.write("};\n")


def emit_set(out, name, entries):
    for i, (level, num, why) in enumerate(entries):
        pal, idx = page(level, num)
        out.write("/* %s page %03d -> %s %d: %s (%d colours) */\n"
                  % (level, num, name.upper(), i, why, len(pal) // 3))
        out.write("static const int k_real_city_%s%d_paln = %d;\n"
                  % (name, i, len(pal) // 3))
        emit_array(out, "k_real_city_%s%d_pal" % (name, i), pal)
        emit_array(out, "k_real_city_%s%d_idx" % (name, i), idx)
    n = len(entries)
    out.write("static const int k_real_city_%s_count = %d;\n" % (name, n))
    out.write("static const int k_real_city_%s_paln[%d] = { %s };\n"
              % (name, n, ", ".join("k_real_city_%s%d_paln" % (name, i)
                                    for i in range(n))))
    for kind in ("pal", "idx"):
        out.write("static const unsigned char *const k_real_city_%s_%s[%d] = "
                  "{ %s };\n"
                  % (name, kind, n,
                     ", ".join("k_real_city_%s%d_%s" % (name, i, kind)
                               for i in range(n))))


def main():
    with open(OUT, "w", newline="\n") as out:
        out.write(
            "/* Extra CITY facade pages for the auto-track, borrowed from three\n"
            " * shipped TD5 city levels (San Francisco level002, Tokyo level015,\n"
            " * Moscow level023) so one generated city is not one shipped town\n"
            " * repeated. LOW pages are masonry street frontage, TOWER pages are\n"
            " * office curtain wall for downtown blocks, STORE pages are ground\n"
            " * floors. Palettes are BGR and indices are 64x64, copied verbatim\n"
            " * from each level's textures.src under re/assets/levels.\n"
            " * GENERATED by re/tools/gen_trackgen_city_tex.py, do not edit. */\n"
            "#ifndef TD5_TG_REAL_TEX_CITY_H\n"
            "#define TD5_TG_REAL_TEX_CITY_H\n\n")
        emit_set(out, "low", LOW)
        emit_set(out, "tower", TOWER)
        emit_set(out, "store", STORE)
        out.write("\n#endif /* TD5_TG_REAL_TEX_CITY_H */\n")
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
