#!/usr/bin/env python3
"""Generate td5_tg_real_tex_r5flora.h -- extra TALL tree pages for the auto-track.

[Autotrack round 5, item 18] The user asked for "more trees in all the different
shapes and forms from the various tracks -- you have to expand the library of
available resources", naming "the end of Moscow" for tall canopy trees. The
shipped tree library the generator already borrows (td5_tg_real_tex.h, 10 pages)
draws from level014/017/013/003/026/004/008 -- NONE from Moscow (level023), whose
texture set is unusually rich in foliage (a survey of its 475 pages found tall
individual trees, dense green canopy walls and an autumn set, all 64x64 and all
properly alpha-keyed with palette index 0 = black transparent key).

This borrows a few of those Moscow pages verbatim (BGR palette + 64x64 index map)
so a NEW tall-park-tree emitter can plant them. Format matches the city header:
each set writes k_r5_flora_<name><i>_{paln,pal,idx} plus the fan-out arrays.

Writes: td5mod/src/td5re/td5_tg_real_tex_r5flora.h
GENERATED by re/tools/gen_trackgen_r5flora_tex.py, do not edit.

Usage: gen_trackgen_r5flora_tex.py [levels_dir]
"""

import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LEVELS = sys.argv[1] if len(sys.argv) > 1 \
    else os.path.join(ROOT, "re", "assets", "levels")
OUT = os.path.join(ROOT, "td5mod", "src", "td5re", "td5_tg_real_tex_r5flora.h")

# (level, page, comment). Picked from a labelled contact sheet of level023 and
# verified alpha-keyed (index 0 = BGR(0,0,0), transparent sky at the top rows,
# solid foliage below) by re/tools inspection.
TREES = [
    ("level023", 397, "Moscow: tall individual canopy tree (40% key)"),
    ("level023", 412, "Moscow: dense green canopy wall (grove backdrop)"),
    ("level023", 424, "Moscow: autumn canopy tree, orange foliage"),
]

TEXELS = 64 * 64


def page(level, num):
    src = os.path.join(LEVELS, level, "textures.src")
    meta = json.load(open(os.path.join(src, "textures.json")))
    if num >= meta["page_count"]:
        sys.exit("%s has no page %d" % (level, num))
    pal = bytes.fromhex(meta["pages"][num]["palette_hex"])
    with open(os.path.join(src, "indices.bin"), "rb") as f:
        f.seek(num * TEXELS)
        idx = f.read(TEXELS)
    if len(idx) != TEXELS:
        sys.exit("%s page %d: short index block" % (level, num))
    return pal, idx


def emit_array(out, decl, data, per_line=32):
    out.write("static const unsigned char %s[%d] = {" % (decl, len(data)))
    for i, v in enumerate(data):
        out.write(("\n" if i % per_line == 0 else "") + "%d," % v)
    out.write("};\n")


def emit_set(out, name, entries):
    for i, (level, num, why) in enumerate(entries):
        pal, idx = page(level, num)
        out.write("/* %s page %03d -> %s %d: %s (%d colours) */\n"
                  % (level, num, name.upper(), i, why, len(pal) // 3))
        out.write("static const int k_r5_flora_%s%d_paln = %d;\n"
                  % (name, i, len(pal) // 3))
        emit_array(out, "k_r5_flora_%s%d_pal" % (name, i), pal)
        emit_array(out, "k_r5_flora_%s%d_idx" % (name, i), idx)
    n = len(entries)
    out.write("static const int k_r5_flora_%s_count = %d;\n" % (name, n))
    out.write("static const int k_r5_flora_%s_paln[%d] = { %s };\n"
              % (name, n, ", ".join("k_r5_flora_%s%d_paln" % (name, i)
                                    for i in range(n))))
    for kind in ("pal", "idx"):
        out.write("static const unsigned char *const k_r5_flora_%s_%s[%d] = "
                  "{ %s };\n"
                  % (name, kind, n,
                     ", ".join("k_r5_flora_%s%d_%s" % (name, i, kind)
                               for i in range(n))))


def main():
    with open(OUT, "w", newline="\n") as out:
        out.write(
            "/* Extra TALL tree pages for the auto-track park biome, borrowed\n"
            " * from Moscow (level023) -- alpha-keyed foliage (index 0 = black\n"
            " * transparent key). Palettes are BGR, indices 64x64, copied\n"
            " * verbatim from level023/textures.src under re/assets/levels.\n"
            " * [Autotrack R5 item 18] expand the tree library from shipped art.\n"
            " * GENERATED by re/tools/gen_trackgen_r5flora_tex.py, do not edit. */\n"
            "#ifndef TD5_TG_REAL_TEX_R5FLORA_H\n"
            "#define TD5_TG_REAL_TEX_R5FLORA_H\n\n")
        emit_set(out, "tree", TREES)
        out.write("\n#endif /* TD5_TG_REAL_TEX_R5FLORA_H */\n")
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
