#!/usr/bin/env python3
"""Generate td5_tg_real_tex_r7city.h -- MORE city facade variety (R7 item 4).

The city pre-selection already draws 12 wall variants (level014 + SF/Moscow/Tokyo,
see gen_trackgen_city_tex.py). Item 4 asks for more building variety, and a survey
of the shipped city levels found ~24 unmined facades. This mines a curated 12 --
seven low-rise masonry and five tower/office frontages -- into a SECOND header so
the first is untouched, and gives them the `r7city` symbol infix so both headers
can coexist in one translation unit. The pages live in the R7_CITY page block; the
derived page chain in td5_trackgen.c is not moved.

Same source form as gen_trackgen_city_tex.py: re/assets/levels/<level>/textures.src
(textures.json BGR palettes + indices.bin 64x64 index blocks), copied verbatim.

Usage:  python re/tools/gen_trackgen_r7city_tex.py [levels_dir]
Writes: td5mod/src/td5re/td5_tg_real_tex_r7city.h
"""

import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
LEVELS = sys.argv[1] if len(sys.argv) > 1 \
    else os.path.join(ROOT, "re", "assets", "levels")
OUT = os.path.join(ROOT, "td5mod", "src", "td5re", "td5_tg_real_tex_r7city.h")

# (level, page, comment). None already used by gen_trackgen_city_tex.py. Curated
# from the R7 shipped-facade survey; level013 is an unmined city block (085-090).
LOW = [
    ("level002", 91,  "San Francisco: timber bay / sash window frontage"),
    ("level002", 93,  "San Francisco: arched masonry windows, brick"),
    ("level023", 128, "Moscow: brick apartment window facade"),
    ("level023", 209, "Moscow: neoclassical facade, windows and cornice"),
    ("level013", 88,  "balconied apartment block"),
    ("level013", 86,  "white windowed office frontage"),
    ("level013", 85,  "pale masonry / tile facade"),
]
TOWER = [
    ("level014", 64,  "Melbourne: dense office window grid"),
    ("level015", 61,  "Tokyo: office curtain-wall base, columns + glass"),
    ("level015", 148, "Tokyo: ribbon-window tower with brown pilaster"),
    ("level015", 150, "Tokyo: window-row building with ledges"),
    ("level013", 89,  "blue-and-cream ribbon-window frontage"),
]

TEXELS = 64 * 64


def page(level, num):
    src = os.path.join(LEVELS, level, "textures.src")
    meta = json.load(open(os.path.join(src, "textures.json")))
    if num >= meta["page_count"]:
        sys.exit("%s has no page %d (page_count %d)"
                 % (level, num, meta["page_count"]))
    pal = bytes.fromhex(meta["pages"][num]["palette_hex"])
    with open(os.path.join(src, "indices.bin"), "rb") as f:
        f.seek(num * TEXELS)
        idx = f.read(TEXELS)
    if len(idx) != TEXELS:
        sys.exit("%s page %d: short index block" % (level, num))
    return pal, idx


def emit_array(out, decl, data, per_line=32):
    out.write("static const unsigned char %s[%d] = {" % (decl, len(data)))
    for i, v in enumerate(data):
        out.write(("\n" if i % per_line == 0 else "") + "%d," % v)
    out.write("};\n")


def emit_set(out, name, entries):
    for i, (level, num, why) in enumerate(entries):
        pal, idx = page(level, num)
        out.write("/* %s page %03d -> %s %d: %s (%d colours) */\n"
                  % (level, num, name.upper(), i, why, len(pal) // 3))
        out.write("static const int k_real_r7city_%s%d_paln = %d;\n"
                  % (name, i, len(pal) // 3))
        emit_array(out, "k_real_r7city_%s%d_pal" % (name, i), pal)
        emit_array(out, "k_real_r7city_%s%d_idx" % (name, i), idx)
    n = len(entries)
    out.write("static const int k_real_r7city_%s_count = %d;\n" % (name, n))
    out.write("static const int k_real_r7city_%s_paln[%d] = { %s };\n"
              % (name, n, ", ".join("k_real_r7city_%s%d_paln" % (name, i)
                                    for i in range(n))))
    for kind in ("pal", "idx"):
        out.write("static const unsigned char *const k_real_r7city_%s_%s[%d] = "
                  "{ %s };\n"
                  % (name, kind, n,
                     ", ".join("k_real_r7city_%s%d_%s" % (name, i, kind)
                               for i in range(n))))


def main():
    with open(OUT, "w", newline="\n") as out:
        out.write(
            "/* MORE city facade variety for the auto-track (R7 item 4), mined\n"
            " * from shipped TD5 city levels not fully used before -- SF level002,\n"
            " * Moscow level023, Tokyo level015, Melbourne level014 and the unmined\n"
            " * city level013. LOW pages are masonry street frontage, TOWER pages\n"
            " * office/glass. Palettes are BGR and indices 64x64, copied verbatim\n"
            " * from each level's textures.src. GENERATED by\n"
            " * re/tools/gen_trackgen_r7city_tex.py, do not edit. */\n"
            "#ifndef TD5_TG_REAL_TEX_R7CITY_H\n"
            "#define TD5_TG_REAL_TEX_R7CITY_H\n\n")
        emit_set(out, "low", LOW)
        emit_set(out, "tower", TOWER)
        out.write("\n#endif /* TD5_TG_REAL_TEX_R7CITY_H */\n")
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
