#!/usr/bin/env python3
"""Bake Xbox_Controller.svg -> raw-DEFLATE BGRA blob C header for the in-race
tutorial overlay (td5_tutorial.c). Regenerate when the art or size changes:
    python re/tools/gen_tutorial_pad_art.py
Writes td5mod/src/td5re/td5_tutorial_pad_art.h."""
import cairosvg, io, zlib, os
from PIL import Image

SRC = "C:/Users/maria/Desktop/Proyectos/TD5RE/Xbox_Controller.svg"
OUT = "C:/Users/maria/Desktop/Proyectos/TD5RE/.claude/worktrees/fix-1782691708-502659-29274/td5mod/src/td5re/td5_tutorial_pad_art.h"
W   = 1024  # render width: crisp at the controller's on-screen size

png = cairosvg.svg2png(url=SRC, output_width=W)
im  = Image.open(io.BytesIO(png)).convert("RGBA")
W,H = im.size
px  = im.load()

raw = bytearray(W*H*4); i=0
for y in range(H):
    for x in range(W):
        r,g,b,a = px[x,y]
        raw[i]=b; raw[i+1]=g; raw[i+2]=r; raw[i+3]=a; i+=4
co   = zlib.compressobj(9, zlib.DEFLATED, -15)
comp = co.compress(bytes(raw)) + co.flush()

def centroid(pred):
    xs=ys=n=0
    for y in range(H):
        for x in range(W):
            r,g,b,a = px[x,y]
            if a>=110 and pred(x,y,r,g,b): xs+=x; ys+=y; n+=1
    return (xs/n/W, ys/n/H) if n else (0.5,0.5)
A=centroid(lambda x,y,r,g,b: g>150 and r<140 and b<120 and x>0.55*W)
B=centroid(lambda x,y,r,g,b: r>150 and g<90 and b<90)
X=centroid(lambda x,y,r,g,b: b>120 and r<90 and g<110)
Y=centroid(lambda x,y,r,g,b: r>180 and g>150 and b<110)

o=["/* td5_tutorial_pad_art.h -- AUTO-GENERATED by re/tools/gen_tutorial_pad_art.py",
   " * from Xbox_Controller.svg (Wikimedia Commons, CC). Raw-DEFLATE BGRA8 image,",
   " * inflated once at runtime and blitted as one textured quad. Do not edit. */",
   "#ifndef TD5_TUTORIAL_PAD_ART_H","#define TD5_TUTORIAL_PAD_ART_H",
   f"#define PAD_ART_W {W}", f"#define PAD_ART_H {H}",
   f"#define PAD_ART_RAW_LEN {len(raw)}  /* W*H*4 BGRA */",
   f"static const unsigned int k_pad_art_deflate_len = {len(comp)}u;",
   "static const unsigned char k_pad_art_deflate[] = {"]
ln="  "
for byte in comp:
    ln+=f"{byte},"
    if len(ln)>=110: o.append(ln); ln="  "
if ln.strip(): o.append(ln)
o.append("};")
def emit(n,t): o.append(f"#define PAD_AX_{n} {t[0]:.4f}f"); o.append(f"#define PAD_AY_{n} {t[1]:.4f}f")
emit("A",A); emit("B",B); emit("X",X); emit("Y",Y)
for k,v in {"LSTICK":(0.200,0.470),"L3":(0.210,0.545),"RSTICK":(0.632,0.745),"R3":(0.632,0.745),"DPAD":(0.356,0.720),"BACK":(0.400,0.470),"START":(0.585,0.470),"LB":(0.215,0.252),"RB":(0.787,0.252),"LT":(0.232,0.130),"RT":(0.772,0.130)}.items(): emit(k,v)
o.append("#endif /* TD5_TUTORIAL_PAD_ART_H */")
open(OUT,"w").write("\n".join(o)+"\n")
print(f"wrote {OUT}: {W}x{H} deflate={len(comp)//1024}KB anchors A={A} B={B} X={X} Y={Y}")
