#!/usr/bin/env python3
"""Generate td5_tg_furniture_tex.h -- real TD5 street-furniture texture pages.

The auto-track generator (td5_trackgen.c) may only use art that shipped with
Test Drive 5.  This lifts four kinds of page out of the extracted level data,
losslessly, into the same (palette, index) pair the trackgen page format wants:

  streetlamp   level001 page 356 -- post + arm + lantern head, alpha-keyed
  railing      level013 page 226 -- metal balustrade, alpha-keyed
  START banner level001 pages 337 + 338 -- the word split across two pages
  FINISH banner level001 pages 369 + 370 -- likewise, with chequer end blocks

Byte order: the shipped .DAT palette is BGR, which is what textures.json's
`palette_hex` already holds, so the palette is copied from the JSON verbatim and
only the 64x64 index plane is read from the PNG.  Page `type` (0 opaque,
1 alpha-keyed on index 0) is likewise the shipped value, not a guess.

Run from the repo root:  python re/tools/gen_tg_furniture_tex.py
"""
import json
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "td5mod", "src", "td5re", "td5_tg_furniture_tex.h")
# A git worktree carries the source but not the extracted level data, so allow
# the asset tree to be pointed at the main checkout.
ASSETS = os.environ.get("TD5RE_ASSETS_ROOT", os.path.join(ROOT, "re", "assets"))

# (C identifier, level, page, human note)
PAGES = [
    ("lamp",      "level001", 356, "streetlamp: post + arm + lantern head"),
    ("fence",     "level013", 226, "metal balustrade railing"),
    ("start_l",   "level001", 337, "START banner, left half"),
    ("start_r",   "level001", 338, "START banner, right half"),
    ("finish_l",  "level001", 369, "FINISH banner, left half"),
    ("finish_r",  "level001", 370, "FINISH banner, right half"),
]


def load(level, page):
    base = os.path.join(ASSETS, "levels", level, "textures.src")
    meta = json.load(open(os.path.join(base, "textures.json")))["pages"][page]
    pal = bytes.fromhex(meta["palette_hex"])
    im = Image.open(os.path.join(base, "pages", "page_%03d.png" % page))
    if im.mode != "P" or im.size != (64, 64):
        raise SystemExit("page %s/%d is not a 64x64 paletted page" % (level, page))
    idx = im.tobytes()
    if len(idx) != 4096:
        raise SystemExit("page %s/%d index plane is %d bytes" % (level, page, len(idx)))
    if max(idx) * 3 + 3 > len(pal):
        raise SystemExit("page %s/%d indexes past its palette" % (level, page))
    return pal, idx, int(meta["type"])


def emit_array(w, name, data, per_line=32):
    w("static const unsigned char %s[%d] = {" % (name, len(data)))
    for off in range(0, len(data), per_line):
        chunk = ",".join(str(b) for b in data[off:off + per_line])
        w("%s%s" % (chunk, "," if off + per_line < len(data) else ""))
    w("};")


def main():
    lines = []
    w = lines.append
    w("/* Real TD5 street-furniture texture pages, encoded losslessly in the")
    w(" * trackgen page format. GENERATED by re/tools/gen_tg_furniture_tex.py,")
    w(" * do not edit. Palettes are BGR, as the shipped .DAT stores them. */")
    w("#ifndef TD5_TG_FURNITURE_TEX_H")
    w("#define TD5_TG_FURNITURE_TEX_H")
    for name, level, page, note in PAGES:
        pal, idx, ptype = load(level, page)
        w("/* %s page %03d -> %s: %s, %d colours, type %d */"
          % (level, page, name.upper(), note, len(pal) // 3, ptype))
        w("static const int k_furn_%s_paln = %d;" % (name, len(pal) // 3))
        w("static const int k_furn_%s_type = %d;" % (name, ptype))
        emit_array(w, "k_furn_%s_pal" % name, pal)
        emit_array(w, "k_furn_%s_idx" % name, idx)
    w("#endif /* TD5_TG_FURNITURE_TEX_H */")
    open(OUT, "w", newline="\n").write("\n".join(lines) + "\n")
    sys.stderr.write("wrote %s (%d pages)\n" % (OUT, len(PAGES)))


if __name__ == "__main__":
    main()
