#!/usr/bin/env python3
"""Generate byte-exact SNK_ label table from the original English Language.dll.

Produces a standalone C header (td5_snk_strings.h) of #define'd label constants so
the port can use the original's exact strings/casing without a runtime DLL dependency.
RESEARCH/BUILD tool — re-runnable; output is checked into the port source tree.
"""
import struct, re, sys

DLL = r"C:/Users/maria/Desktop/Proyectos/TD5RE/original/Language/English/Language.dll"

data = open(DLL, "rb").read()
pe = struct.unpack_from("<I", data, 0x3c)[0]
coff = pe + 4
nsec = struct.unpack_from("<H", data, coff + 2)[0]
optsz = struct.unpack_from("<H", data, coff + 16)[0]
opt = coff + 20
magic = struct.unpack_from("<H", data, opt)[0]
imgbase = struct.unpack_from("<I", data, opt + (28 if magic == 0x10b else 24))[0]
ddir = opt + (96 if magic == 0x10b else 112)
exp_rva = struct.unpack_from("<I", data, ddir)[0]
sect = opt + optsz
secs = []
for i in range(nsec):
    o = sect + i * 40
    vsz, va, rsz, raw = struct.unpack_from("<IIII", data, o + 8)
    secs.append((va, vsz, raw, rsz))


def r2o(rva):
    for va, vsz, raw, rsz in secs:
        if va <= rva < va + max(vsz, rsz):
            off = raw + (rva - va)
            return off if off < len(data) else None
    return None


def cstr(off):
    if off is None:
        return None
    e = data.find(b"\0", off)
    return data[off:e].decode("latin1", "replace")


def lines(off):
    out = []
    cur = off
    while cur is not None and cur < len(data):
        e = data.find(b"\0", cur)
        seg = data[cur:e].decode("latin1", "replace")
        if seg == "" and out:
            break
        out.append(seg)
        cur = e + 1
        if len(out) > 30:
            break
    return out


eo = r2o(exp_rva)
nname = struct.unpack_from("<I", data, eo + 24)[0]
fo = r2o(struct.unpack_from("<I", data, eo + 28)[0])
no = r2o(struct.unpack_from("<I", data, eo + 32)[0])
oo = r2o(struct.unpack_from("<I", data, eo + 36)[0])
exp = {}
for i in range(nname):
    nm = cstr(r2o(struct.unpack_from("<I", data, no + i * 4)[0]))
    ordi = struct.unpack_from("<H", data, oo + i * 2)[0]
    exp[nm] = struct.unpack_from("<I", data, fo + ordi * 4)[0]


def bt(nm):
    m = re.match(r"\?(\w+)@@3(.*)A$", nm)
    return (m.group(1), m.group(2)) if m else (nm, "")


def cesc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


out = []
out.append("/* AUTO-GENERATED byte-exact from original/Language/English/Language.dll")
out.append(" * by re/tools/gen_snk_labels.py -- DO NOT EDIT BY HAND.")
out.append(" * Standalone SNK_ label bake: the original's exact strings/casing, no runtime DLL. */")
out.append("#ifndef TD5_SNK_STRINGS_H")
out.append("#define TD5_SNK_STRINGS_H")
out.append("")
out.append("/* ---- Single-string labels (SNK_*ButTxt / SNK_*Txt) ---- */")
for nm in sorted(exp):
    b, t = bt(nm)
    # Every single-string (PAD = char*) SNK_ export that is NOT a hint (_MT/_Ex)
    # nor a config-unit fragment; covers ButTxt/Txt labels AND the results action-menu
    # names (SNK_ViewReplay, SNK_RaceAgain, SNK_Quit, ...) that don't use the *Txt suffix.
    if t.startswith("PAD") and not b.endswith(("_MT", "_Ex", "_MT1")):
        out.append('#define %s "%s"' % (b, cesc(cstr(r2o(exp[nm])))))
out.append("")
out.append("#endif /* TD5_SNK_STRINGS_H */")

dst = r"C:/Users/maria/Desktop/Proyectos/TD5RE/.claude/worktrees/fix-1780170781-137846-13319/td5mod/src/td5re/td5_snk_strings.h"
if len(sys.argv) > 1:
    dst = sys.argv[1]
open(dst, "w").write("\n".join(out) + "\n")
ndef = sum(1 for l in out if l.startswith("#define SNK_"))
print("wrote %s (%d label defines)" % (dst, ndef))
