/**
 * d3d11_backend.c - D3D11 device creation, shaders, state objects, compositing
 *
 * Backend_Init, Backend_Shutdown, and Backend_EnumerateModes live in
 * ddraw_main.c (alongside the DLL exports). This file contains:
 *   - Device lifecycle (CreateDevice, Reset)
 *   - Display window management (windowed mode)
 *   - Shader creation from pre-compiled bytecode
 *   - Immutable state object creation (blend, depth-stencil, rasterizer, sampler)
 *   - Dynamic vertex/index buffer management
 *   - Constant buffer updates (viewport, fog)
 *   - Render state cache → D3D11 state object binding
 *   - Pixel shader selection (transparency mode)
 *   - Fullscreen quad rendering (present blit, compositing)
 *   - WrapperClipper stub
 */

#include "wrapper.h"

/* Pre-compiled shader bytecode (generated by fxc.exe from shaders/*.hlsl) */
#include "shaders/vs_pretransformed_bytes.h"
#include "shaders/vs_fullscreen_bytes.h"
#include "shaders/ps_modulate_bytes.h"
#include "shaders/ps_modulate_alpha_bytes.h"
#include "shaders/ps_decal_bytes.h"
#include "shaders/ps_luminance_alpha_bytes.h"
#include "shaders/ps_composite_bytes.h"

/* Dynamic buffer sizes */
#define DYNAMIC_VB_SIZE  (128 * 1024)   /* 128 KB — handles ~4000 vertices */
#define DYNAMIC_IB_SIZE  (32 * 1024)    /* 32 KB — handles ~16000 indices */

/* ========================================================================
 * Display window
 *
 * We create our OWN window for display output. M2DX's 640x480 WS_POPUP
 * window stays hidden. This avoids all conflicts with M2DX's window
 * management (HandleRenderWindowResize, ApplyWindowedRenderSize, etc.)
 * ======================================================================== */

static HWND s_display_hwnd = NULL;
static HWND s_dinput_hwnd_storage = NULL;  /* Static storage for DInput hwnd patch */
static volatile int s_window_focused = 1;  /* 1 = focused, 0 = unfocused (pause game) */

static LRESULT CALLBACK DisplayWindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    switch (msg) {
    case WM_CHAR:
    case WM_KEYDOWN:
    case WM_KEYUP:
    case WM_SYSKEYDOWN:
    case WM_SYSKEYUP:
        /* Only forward keyboard input when focused */
        if (s_window_focused && g_backend.hwnd)
            PostMessageA(g_backend.hwnd, msg, wParam, lParam);
        return 0;

    case WM_CLOSE:
        if (g_backend.hwnd)
            PostMessageA(g_backend.hwnd, WM_CLOSE, 0, 0);
        return 0;

    case WM_ACTIVATE:
        if (LOWORD(wParam) == WA_INACTIVE) {
            s_window_focused = 0;
            ClipCursor(NULL);
            WRAPPER_LOG("DisplayWindowProc: UNFOCUSED — game paused");
        } else {
            s_window_focused = 1;
            SetCursor(NULL);   /* hide system cursor immediately on focus restore */
            WRAPPER_LOG("DisplayWindowProc: FOCUSED — game resumed");
        }
        break;

    case WM_SETFOCUS:
        s_window_focused = 1;
        SetCursor(NULL);
        break;

    case WM_KILLFOCUS:
        s_window_focused = 0;
        ClipCursor(NULL);
        break;

    case WM_SETCURSOR:
        /* Suppress the system arrow cursor over the game client area so the
         * software-rendered SnkMouse.TGA cursor is the only one visible. */
        if (LOWORD(lParam) == HTCLIENT) {
            SetCursor(NULL);
            return TRUE;
        }
        break;
    }
    return DefWindowProcA(hwnd, msg, wParam, lParam);
}

static HWND Backend_CreateDisplayWindow(int client_w, int client_h)
{
    WNDCLASSEXA wc;
    DWORD style = WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_VISIBLE;
    RECT wr = { 0, 0, client_w, client_h };
    int scr_w, scr_h, x, y;
    HWND hwnd;

    ZeroMemory(&wc, sizeof(wc));
    wc.cbSize        = sizeof(wc);
    wc.style         = CS_HREDRAW | CS_VREDRAW;
    wc.lpfnWndProc   = DisplayWindowProc;
    wc.hInstance      = GetModuleHandleA(NULL);
    wc.hCursor        = LoadCursor(NULL, IDC_ARROW);
    wc.hbrBackground  = (HBRUSH)GetStockObject(BLACK_BRUSH);
    wc.lpszClassName  = "TD5_D3D11_Display";
    RegisterClassExA(&wc);

    AdjustWindowRect(&wr, style, FALSE);
    scr_w = GetSystemMetrics(SM_CXSCREEN);
    scr_h = GetSystemMetrics(SM_CYSCREEN);
    x = (scr_w - (wr.right - wr.left)) / 2;
    y = (scr_h - (wr.bottom - wr.top)) / 2;

    /* TD5RE_WINDOW_TITLE overrides the default so /fix sessions can tag the
     * window with the branch / scenario under test. */
    {
        static char title_buf[256];
        const char *title = "Test Drive 5";
        DWORD n = GetEnvironmentVariableA("TD5RE_WINDOW_TITLE",
                                          title_buf, sizeof(title_buf));
        if (n > 0 && n < sizeof(title_buf)) title = title_buf;

        hwnd = CreateWindowExA(
            0, "TD5_D3D11_Display", title,
            style, x, y,
            wr.right - wr.left, wr.bottom - wr.top,
            NULL, NULL, GetModuleHandleA(NULL), NULL);
    }

    if (hwnd) {
        ShowWindow(hwnd, SW_SHOW);
        UpdateWindow(hwnd);
        WRAPPER_LOG("Backend_CreateDisplayWindow: %p %dx%d (client %dx%d)",
            hwnd, wr.right - wr.left, wr.bottom - wr.top, client_w, client_h);
    } else {
        WRAPPER_LOG("Backend_CreateDisplayWindow: CreateWindowExA FAILED");
    }
    return hwnd;
}

HWND Backend_GetDisplayWindow(void)
{
    return s_display_hwnd;
}

void Backend_UpdateMousePosition(void)
{
    HMODULE m2dx;
    POINT pt;
    int gx, gy;
    BYTE *base;

    if (!g_backend.windowed || !s_display_hwnd)
        return;

    m2dx = GetModuleHandleA("M2DX.dll");
    if (!m2dx) return;

    GetCursorPos(&pt);
    ScreenToClient(s_display_hwnd, &pt);

    gx = pt.x * g_backend.width / g_backend.target_width;
    gy = pt.y * g_backend.height / g_backend.target_height;

    if (gx < 0) gx = 0;
    if (gx >= g_backend.width) gx = g_backend.width - 1;
    if (gy < 0) gy = 0;
    if (gy >= g_backend.height) gy = g_backend.height - 1;

    base = (BYTE*)m2dx;
    *(int*)(base + 0x61BD0) = gx;
    *(int*)(base + 0x61BD4) = gy;
    *(int*)0x00498710 = 1;
}

void Backend_EnforceWindowSize(void)
{
    MSG msg;

    if (!g_backend.windowed || !s_display_hwnd)
        return;

    /* Standalone mode: skip focus enforcement so the window doesn't freeze
     * when it loses focus during development. */
    if (g_backend.standalone)
        return;

    /* Process window messages */
    while (PeekMessageA(&msg, s_display_hwnd, 0, 0, PM_REMOVE)) {
        TranslateMessage(&msg);
        DispatchMessageA(&msg);
    }

    /* When unfocused: spin in a sleep loop until focus returns.
     * This effectively pauses the game since the game loop is blocked
     * in the present/flip/blt call that invokes EnforceWindowSize. */
    while (!s_window_focused && s_display_hwnd) {
        Sleep(50);
        /* Keep processing messages so we can detect WM_ACTIVATE to resume */
        while (PeekMessageA(&msg, s_display_hwnd, 0, 0, PM_REMOVE)) {
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
    }

    if (g_backend.windowed && s_display_hwnd) {
        /* Only confine cursor and update mouse when our window is actually
         * the foreground window AND focused. Skip when debugger has focus. */
        if (s_window_focused && GetForegroundWindow() == s_display_hwnd) {
            Backend_UpdateMousePosition();
            RECT clip;
            GetClientRect(s_display_hwnd, &clip);
            MapWindowPoints(s_display_hwnd, NULL, (POINT*)&clip, 2);
            ClipCursor(&clip);
        } else {
            ClipCursor(NULL);
        }
    }
}

/* ========================================================================
 * M2DX.dll patches for windowed mode
 * (Input, cooperative level, window management)
 * ======================================================================== */

static void Backend_ApplyM2DXPatches(HWND display_hwnd, HWND game_hwnd)
{
    HMODULE m2dx = GetModuleHandleA("M2DX.dll");
    if (!m2dx) return;

    BYTE *base = (BYTE*)m2dx;
    DWORD old_protect;

    s_dinput_hwnd_storage = display_hwnd;

    /* Keyboard coop flags: 0x06 -> 0x0A (NONEXCLUSIVE|BACKGROUND) */
    if (VirtualProtect(base + 0x95A3, 1, PAGE_EXECUTE_READWRITE, &old_protect)) {
        *(base + 0x95A3) = 0x0A;
        VirtualProtect(base + 0x95A3, 1, old_protect, &old_protect);
    }
    /* Keyboard hwnd operand */
    if (VirtualProtect(base + 0x9597, 4, PAGE_EXECUTE_READWRITE, &old_protect)) {
        *(DWORD*)(base + 0x9597) = (DWORD)(uintptr_t)&s_dinput_hwnd_storage;
        VirtualProtect(base + 0x9597, 4, old_protect, &old_protect);
    }
    /* Mouse coop flags: 0x05 -> 0x0A */
    if (VirtualProtect(base + 0x9609, 1, PAGE_EXECUTE_READWRITE, &old_protect)) {
        *(base + 0x9609) = 0x0A;
        VirtualProtect(base + 0x9609, 1, old_protect, &old_protect);
    }
    /* Mouse hwnd operand */
    if (VirtualProtect(base + 0x95FD, 4, PAGE_EXECUTE_READWRITE, &old_protect)) {
        *(DWORD*)(base + 0x95FD) = (DWORD)(uintptr_t)&s_dinput_hwnd_storage;
        VirtualProtect(base + 0x95FD, 4, old_protect, &old_protect);
    }

    /* NOP 6 position-write instructions in GetMouse (keep button write intact) */
    {
        struct { int offset; int len; } nops[] = {
            { 0x9853, 5 }, { 0x9858, 6 }, { 0x9874, 5 },
            { 0x988D, 6 }, { 0x98A5, 6 }, { 0x98BD, 6 },
        };
        int i;
        for (i = 0; i < 6; i++) {
            BYTE *p = base + nops[i].offset;
            if (VirtualProtect(p, nops[i].len, PAGE_EXECUTE_READWRITE, &old_protect)) {
                int j;
                for (j = 0; j < nops[i].len; j++) p[j] = 0x90;
                VirtualProtect(p, nops[i].len, old_protect, &old_protect);
            }
        }
    }

    /* Patch GetMaxTextures → return 100 immediately */
    if (VirtualProtect(base + 0x1D40, 6, PAGE_EXECUTE_READWRITE, &old_protect)) {
        base[0x1D40] = 0xB8; base[0x1D41] = 0x64; base[0x1D42] = 0x00;
        base[0x1D43] = 0x00; base[0x1D44] = 0x00; base[0x1D45] = 0xC3;
        VirtualProtect(base + 0x1D40, 6, old_protect, &old_protect);
    }

    /* Patch mouse-active-this-frame flag init 0→1 */
    {
        BYTE *imm = (BYTE*)0x414C3C;
        DWORD op;
        if (VirtualProtect(imm, 1, PAGE_EXECUTE_READWRITE, &op)) {
            *imm = 0x01;
            VirtualProtect(imm, 1, op, &op);
        }
    }

    /* Disable FPS overlay (uses overlay surfaces + GetDC which would crash) */
    {
        DWORD *pFpsOverlay = (DWORD*)(base + 0x32728);
        DWORD old2;
        if (VirtualProtect(pFpsOverlay, 4, PAGE_READWRITE, &old2)) {
            *pFpsOverlay = 0;
            VirtualProtect(pFpsOverlay, 4, old2, &old2);
        }
    }

    /* Bypass viewport Clear in DXD3D::BeginScene (we do Z-clear ourselves) */
    if (VirtualProtect(base + 0x1611, 5, PAGE_EXECUTE_READWRITE, &old_protect)) {
        base[0x1611] = 0xEB;  /* JMP rel8 */
        base[0x1612] = 0x67;  /* +0x67 → skip to CalculateFrameRate */
        base[0x1613] = 0x90;
        base[0x1614] = 0x90;
        base[0x1615] = 0x90;
        VirtualProtect(base + 0x1611, 5, old_protect, &old_protect);
    }

    /* Note: HandleRenderWindowResize is patched early in Backend_Init (ddraw_main.c) */
    WRAPPER_LOG("Backend_ApplyM2DXPatches: all patches applied");
}

/* ========================================================================
 * Shader & state object creation
 * ======================================================================== */

static int Backend_CreateShaders(void)
{
    HRESULT hr;
    ID3D11Device *dev = g_backend.device;

    /* Vertex shader: pre-transformed XYZRHW → NDC */
    hr = ID3D11Device_CreateVertexShader(dev,
        g_vs_pretransformed, sizeof(g_vs_pretransformed), NULL,
        &g_backend.vs_pretransformed);
    if (FAILED(hr)) {
        WRAPPER_LOG("CreateShaders: vs_pretransformed FAILED hr=0x%08lX", hr);
        return 0;
    }

    /* Input layout (must match vs_pretransformed input signature) */
    {
        D3D11_INPUT_ELEMENT_DESC layout[] = {
            { "POSITION", 0, DXGI_FORMAT_R32G32B32A32_FLOAT, 0,  0, D3D11_INPUT_PER_VERTEX_DATA, 0 },
            { "COLOR",    0, DXGI_FORMAT_B8G8R8A8_UNORM,     0, 16, D3D11_INPUT_PER_VERTEX_DATA, 0 },
            { "COLOR",    1, DXGI_FORMAT_B8G8R8A8_UNORM,     0, 20, D3D11_INPUT_PER_VERTEX_DATA, 0 },
            { "TEXCOORD", 0, DXGI_FORMAT_R32G32_FLOAT,        0, 24, D3D11_INPUT_PER_VERTEX_DATA, 0 },
        };
        hr = ID3D11Device_CreateInputLayout(dev,
            layout, 4,
            g_vs_pretransformed, sizeof(g_vs_pretransformed),
            &g_backend.input_layout);
        if (FAILED(hr)) {
            WRAPPER_LOG("CreateShaders: input_layout FAILED hr=0x%08lX", hr);
            return 0;
        }
    }

    /* Vertex shader: fullscreen quad (SV_VertexID based, no input layout) */
    hr = ID3D11Device_CreateVertexShader(dev,
        g_vs_fullscreen, sizeof(g_vs_fullscreen), NULL,
        &g_backend.vs_fullscreen);
    if (FAILED(hr)) {
        WRAPPER_LOG("CreateShaders: vs_fullscreen FAILED hr=0x%08lX", hr);
        return 0;
    }

    /* Pixel shaders */
    hr = ID3D11Device_CreatePixelShader(dev,
        g_ps_modulate, sizeof(g_ps_modulate), NULL,
        &g_backend.ps_shaders[PS_MODULATE]);
    if (FAILED(hr)) { WRAPPER_LOG("CreateShaders: ps_modulate FAILED"); return 0; }

    hr = ID3D11Device_CreatePixelShader(dev,
        g_ps_modulate_alpha, sizeof(g_ps_modulate_alpha), NULL,
        &g_backend.ps_shaders[PS_MODULATE_ALPHA]);
    if (FAILED(hr)) { WRAPPER_LOG("CreateShaders: ps_modulate_alpha FAILED"); return 0; }

    hr = ID3D11Device_CreatePixelShader(dev,
        g_ps_decal, sizeof(g_ps_decal), NULL,
        &g_backend.ps_shaders[PS_DECAL]);
    if (FAILED(hr)) { WRAPPER_LOG("CreateShaders: ps_decal FAILED"); return 0; }

    hr = ID3D11Device_CreatePixelShader(dev,
        g_ps_luminance_alpha, sizeof(g_ps_luminance_alpha), NULL,
        &g_backend.ps_shaders[PS_LUMINANCE_ALPHA]);
    if (FAILED(hr)) { WRAPPER_LOG("CreateShaders: ps_luminance_alpha FAILED"); return 0; }

    hr = ID3D11Device_CreatePixelShader(dev,
        g_ps_composite, sizeof(g_ps_composite), NULL,
        &g_backend.ps_composite);
    if (FAILED(hr)) { WRAPPER_LOG("CreateShaders: ps_composite FAILED"); return 0; }

    WRAPPER_LOG("CreateShaders: all shaders created OK");
    return 1;
}

static int Backend_CreateStateObjects(void)
{
    HRESULT hr;
    ID3D11Device *dev = g_backend.device;

    /* --- Blend states --- */
    {
        D3D11_BLEND_DESC bd;
        ZeroMemory(&bd, sizeof(bd));
        bd.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;

        /* BLEND_OPAQUE: no blending */
        bd.RenderTarget[0].BlendEnable = FALSE;
        hr = ID3D11Device_CreateBlendState(dev, &bd, &g_backend.blend_states[BLEND_OPAQUE]);
        if (FAILED(hr)) return 0;

        /* BLEND_SRCALPHA_INVSRC: standard alpha blend */
        bd.RenderTarget[0].BlendEnable = TRUE;
        bd.RenderTarget[0].SrcBlend  = D3D11_BLEND_SRC_ALPHA;
        bd.RenderTarget[0].DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOp   = D3D11_BLEND_OP_ADD;
        bd.RenderTarget[0].SrcBlendAlpha  = D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOpAlpha   = D3D11_BLEND_OP_ADD;
        hr = ID3D11Device_CreateBlendState(dev, &bd, &g_backend.blend_states[BLEND_SRCALPHA_INVSRC]);
        if (FAILED(hr)) return 0;

        /* BLEND_SRCALPHA_ONE: additive with source alpha */
        bd.RenderTarget[0].DestBlend = D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_ONE;
        hr = ID3D11Device_CreateBlendState(dev, &bd, &g_backend.blend_states[BLEND_SRCALPHA_ONE]);
        if (FAILED(hr)) return 0;

        /* BLEND_ONE_ONE: full additive */
        bd.RenderTarget[0].SrcBlend  = D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlend = D3D11_BLEND_ONE;
        bd.RenderTarget[0].SrcBlendAlpha  = D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_ONE;
        hr = ID3D11Device_CreateBlendState(dev, &bd, &g_backend.blend_states[BLEND_ONE_ONE]);
        if (FAILED(hr)) return 0;

        /* BLEND_SRCALPHA_SRCALPHA: TD5 transparency mode
         * out = src*srcA + dst*srcA — used by BindRaceTexturePage for
         * translucent geometry (trees, fences, billboards). */
        bd.RenderTarget[0].SrcBlend  = D3D11_BLEND_SRC_ALPHA;
        bd.RenderTarget[0].DestBlend = D3D11_BLEND_SRC_ALPHA;
        bd.RenderTarget[0].BlendOp   = D3D11_BLEND_OP_ADD;
        bd.RenderTarget[0].SrcBlendAlpha  = D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_SRC_ALPHA;
        bd.RenderTarget[0].BlendOpAlpha   = D3D11_BLEND_OP_ADD;
        hr = ID3D11Device_CreateBlendState(dev, &bd, &g_backend.blend_states[BLEND_SRCALPHA_SRCALPHA]);
        if (FAILED(hr)) return 0;

        /* BLEND_INVSRC_INVSRC: M2DX baseline blend mode
         * out = src*(1-srcA) + dst*(1-srcA) — set as default blend factors
         * by M2DX::SetRenderState. With opaque pixels (alpha=1) this produces
         * zero output, effectively making blending a no-op for opaque geometry. */
        bd.RenderTarget[0].SrcBlend  = D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOp   = D3D11_BLEND_OP_ADD;
        bd.RenderTarget[0].SrcBlendAlpha  = D3D11_BLEND_ONE;
        bd.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
        bd.RenderTarget[0].BlendOpAlpha   = D3D11_BLEND_OP_ADD;
        hr = ID3D11Device_CreateBlendState(dev, &bd, &g_backend.blend_states[BLEND_INVSRC_INVSRC]);
        if (FAILED(hr)) return 0;
    }

    /* --- Depth-stencil states --- */
    {
        D3D11_DEPTH_STENCIL_DESC dd;
        ZeroMemory(&dd, sizeof(dd));
        dd.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
        dd.StencilEnable = FALSE;

        dd.DepthEnable = TRUE;  dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
        hr = ID3D11Device_CreateDepthStencilState(dev, &dd, &g_backend.ds_states[DS_Z_ON_WRITE_ON]);
        if (FAILED(hr)) return 0;

        dd.DepthEnable = TRUE;  dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
        hr = ID3D11Device_CreateDepthStencilState(dev, &dd, &g_backend.ds_states[DS_Z_ON_WRITE_OFF]);
        if (FAILED(hr)) return 0;

        dd.DepthEnable = FALSE; dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
        hr = ID3D11Device_CreateDepthStencilState(dev, &dd, &g_backend.ds_states[DS_Z_OFF_WRITE_OFF]);
        if (FAILED(hr)) return 0;

        dd.DepthEnable = FALSE; dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
        hr = ID3D11Device_CreateDepthStencilState(dev, &dd, &g_backend.ds_states[DS_Z_OFF_WRITE_ON]);
        if (FAILED(hr)) return 0;

        /* ALWAYS comparison (for sky, HUD overlays that always pass depth test) */
        dd.DepthFunc = D3D11_COMPARISON_ALWAYS;
        dd.DepthEnable = TRUE; dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ALL;
        hr = ID3D11Device_CreateDepthStencilState(dev, &dd, &g_backend.ds_states[DS_Z_ON_WRITE_ON_ALWAYS]);
        if (FAILED(hr)) return 0;

        dd.DepthEnable = TRUE; dd.DepthWriteMask = D3D11_DEPTH_WRITE_MASK_ZERO;
        hr = ID3D11Device_CreateDepthStencilState(dev, &dd, &g_backend.ds_states[DS_Z_ON_WRITE_OFF_ALWAYS]);
        if (FAILED(hr)) return 0;
    }

    /* --- Rasterizer state --- */
    {
        D3D11_RASTERIZER_DESC rd;
        ZeroMemory(&rd, sizeof(rd));
        rd.FillMode = D3D11_FILL_SOLID;
        rd.CullMode = D3D11_CULL_NONE;
        rd.DepthClipEnable = FALSE;  /* Legacy Direct3D XYZRHW didn't clip on Z — match that behavior */
        rd.ScissorEnable = TRUE;     /* HUD/minimap uses RSSetScissorRects for 2D clipping */
        rd.MultisampleEnable = FALSE;
        rd.AntialiasedLineEnable = FALSE;
        hr = ID3D11Device_CreateRasterizerState(dev, &rd, &g_backend.rs_state);
        if (FAILED(hr)) return 0;
    }

    /* --- Sampler states --- */
    {
        D3D11_SAMPLER_DESC sd;
        ZeroMemory(&sd, sizeof(sd));
        sd.MaxAnisotropy = 1;
        sd.ComparisonFunc = D3D11_COMPARISON_NEVER;
        sd.MinLOD = 0;
        sd.MaxLOD = D3D11_FLOAT32_MAX;

        /* Point + Wrap */
        sd.Filter = D3D11_FILTER_MIN_MAG_MIP_POINT;
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_WRAP;
        hr = ID3D11Device_CreateSamplerState(dev, &sd, &g_backend.sampler_states[SAMP_POINT_WRAP]);
        if (FAILED(hr)) return 0;

        /* Point + Clamp */
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        hr = ID3D11Device_CreateSamplerState(dev, &sd, &g_backend.sampler_states[SAMP_POINT_CLAMP]);
        if (FAILED(hr)) return 0;

        /* Linear + Wrap */
        sd.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_WRAP;
        hr = ID3D11Device_CreateSamplerState(dev, &sd, &g_backend.sampler_states[SAMP_LINEAR_WRAP]);
        if (FAILED(hr)) return 0;

        /* Linear + Clamp */
        sd.AddressU = sd.AddressV = sd.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
        hr = ID3D11Device_CreateSamplerState(dev, &sd, &g_backend.sampler_states[SAMP_LINEAR_CLAMP]);
        if (FAILED(hr)) return 0;
    }

    WRAPPER_LOG("CreateStateObjects: all state objects created OK");
    return 1;
}

static int Backend_CreateDynamicBuffers(void)
{
    HRESULT hr;
    D3D11_BUFFER_DESC bd;

    /* Dynamic vertex buffer */
    ZeroMemory(&bd, sizeof(bd));
    bd.ByteWidth = DYNAMIC_VB_SIZE;
    bd.Usage = D3D11_USAGE_DYNAMIC;
    bd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
    bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    hr = ID3D11Device_CreateBuffer(g_backend.device, &bd, NULL, &g_backend.dynamic_vb);
    if (FAILED(hr)) {
        WRAPPER_LOG("CreateDynamicBuffers: VB FAILED hr=0x%08lX", hr);
        return 0;
    }
    g_backend.dynamic_vb_size = DYNAMIC_VB_SIZE;

    /* Dynamic index buffer */
    bd.ByteWidth = DYNAMIC_IB_SIZE;
    bd.BindFlags = D3D11_BIND_INDEX_BUFFER;
    hr = ID3D11Device_CreateBuffer(g_backend.device, &bd, NULL, &g_backend.dynamic_ib);
    if (FAILED(hr)) {
        WRAPPER_LOG("CreateDynamicBuffers: IB FAILED hr=0x%08lX", hr);
        return 0;
    }
    g_backend.dynamic_ib_size = DYNAMIC_IB_SIZE;

    /* Viewport constant buffer */
    bd.ByteWidth = sizeof(ViewportCB);
    bd.Usage = D3D11_USAGE_DEFAULT;
    bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    bd.CPUAccessFlags = 0;
    hr = ID3D11Device_CreateBuffer(g_backend.device, &bd, NULL, &g_backend.cb_viewport);
    if (FAILED(hr)) return 0;

    /* Fog constant buffer */
    bd.ByteWidth = sizeof(FogCB);
    hr = ID3D11Device_CreateBuffer(g_backend.device, &bd, NULL, &g_backend.cb_fog);
    if (FAILED(hr)) return 0;

    WRAPPER_LOG("CreateDynamicBuffers: VB=%uKB IB=%uKB, CBs created",
        DYNAMIC_VB_SIZE/1024, DYNAMIC_IB_SIZE/1024);

    /* 1x1 white texture for the debug-line path. PS_MODULATE multiplies the
     * sampled texel by the diffuse vertex color, so a white texel yields the
     * raw vertex color — exactly what we want for solid-color line overlays. */
    {
        D3D11_TEXTURE2D_DESC td;
        D3D11_SUBRESOURCE_DATA srd;
        UINT pixel = 0xFFFFFFFFu;
        ZeroMemory(&td, sizeof(td));
        td.Width = 1; td.Height = 1; td.MipLevels = 1; td.ArraySize = 1;
        td.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
        td.SampleDesc.Count = 1;
        td.Usage = D3D11_USAGE_IMMUTABLE;
        td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
        srd.pSysMem = &pixel;
        srd.SysMemPitch = 4;
        srd.SysMemSlicePitch = 0;
        hr = ID3D11Device_CreateTexture2D(g_backend.device, &td, &srd, &g_backend.white_tex);
        if (FAILED(hr)) {
            WRAPPER_LOG("CreateDynamicBuffers: white_tex FAILED hr=0x%08lX", hr);
            return 0;
        }
        hr = ID3D11Device_CreateShaderResourceView(g_backend.device,
            (ID3D11Resource*)g_backend.white_tex, NULL, &g_backend.white_srv);
        if (FAILED(hr)) {
            WRAPPER_LOG("CreateDynamicBuffers: white_srv FAILED hr=0x%08lX", hr);
            return 0;
        }
    }
    return 1;
}

/* ========================================================================
 * Swap chain render target creation
 * ======================================================================== */

static int Backend_CreateRenderTargets(int width, int height)
{
    HRESULT hr;
    ID3D11Texture2D *bb_tex = NULL;

    /* Get swap chain back buffer */
    hr = IDXGISwapChain_GetBuffer(g_backend.swap_chain, 0,
        &IID_ID3D11Texture2D, (void**)&bb_tex);
    if (FAILED(hr)) {
        WRAPPER_LOG("CreateRenderTargets: GetBuffer FAILED hr=0x%08lX", hr);
        return 0;
    }

    hr = ID3D11Device_CreateRenderTargetView(g_backend.device,
        (ID3D11Resource*)bb_tex, NULL, &g_backend.swap_rtv);
    ID3D11Texture2D_Release(bb_tex);
    if (FAILED(hr)) {
        WRAPPER_LOG("CreateRenderTargets: CreateRTV FAILED hr=0x%08lX", hr);
        return 0;
    }

    /* Create depth buffer */
    {
        D3D11_TEXTURE2D_DESC dtd;
        ZeroMemory(&dtd, sizeof(dtd));
        dtd.Width  = (UINT)width;
        dtd.Height = (UINT)height;
        dtd.MipLevels = 1;
        dtd.ArraySize = 1;
        dtd.Format = DXGI_FORMAT_D16_UNORM;
        dtd.SampleDesc.Count = 1;
        dtd.Usage = D3D11_USAGE_DEFAULT;
        dtd.BindFlags = D3D11_BIND_DEPTH_STENCIL;

        hr = ID3D11Device_CreateTexture2D(g_backend.device, &dtd, NULL, &g_backend.depth_tex);
        if (FAILED(hr)) {
            WRAPPER_LOG("CreateRenderTargets: depth texture FAILED hr=0x%08lX", hr);
            return 0;
        }

        hr = ID3D11Device_CreateDepthStencilView(g_backend.device,
            (ID3D11Resource*)g_backend.depth_tex, NULL, &g_backend.depth_dsv);
        if (FAILED(hr)) {
            WRAPPER_LOG("CreateRenderTargets: DSV FAILED hr=0x%08lX", hr);
            return 0;
        }
    }

    WRAPPER_LOG("CreateRenderTargets: %dx%d OK", width, height);
    return 1;
}

static void Backend_ReleaseRenderTargets(void)
{
    if (g_backend.depth_dsv)  { ID3D11DepthStencilView_Release(g_backend.depth_dsv);  g_backend.depth_dsv = NULL; }
    if (g_backend.depth_tex)  { ID3D11Texture2D_Release(g_backend.depth_tex);           g_backend.depth_tex = NULL; }
    if (g_backend.swap_rtv)   { ID3D11RenderTargetView_Release(g_backend.swap_rtv);     g_backend.swap_rtv = NULL; }
}

/* ========================================================================
 * Backend_CreateDevice
 * ======================================================================== */

int Backend_CreateDevice(HWND hwnd, int width, int height, int bpp, int windowed)
{
    HRESULT hr;
    HWND device_hwnd;
    DXGI_SWAP_CHAIN_DESC scd;
    UINT create_flags = 0;
    int rt_width, rt_height;

    WRAPPER_LOG("Backend_CreateDevice: hwnd=%p %dx%d %dbpp windowed=%d",
                hwnd, width, height, bpp, windowed);

    if (!g_backend.device) {
        /* First-time D3D11 device creation */
        D3D_FEATURE_LEVEL feature_levels[] = {
            D3D_FEATURE_LEVEL_11_0,
            D3D_FEATURE_LEVEL_10_1,
            D3D_FEATURE_LEVEL_10_0,
        };
        D3D_FEATURE_LEVEL achieved_level;

#ifdef WRAPPER_DEBUG
        /* Debug layer DISABLED — it enforces strict resource hazard rules
         * that may silently unbind render targets during normal operation. */
        /* create_flags |= D3D11_CREATE_DEVICE_DEBUG; */
#endif

        /* Store parameters */
        g_backend.hwnd = hwnd;
        g_backend.width = width;
        g_backend.height = height;
        g_backend.bpp = bpp;
        g_backend.windowed = windowed;

        /* In windowed mode, create our own display window */
        device_hwnd = hwnd;
        if (windowed) {
            /* Use pre-set target dimensions if available (standalone mode sets
             * these from td5re.ini before calling Backend_CreateDevice).
             * Only fall back to INI/native detection for wrapper DLL mode. */
            if (g_backend.target_width <= 0 || g_backend.target_height <= 0) {
                int ini_w, ini_h;
                char ini_path[MAX_PATH];
                GetModuleFileNameA(NULL, ini_path, MAX_PATH);
                { char *s = strrchr(ini_path, '\\'); if (s) strcpy(s + 1, "td5re.ini"); }
                ini_w = GetPrivateProfileIntA("Display", "Width", 0, ini_path);
                ini_h = GetPrivateProfileIntA("Display", "Height", 0, ini_path);
                if (ini_w <= 0 || ini_h <= 0) {
                    ini_w = GetSystemMetrics(SM_CXSCREEN);
                    ini_h = GetSystemMetrics(SM_CYSCREEN);
                    if (ini_w <= 0) ini_w = 1280;
                    if (ini_h <= 0) ini_h = 960;
                }
                g_backend.target_width  = ini_w;
                g_backend.target_height = ini_h;
            }

            if (!s_display_hwnd) {
                s_display_hwnd = Backend_CreateDisplayWindow(g_backend.target_width, g_backend.target_height);
            }
            if (s_display_hwnd) {
                device_hwnd = s_display_hwnd;
                ShowWindow(hwnd, SW_HIDE);
                Backend_ApplyM2DXPatches(s_display_hwnd, hwnd);
            }
        }

        rt_width  = windowed ? g_backend.target_width  : width;
        rt_height = windowed ? g_backend.target_height : height;

        /* Create swap chain description */
        ZeroMemory(&scd, sizeof(scd));
        scd.BufferCount = 1;
        scd.BufferDesc.Width  = (UINT)rt_width;
        scd.BufferDesc.Height = (UINT)rt_height;
        scd.BufferDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
        scd.BufferDesc.RefreshRate.Numerator   = 60;
        scd.BufferDesc.RefreshRate.Denominator = 1;
        scd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
        scd.OutputWindow = device_hwnd;
        scd.SampleDesc.Count = 1;
        scd.Windowed = windowed ? TRUE : FALSE;
        scd.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;

        hr = D3D11CreateDeviceAndSwapChain(
            NULL,                       /* Default adapter */
            D3D_DRIVER_TYPE_HARDWARE,
            NULL,                       /* No software rasterizer */
            create_flags,
            feature_levels, 3,
            D3D11_SDK_VERSION,
            &scd,
            &g_backend.swap_chain,
            &g_backend.device,
            &achieved_level,
            &g_backend.context);

        if (FAILED(hr)) {
            WRAPPER_LOG("Backend_CreateDevice: D3D11CreateDeviceAndSwapChain FAILED hr=0x%08lX", hr);
            /* Retry without debug layer */
            create_flags &= ~D3D11_CREATE_DEVICE_DEBUG;
            hr = D3D11CreateDeviceAndSwapChain(
                NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, create_flags,
                feature_levels, 3, D3D11_SDK_VERSION, &scd,
                &g_backend.swap_chain, &g_backend.device,
                &achieved_level, &g_backend.context);
            if (FAILED(hr)) {
                WRAPPER_LOG("Backend_CreateDevice: retry without debug FAILED hr=0x%08lX", hr);
                return 0;
            }
        }

        WRAPPER_LOG("Backend_CreateDevice: device=%p ctx=%p feature_level=0x%X",
            g_backend.device, g_backend.context, achieved_level);

        /* Create render targets */
        if (!Backend_CreateRenderTargets(rt_width, rt_height))
            return 0;

        /* Create shaders */
        if (!Backend_CreateShaders())
            return 0;

        /* Create state objects */
        if (!Backend_CreateStateObjects())
            return 0;

        /* Create dynamic buffers */
        if (!Backend_CreateDynamicBuffers())
            return 0;

        /* Set initial pipeline state */
        {
            ID3D11DeviceContext *ctx = g_backend.context;
            UINT stride = TD5_VERTEX_STRIDE;
            UINT offset = 0;
            D3D11_VIEWPORT vp;

            ID3D11DeviceContext_IASetInputLayout(ctx, g_backend.input_layout);
            ID3D11DeviceContext_IASetPrimitiveTopology(ctx, D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
            ID3D11DeviceContext_IASetVertexBuffers(ctx, 0, 1, &g_backend.dynamic_vb, &stride, &offset);
            ID3D11DeviceContext_IASetIndexBuffer(ctx, g_backend.dynamic_ib, DXGI_FORMAT_R16_UINT, 0);

            ID3D11DeviceContext_VSSetShader(ctx, g_backend.vs_pretransformed, NULL, 0);
            ID3D11DeviceContext_VSSetConstantBuffers(ctx, 0, 1, &g_backend.cb_viewport);

            ID3D11DeviceContext_PSSetShader(ctx, g_backend.ps_shaders[PS_MODULATE], NULL, 0);
            ID3D11DeviceContext_PSSetConstantBuffers(ctx, 0, 1, &g_backend.cb_fog);

            ID3D11DeviceContext_RSSetState(ctx, g_backend.rs_state);
            ID3D11DeviceContext_OMSetRenderTargets(ctx, 1, &g_backend.swap_rtv, g_backend.depth_dsv);
            ID3D11DeviceContext_OMSetBlendState(ctx, g_backend.blend_states[BLEND_OPAQUE], NULL, 0xFFFFFFFF);
            ID3D11DeviceContext_OMSetDepthStencilState(ctx, g_backend.ds_states[DS_Z_ON_WRITE_ON], 0);
            ID3D11DeviceContext_PSSetSamplers(ctx, 0, 1, &g_backend.sampler_states[SAMP_LINEAR_WRAP]);

            vp.TopLeftX = 0; vp.TopLeftY = 0;
            vp.Width    = (FLOAT)rt_width;
            vp.Height   = (FLOAT)rt_height;
            vp.MinDepth = 0.0f;
            vp.MaxDepth = 1.0f;
            ID3D11DeviceContext_RSSetViewports(ctx, 1, &vp);

            /* Default scissor rect covers the full render target; the RS state
             * has ScissorEnable=TRUE so 2D HUD clipping can override it via
             * RSSetScissorRects without touching rasterizer state. */
            {
                D3D11_RECT scissor;
                scissor.left   = 0;
                scissor.top    = 0;
                scissor.right  = (LONG)rt_width;
                scissor.bottom = (LONG)rt_height;
                ID3D11DeviceContext_RSSetScissorRects(ctx, 1, &scissor);
            }
        }

        /* Initialize state cache */
        g_backend.state.z_enable = 1;
        g_backend.state.z_write = 1;
        g_backend.state.blend_enable = 0;
        g_backend.state.src_blend = D3D6BLEND_SRCALPHA;
        g_backend.state.dest_blend = D3D6BLEND_INVSRCALPHA;
        g_backend.state.texblend_mode = D3DTBLEND_MODULATE;
        g_backend.state.mag_filter = 2; /* LINEAR */
        g_backend.state.min_filter = 2;
        g_backend.state.tex_address_u = 1; /* WRAP */
        g_backend.state.tex_address_v = 1;
        g_backend.state.current_blend_idx = BLEND_OPAQUE;
        g_backend.state.current_ds_idx = DS_Z_ON_WRITE_ON;
        g_backend.state.current_samp_idx = SAMP_LINEAR_WRAP;
        g_backend.state.current_ps_idx = PS_MODULATE;
        g_backend.state.dirty = 0;

        g_backend.current_tex_has_alpha = 1;
        g_backend.alpha_blend_enabled = 0;

        /* Update viewport constant buffer */
        Backend_UpdateViewportCB((float)rt_width, (float)rt_height);

        /* Initialize fog CB (disabled by default) */
        {
            FogCB fog = {0};
            fog.fogEnabled = 0;
            ID3D11DeviceContext_UpdateSubresource(g_backend.context,
                (ID3D11Resource*)g_backend.cb_fog, 0, NULL, &fog, 0, 0);
        }

        /* Initialize frontend scaling */
        g_backend.fe_scale.virtual_w  = width;
        g_backend.fe_scale.virtual_h  = height;
        g_backend.fe_scale.native_w   = g_backend.target_width;
        g_backend.fe_scale.native_h   = g_backend.target_height;
        if (g_backend.target_width > 0 && g_backend.target_height > 0 &&
            g_backend.target_width > width) {
            g_backend.fe_scale.scale_x  = (float)g_backend.target_width / (float)width;
            g_backend.fe_scale.scale_y  = (float)g_backend.target_height / (float)height;
            g_backend.fe_scale.enabled  = 1;
        } else {
            g_backend.fe_scale.scale_x  = 1.0f;
            g_backend.fe_scale.scale_y  = 1.0f;
            g_backend.fe_scale.enabled  = 0;
        }
        g_backend.fe_scale.log_level    = 1;
        g_backend.fe_scale.adjust_x     = 0;
        g_backend.fe_scale.adjust_y     = 0;
        g_backend.fe_scale.filter_mode  = 0;

        /* Vertex scaling */
        g_backend.vertex_scale_x = 1.0f;
        g_backend.vertex_scale_y = 1.0f;
        g_backend.m2dx_width = width;
        g_backend.m2dx_height = height;

        WRAPPER_LOG("Backend_CreateDevice: OK device=%p swap=%p",
            g_backend.device, g_backend.swap_chain);
        return 1;
    }

    /* Device already exists — this is a mode change, handled by Backend_Reset */
    return Backend_Reset(width, height, bpp, windowed);
}

/* ========================================================================
 * Backend_Reset
 * ======================================================================== */

int Backend_Reset(int width, int height, int bpp, int windowed)
{
    HRESULT hr;
    int rt_width, rt_height;

    WRAPPER_LOG("Backend_Reset: %dx%d %dbpp windowed=%d", width, height, bpp, windowed);

    if (!g_backend.device || !g_backend.swap_chain) {
        WRAPPER_LOG("Backend_Reset: no device, calling CreateDevice");
        return Backend_CreateDevice(g_backend.hwnd, width, height, bpp, windowed);
    }

    g_backend.width = width;
    g_backend.height = height;
    g_backend.bpp = bpp;
    g_backend.windowed = windowed;

    rt_width  = windowed ? g_backend.target_width  : width;
    rt_height = windowed ? g_backend.target_height : height;

    /* Release render targets before resizing swap chain */
    ID3D11DeviceContext_OMSetRenderTargets(g_backend.context, 0, NULL, NULL);
    Backend_ReleaseRenderTargets();

    hr = IDXGISwapChain_ResizeBuffers(g_backend.swap_chain,
        1, (UINT)rt_width, (UINT)rt_height,
        DXGI_FORMAT_B8G8R8A8_UNORM, 0);
    if (FAILED(hr)) {
        WRAPPER_LOG("Backend_Reset: ResizeBuffers FAILED hr=0x%08lX", hr);
        return 0;
    }

    if (!Backend_CreateRenderTargets(rt_width, rt_height))
        return 0;

    /* Re-bind render targets */
    ID3D11DeviceContext_OMSetRenderTargets(g_backend.context, 1,
        &g_backend.swap_rtv, g_backend.depth_dsv);

    /* Update viewport */
    {
        D3D11_VIEWPORT vp;
        vp.TopLeftX = 0; vp.TopLeftY = 0;
        vp.Width    = (FLOAT)rt_width;
        vp.Height   = (FLOAT)rt_height;
        vp.MinDepth = 0.0f;
        vp.MaxDepth = 1.0f;
        ID3D11DeviceContext_RSSetViewports(g_backend.context, 1, &vp);
    }
    Backend_UpdateViewportCB((float)rt_width, (float)rt_height);

    WRAPPER_LOG("Backend_Reset: OK");
    return 1;
}

/* ========================================================================
 * Constant buffer updates
 * ======================================================================== */

void Backend_UpdateViewportCB(float w, float h)
{
    ViewportCB vp;
    vp.viewportWidth  = w;
    vp.viewportHeight = h;
    vp._pad[0] = vp._pad[1] = 0.0f;
    ID3D11DeviceContext_UpdateSubresource(g_backend.context,
        (ID3D11Resource*)g_backend.cb_viewport, 0, NULL, &vp, 0, 0);
}

void Backend_UpdateFogCB(void)
{
    FogCB fog;
    DWORD fc = g_backend.state.fog_color;
    fog.fogColor[0] = ((fc >> 16) & 0xFF) / 255.0f;  /* R */
    fog.fogColor[1] = ((fc >>  8) & 0xFF) / 255.0f;  /* G */
    fog.fogColor[2] = ((fc >>  0) & 0xFF) / 255.0f;  /* B */
    fog.fogColor[3] = 1.0f;
    fog.fogStart    = g_backend.state.fog_start;
    fog.fogEnd      = g_backend.state.fog_end;
    fog.fogDensity  = g_backend.state.fog_density;
    fog.fogEnabled  = g_backend.state.fog_enable;
    fog.alphaTestEnabled = g_backend.state.alpha_test_enable;
    fog.alphaRef    = g_backend.state.alpha_ref / 255.0f;
    fog._pad1       = 0.0f;
    fog._pad2       = 0.0f;
    ID3D11DeviceContext_UpdateSubresource(g_backend.context,
        (ID3D11Resource*)g_backend.cb_fog, 0, NULL, &fog, 0, 0);
}

/* ========================================================================
 * State cache → D3D11 binding
 * ======================================================================== */

static const char *s_ps_names[] = { "MODULATE", "MODULATE_ALPHA", "DECAL", "LUMINANCE_ALPHA" };

void Backend_SelectPixelShader(void)
{
    int idx;

    /* R5G6B5 textures are converted to B8G8R8A8 with alpha=0xFF (fully opaque).
     * A1R5G5B5 textures get correct alpha from bit15. Both formats have valid
     * alpha in the D3D11 texture, so we always use the standard shader path.
     *
     * LUMINANCE_ALPHA was previously auto-selected for blended R5G6B5 textures,
     * but this is WRONG: it replaces alpha with luminance, making dark pixels
     * transparent. The sky, road, and other opaque geometry rendered semi-transparent
     * over the cleared black background, causing missing track elements and
     * wrong car textures. */
    switch (g_backend.state.texblend_mode) {
    case D3DTBLEND_DECAL:         idx = PS_DECAL; break;
    case D3DTBLEND_MODULATEALPHA: idx = PS_MODULATE_ALPHA; break;
    default:                      idx = PS_MODULATE; break;
    }

    if (idx != g_backend.state.current_ps_idx) {
        static int s_ps_log = 0;
        if (s_ps_log < 30) {
            WRAPPER_LOG("SelectPS: %s (blend=%d tex_alpha=%d texblend=%d src=%u dst=%u)",
                s_ps_names[idx], g_backend.alpha_blend_enabled,
                g_backend.current_tex_has_alpha, g_backend.state.texblend_mode,
                g_backend.state.src_blend, g_backend.state.dest_blend);
            s_ps_log++;
        }
        g_backend.state.current_ps_idx = idx;
        ID3D11DeviceContext_PSSetShader(g_backend.context,
            g_backend.ps_shaders[idx], NULL, 0);
    }
}

void Backend_ApplyStateCache(void)
{
    RenderStateCache *s = &g_backend.state;
    ID3D11DeviceContext *ctx = g_backend.context;

    if (!s->dirty) return;

    /* Blend state */
    {
        int bi;
        if (!s->blend_enable) {
            bi = BLEND_OPAQUE;
        } else if (s->src_blend == D3D6BLEND_SRCALPHA && s->dest_blend == D3D6BLEND_INVSRCALPHA) {
            bi = BLEND_SRCALPHA_INVSRC;
        } else if (s->src_blend == D3D6BLEND_SRCALPHA && s->dest_blend == D3D6BLEND_ONE) {
            bi = BLEND_SRCALPHA_ONE;
        } else if (s->src_blend == D3D6BLEND_ONE && s->dest_blend == D3D6BLEND_ONE) {
            bi = BLEND_ONE_ONE;
        } else if (s->src_blend == D3D6BLEND_SRCALPHA && s->dest_blend == D3D6BLEND_SRCALPHA) {
            bi = BLEND_SRCALPHA_SRCALPHA;
        } else if (s->src_blend == D3D6BLEND_INVSRCALPHA && s->dest_blend == D3D6BLEND_INVSRCALPHA) {
            bi = BLEND_INVSRC_INVSRC;
        } else {
            /* Default to standard alpha blend for unhandled combos */
            bi = BLEND_SRCALPHA_INVSRC;
            WRAPPER_LOG("ApplyStateCache: unhandled blend combo src=%u dst=%u, using SRCALPHA_INVSRC",
                s->src_blend, s->dest_blend);
        }
        if (bi != s->current_blend_idx) {
            s->current_blend_idx = bi;
            ID3D11DeviceContext_OMSetBlendState(ctx, g_backend.blend_states[bi], NULL, 0xFFFFFFFF);
        }
    }

    /* Depth-stencil state */
    {
        int di;
        if (!s->z_enable && !s->z_write)      di = DS_Z_OFF_WRITE_OFF;
        else if (!s->z_enable && s->z_write)   di = DS_Z_OFF_WRITE_ON;
        else if (s->z_func == 1) {
            di = s->z_write ? DS_Z_ON_WRITE_ON_ALWAYS : DS_Z_ON_WRITE_OFF_ALWAYS;
        }
        else if (s->z_enable && s->z_write)    di = DS_Z_ON_WRITE_ON;
        else                                   di = DS_Z_ON_WRITE_OFF;

        if (di != s->current_ds_idx) {
            s->current_ds_idx = di;
            ID3D11DeviceContext_OMSetDepthStencilState(ctx, g_backend.ds_states[di], 0);
        }
    }

    /* Sampler state */
    {
        int si;
        int linear = (s->mag_filter >= 2 || s->min_filter >= 2);
        int clamp  = (s->tex_address_u == 3 || s->tex_address_v == 3);
        if (linear && clamp)       si = SAMP_LINEAR_CLAMP;
        else if (linear && !clamp) si = SAMP_LINEAR_WRAP;
        else if (!linear && clamp) si = SAMP_POINT_CLAMP;
        else                       si = SAMP_POINT_WRAP;

        if (si != s->current_samp_idx) {
            s->current_samp_idx = si;
            ID3D11DeviceContext_PSSetSamplers(ctx, 0, 1, &g_backend.sampler_states[si]);
        }
    }

    /* Pixel shader */
    Backend_SelectPixelShader();

    /* Update fog+alpha CB (contains alpha test state which changes per-draw) */
    Backend_UpdateFogCB();

    s->dirty = 0;
}

/* ========================================================================
 * Fullscreen quad rendering
 * ======================================================================== */

void Backend_DrawFullscreenQuad(ID3D11ShaderResourceView *srv)
{
    ID3D11DeviceContext *ctx = g_backend.context;
    D3D11_VIEWPORT vp;
    FLOAT vp_w = (FLOAT)(g_backend.target_width  > 0 ? g_backend.target_width  : g_backend.width);
    FLOAT vp_h = (FLOAT)(g_backend.target_height > 0 ? g_backend.target_height : g_backend.height);

    vp.TopLeftX = 0.0f;
    vp.TopLeftY = 0.0f;
    vp.Width    = vp_w;
    vp.Height   = vp_h;
    vp.MinDepth = 0.0f;
    vp.MaxDepth = 1.0f;
    ID3D11DeviceContext_RSSetViewports(ctx, 1, &vp);

    /* Switch to fullscreen VS + composite PS */
    ID3D11DeviceContext_VSSetShader(ctx, g_backend.vs_fullscreen, NULL, 0);
    ID3D11DeviceContext_PSSetShader(ctx, g_backend.ps_composite, NULL, 0);
    ID3D11DeviceContext_IASetInputLayout(ctx, NULL);
    ID3D11DeviceContext_IASetPrimitiveTopology(ctx, D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

    /* Bind source texture */
    ID3D11DeviceContext_PSSetShaderResources(ctx, 0, 1, &srv);

    /* Use point (nearest-neighbor) sampler for crisp pixel-perfect present */
    ID3D11DeviceContext_PSSetSamplers(ctx, 0, 1, &g_backend.sampler_states[SAMP_POINT_CLAMP]);

    /* Force opaque blit — the backbuffer is the final composed frame.
     * All transparency was resolved during rendering (alpha blend in
     * DrawPrimitive) and BltFast (color key skip). The present blit
     * should copy the result as-is to the swap chain. */
    ID3D11DeviceContext_OMSetBlendState(ctx, g_backend.blend_states[BLEND_OPAQUE], NULL, 0xFFFFFFFF);
    ID3D11DeviceContext_OMSetDepthStencilState(ctx, g_backend.ds_states[DS_Z_OFF_WRITE_OFF], 0);

    /* Draw 3 vertices (fullscreen triangle from SV_VertexID) */
    ID3D11DeviceContext_Draw(ctx, 3, 0);

    /* Restore game rendering state */
    ID3D11DeviceContext_VSSetShader(ctx, g_backend.vs_pretransformed, NULL, 0);
    ID3D11DeviceContext_IASetInputLayout(ctx, g_backend.input_layout);
    Backend_SelectPixelShader();

    /* Restore depth state from cache */
    ID3D11DeviceContext_OMSetDepthStencilState(ctx,
        g_backend.ds_states[g_backend.state.current_ds_idx], 0);

    /* Restore blend state from cache */
    ID3D11DeviceContext_OMSetBlendState(ctx,
        g_backend.blend_states[g_backend.state.current_blend_idx], NULL, 0xFFFFFFFF);

    /* Restore sampler from cache */
    ID3D11DeviceContext_PSSetSamplers(ctx, 0, 1,
        &g_backend.sampler_states[g_backend.state.current_samp_idx]);

    /* Unbind SRV to avoid D3D11 warning (RT and SRV conflict) */
    {
        ID3D11ShaderResourceView *null_srv = NULL;
        ID3D11DeviceContext_PSSetShaderResources(ctx, 0, 1, &null_srv);
    }
}

/* ========================================================================
 * Compositing: merge BltFast (2D) and D3D (3D) layers at present
 * ======================================================================== */

void Backend_EnsureCompositingTextures(int width, int height)
{
    HRESULT hr;

    if (g_backend.composite_tex &&
        g_backend.composite_w == width && g_backend.composite_h == height)
        return;

    /* Release old */
    if (g_backend.composite_srv)     { ID3D11ShaderResourceView_Release(g_backend.composite_srv);  g_backend.composite_srv = NULL; }
    if (g_backend.composite_tex)     { ID3D11Texture2D_Release(g_backend.composite_tex);           g_backend.composite_tex = NULL; }
    if (g_backend.composite_staging) { ID3D11Texture2D_Release(g_backend.composite_staging);       g_backend.composite_staging = NULL; }

    /* GPU texture (for rendering as quad) */
    {
        D3D11_TEXTURE2D_DESC td;
        ZeroMemory(&td, sizeof(td));
        td.Width  = (UINT)width;
        td.Height = (UINT)height;
        td.MipLevels = 1;
        td.ArraySize = 1;
        td.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
        td.SampleDesc.Count = 1;
        td.Usage = D3D11_USAGE_DEFAULT;
        td.BindFlags = D3D11_BIND_SHADER_RESOURCE;

        hr = ID3D11Device_CreateTexture2D(g_backend.device, &td, NULL, &g_backend.composite_tex);
        if (FAILED(hr)) {
            /* Fall back to B8G8R8A8 if B5G6R5 not supported */
            td.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
            hr = ID3D11Device_CreateTexture2D(g_backend.device, &td, NULL, &g_backend.composite_tex);
            if (FAILED(hr)) {
                WRAPPER_LOG("EnsureCompositingTextures: CreateTexture2D FAILED hr=0x%08lX", hr);
                return;
            }
        }

        hr = ID3D11Device_CreateShaderResourceView(g_backend.device,
            (ID3D11Resource*)g_backend.composite_tex, NULL, &g_backend.composite_srv);
        if (FAILED(hr)) {
            WRAPPER_LOG("EnsureCompositingTextures: CreateSRV FAILED hr=0x%08lX", hr);
            return;
        }

        /* Staging texture for CPU upload */
        td.Usage = D3D11_USAGE_STAGING;
        td.BindFlags = 0;
        td.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        hr = ID3D11Device_CreateTexture2D(g_backend.device, &td, NULL, &g_backend.composite_staging);
        if (FAILED(hr)) {
            WRAPPER_LOG("EnsureCompositingTextures: staging FAILED hr=0x%08lX", hr);
            return;
        }
    }

    g_backend.composite_w = width;
    g_backend.composite_h = height;
    WRAPPER_LOG("EnsureCompositingTextures: %dx%d OK", width, height);
}

/**
 * Upload sys_buffer to composite texture with color-key alpha.
 * Black pixels (R5G6B5 == 0x0000) get alpha=0 (transparent).
 * All other pixels get alpha=1 (opaque HUD content).
 */
static void Backend_UploadOverlayWithAlpha(WrapperSurface *s)
{
    DWORD row32 = s->width * 4;
    BYTE *buf32;
    DWORD y;

    if (!s->sys_buffer || s->bpp != 16) return;

    Backend_EnsureCompositingTextures((int)s->width, (int)s->height);
    if (!g_backend.composite_tex) return;

    buf32 = (BYTE*)malloc(row32 * s->height);
    if (!buf32) return;

    for (y = 0; y < s->height; y++) {
        uint16_t *src16 = (uint16_t*)((BYTE*)s->sys_buffer + y * s->pitch);
        uint32_t *dst32 = (uint32_t*)(buf32 + y * row32);
        DWORD x;
        for (x = 0; x < s->width; x++) {
            uint16_t c = src16[x];
            if (c == 0) {
                dst32[x] = 0x00000000;  /* color key → fully transparent */
            } else {
                uint32_t r = ((c >> 11) & 0x1F) * 255 / 31;
                uint32_t g = ((c >> 5)  & 0x3F) * 255 / 63;
                uint32_t b = ((c)       & 0x1F) * 255 / 31;
                dst32[x] = 0xFF000000 | (r << 16) | (g << 8) | b;
            }
        }
    }

    ID3D11DeviceContext_UpdateSubresource(g_backend.context,
        (ID3D11Resource*)g_backend.composite_tex, 0, NULL,
        buf32, row32, 0);
    free(buf32);
}

void Backend_CompositeAndPresent(WrapperSurface *rt_surface, RECT *srcRect, RECT *dstRect)
{
    HRESULT hr;
    static int s_log_count = 0;
    ID3D11DeviceContext *ctx = g_backend.context;

    (void)srcRect; (void)dstRect;
    if (!g_backend.swap_chain || !ctx) return;

    Backend_EnforceWindowSize();

    /* Two-layer composite: when 3D rendered this frame, the 3D scene lives
     * on the D3D11 texture (via RTV). If BltFast also wrote HUD overlay to
     * sys_buffer, FlushDirty would destroy the 3D scene by overwriting the
     * GPU texture. Instead, draw them as separate layers:
     *   Layer 1: backbuffer D3D11 texture (3D scene) — opaque
     *   Layer 2: sys_buffer (BltFast HUD overlay) — alpha blended
     *
     * Even if no BltFast wrote this frame (dirty=0), we must NOT FlushDirty
     * because that would overwrite the 3D scene with stale sys_buffer data. */
    if (g_backend.scene_rendered && rt_surface && rt_surface->d3d11_srv) {

        /* Upload BltFast overlay to a SECOND composite texture with color-key alpha
         * (only if BltFast wrote this frame; skip if no HUD content) */
        int has_overlay = (rt_surface->dirty && rt_surface->sys_buffer);

        /* Unbind the backbuffer as RT to avoid D3D11 RT/SRV hazard, then
         * copy it to the composite texture for safe reading as SRV */
        ID3D11DeviceContext_OMSetRenderTargets(ctx, 0, NULL, NULL);

        Backend_EnsureCompositingTextures((int)rt_surface->width, (int)rt_surface->height);
        if (g_backend.composite_tex) {
            ID3D11DeviceContext_CopyResource(ctx,
                (ID3D11Resource*)g_backend.composite_tex,
                (ID3D11Resource*)rt_surface->d3d11_texture);
        }

        /* Bind swap chain as render target */
        ID3D11DeviceContext_OMSetRenderTargets(ctx, 1, &g_backend.swap_rtv, NULL);

        /* Layer 1: draw 3D scene (opaque) from the COPY */
        Backend_DrawFullscreenQuad(g_backend.composite_srv ? g_backend.composite_srv : rt_surface->d3d11_srv);

        /* DrawFullscreenQuad changes VS/PS/InputLayout/Sampler — invalidate
         * all cached indices so next ApplyStateCache actually re-sets them. */
        g_backend.state.current_ps_idx = -1;
        g_backend.state.current_samp_idx = -1;
        g_backend.state.current_blend_idx = -1;
        g_backend.state.current_ds_idx = -1;
        g_backend.state.dirty = 1;

        /* Now upload BltFast overlay to composite texture (reusing it for layer 2) */
        if (has_overlay)
            Backend_UploadOverlayWithAlpha(rt_surface);

        /* Layer 2: draw BltFast overlay (alpha blended) — only if BltFast wrote */
        if (has_overlay && g_backend.composite_srv) {
            ID3D11DeviceContext_VSSetShader(ctx, g_backend.vs_fullscreen, NULL, 0);
            ID3D11DeviceContext_PSSetShader(ctx, g_backend.ps_composite, NULL, 0);
            ID3D11DeviceContext_IASetInputLayout(ctx, NULL);
            ID3D11DeviceContext_IASetPrimitiveTopology(ctx, D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
            ID3D11DeviceContext_PSSetShaderResources(ctx, 0, 1, &g_backend.composite_srv);
            ID3D11DeviceContext_PSSetSamplers(ctx, 0, 1,
                &g_backend.sampler_states[SAMP_POINT_CLAMP]);

            /* Alpha blend: overlay pixels with alpha=1 replace, alpha=0 show through */
            ID3D11DeviceContext_OMSetBlendState(ctx,
                g_backend.blend_states[BLEND_SRCALPHA_INVSRC], NULL, 0xFFFFFFFF);
            ID3D11DeviceContext_OMSetDepthStencilState(ctx,
                g_backend.ds_states[DS_Z_OFF_WRITE_OFF], 0);

            ID3D11DeviceContext_Draw(ctx, 3, 0);

            /* Restore rendering state.
             * Invalidate current_ps_idx so SelectPixelShader actually
             * re-sets the shader (composite changed it to ps_composite). */
            ID3D11DeviceContext_VSSetShader(ctx, g_backend.vs_pretransformed, NULL, 0);
            ID3D11DeviceContext_IASetInputLayout(ctx, g_backend.input_layout);
            g_backend.state.current_ps_idx = -1;
            Backend_SelectPixelShader();
            ID3D11DeviceContext_OMSetDepthStencilState(ctx,
                g_backend.ds_states[g_backend.state.current_ds_idx], 0);
            ID3D11DeviceContext_OMSetBlendState(ctx,
                g_backend.blend_states[g_backend.state.current_blend_idx], NULL, 0xFFFFFFFF);
            ID3D11DeviceContext_PSSetSamplers(ctx, 0, 1,
                &g_backend.sampler_states[g_backend.state.current_samp_idx]);
            {
                ID3D11ShaderResourceView *null_srv = NULL;
                ID3D11DeviceContext_PSSetShaderResources(ctx, 0, 1, &null_srv);
            }
        }

        if (s_log_count < 200) {
            WRAPPER_LOG("CompositeAndPresent[%d]: TWO-LAYER scene=%d dirty=%d overlay=%d srv=%p",
                s_log_count, g_backend.scene_rendered,
                rt_surface ? rt_surface->dirty : -1,
                (rt_surface && rt_surface->dirty && rt_surface->sys_buffer) ? 1 : 0,
                rt_surface ? rt_surface->d3d11_srv : NULL);
            s_log_count++;
        }

        rt_surface->dirty = 0;
        /* Do NOT clear scene_rendered here — the game may call Blt to primary
         * multiple times per frame. Clearing here causes the second present to
         * take the SINGLE-LAYER path, which FlushDirty's the sys_buffer and
         * OVERWRITES the 3D scene. scene_rendered is cleared in BeginScene
         * when the next frame starts. */

    } else {
        /* Single-layer path: no 3D this frame, just flush and present.
         * Used for frontend menus (BltFast only, no DrawPrimitive). */
        if (s_log_count < 200) {
            WRAPPER_LOG("CompositeAndPresent[%d]: SINGLE-LAYER scene=%d dirty=%d rt_srv=%p",
                s_log_count, g_backend.scene_rendered,
                rt_surface ? rt_surface->dirty : -1,
                rt_surface ? rt_surface->d3d11_srv : NULL);
            s_log_count++;
        }

        if (rt_surface && rt_surface->dirty)
            WrapperSurface_FlushDirty(rt_surface);

        if (rt_surface && rt_surface->d3d11_srv) {
            ID3D11DeviceContext_OMSetRenderTargets(ctx, 1, &g_backend.swap_rtv, NULL);
            Backend_DrawFullscreenQuad(rt_surface->d3d11_srv);
        }
        /* Do NOT clear scene_rendered here either — same reason as TWO-LAYER path */
    }

    hr = IDXGISwapChain_Present(g_backend.swap_chain, 1, 0);
    if (FAILED(hr) && s_log_count < 10) {
        WRAPPER_LOG("CompositeAndPresent: Present FAILED hr=0x%08lX", hr);
    }

    /* Restore game RT (backbuffer, not swap chain) */
    if (g_backend.backbuffer && g_backend.backbuffer->d3d11_rtv) {
        ID3D11DeviceContext_OMSetRenderTargets(ctx, 1,
            &g_backend.backbuffer->d3d11_rtv, g_backend.depth_dsv);
    }
}

/* ========================================================================
 * WrapperClipper - minimal IDirectDrawClipper stub
 * ======================================================================== */

typedef struct WrapperClipperVtbl WrapperClipperVtbl;

struct WrapperClipperVtbl {
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(WrapperClipper *self, REFIID riid, void **ppv);
    ULONG   (STDMETHODCALLTYPE *AddRef)(WrapperClipper *self);
    ULONG   (STDMETHODCALLTYPE *Release)(WrapperClipper *self);
    HRESULT (STDMETHODCALLTYPE *GetClipList)(WrapperClipper *self, RECT *rect, void *rgndata, DWORD *size);
    HRESULT (STDMETHODCALLTYPE *GetHWnd)(WrapperClipper *self, HWND *hwnd);
    HRESULT (STDMETHODCALLTYPE *Initialize)(WrapperClipper *self, void *ddraw, DWORD flags);
    HRESULT (STDMETHODCALLTYPE *IsClipListChanged)(WrapperClipper *self, BOOL *changed);
    HRESULT (STDMETHODCALLTYPE *SetClipList)(WrapperClipper *self, void *rgndata, DWORD flags);
    HRESULT (STDMETHODCALLTYPE *SetHWnd)(WrapperClipper *self, DWORD flags, HWND hwnd);
};

static HRESULT STDMETHODCALLTYPE Clipper_QueryInterface(WrapperClipper *self, REFIID riid, void **ppv)
{
    (void)riid;
    if (!ppv) return E_POINTER;
    *ppv = self;
    InterlockedIncrement(&self->ref_count);
    return S_OK;
}

static ULONG STDMETHODCALLTYPE Clipper_AddRef(WrapperClipper *self)
{
    return (ULONG)InterlockedIncrement(&self->ref_count);
}

static ULONG STDMETHODCALLTYPE Clipper_Release(WrapperClipper *self)
{
    LONG ref = InterlockedDecrement(&self->ref_count);
    if (ref <= 0) {
        HeapFree(GetProcessHeap(), 0, self);
        return 0;
    }
    return (ULONG)ref;
}

static HRESULT STDMETHODCALLTYPE Clipper_GetClipList(WrapperClipper *self, RECT *rect, void *rgndata, DWORD *size)
{ (void)self; (void)rect; (void)rgndata; (void)size; WRAPPER_STUB("Clipper::GetClipList"); }

static HRESULT STDMETHODCALLTYPE Clipper_GetHWnd(WrapperClipper *self, HWND *hwnd)
{
    if (!hwnd) return E_POINTER;
    *hwnd = self->hwnd;
    return DD_OK;
}

static HRESULT STDMETHODCALLTYPE Clipper_Initialize(WrapperClipper *self, void *ddraw, DWORD flags)
{ (void)self; (void)ddraw; (void)flags; WRAPPER_STUB("Clipper::Initialize"); }

static HRESULT STDMETHODCALLTYPE Clipper_IsClipListChanged(WrapperClipper *self, BOOL *changed)
{
    (void)self;
    if (changed) *changed = FALSE;
    return DD_OK;
}

static HRESULT STDMETHODCALLTYPE Clipper_SetClipList(WrapperClipper *self, void *rgndata, DWORD flags)
{ (void)self; (void)rgndata; (void)flags; WRAPPER_STUB("Clipper::SetClipList"); }

static HRESULT STDMETHODCALLTYPE Clipper_SetHWnd(WrapperClipper *self, DWORD flags, HWND hwnd)
{
    (void)flags;
    self->hwnd = hwnd;
    return DD_OK;
}

static WrapperClipperVtbl s_clipper_vtbl = {
    Clipper_QueryInterface,
    Clipper_AddRef,
    Clipper_Release,
    Clipper_GetClipList,
    Clipper_GetHWnd,
    Clipper_Initialize,
    Clipper_IsClipListChanged,
    Clipper_SetClipList,
    Clipper_SetHWnd,
};

WrapperClipper* WrapperClipper_Create(void)
{
    WrapperClipper *clip = (WrapperClipper*)HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, sizeof(WrapperClipper));
    if (!clip) return NULL;
    clip->vtbl = (void*)&s_clipper_vtbl;
    clip->ref_count = 1;
    clip->hwnd = NULL;
    WRAPPER_LOG("WrapperClipper_Create: %p", clip);
    return clip;
}
