/**
 * td5_changelog.h -- In-game CHANGELOG screen content (TD5RE source port).
 *
 * A flat, scrollable list of lines rendered by Screen_Changelog
 * (frontend_changelog_render in td5_frontend.c). The most recent 7 days are
 * itemised day-by-day; everything before that is condensed into an "EARLIER
 * HIGHLIGHTS" summary of the biggest changes since the port began (2026-03-31).
 *
 * Keep each CL_ITEM line <= ~62 characters so it fits the body column without
 * running under the scrollbar. Add new entries at the TOP of LAST 7 DAYS and,
 * once they age out, fold the gist into EARLIER HIGHLIGHTS.
 *
 * Included by exactly ONE translation unit (td5_frontend.c); the array is
 * file-static there.
 */
#ifndef TD5_CHANGELOG_H
#define TD5_CHANGELOG_H

/* Line styles (see frontend_changelog_render for the colours/indent). */
#define CL_SECTION 0   /* gold section heading                     */
#define CL_DATE    1   /* cyan date / sub-heading                  */
#define CL_ITEM    2   /* white bullet line                        */
#define CL_BLANK   3   /* vertical spacer (text ignored)           */

typedef struct {
    int         style;
    const char *text;
} TD5_ChangelogLine;

static const TD5_ChangelogLine k_changelog_lines[] = {

    { CL_SECTION, "LAST 7 DAYS" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 22" },
    { CL_ITEM,    "POLISH: Spanish text now renders entirely in the menu" },
    { CL_ITEM,    "  font - vowel accents are dropped (MENU PRINCIPAL," },
    { CL_ITEM,    "  GRAFICAS) and the N-with-tilde + inverted ?/! are" },
    { CL_ITEM,    "  built into the font, so no more mismatched fallback" },
    { CL_ITEM,    "  typeface on accented characters." },
    { CL_ITEM,    "DEV: two new automated test scenarios - police start" },
    { CL_ITEM,    "  chasing speeders (new per-car pursuit readout) and" },
    { CL_ITEM,    "  reverse-direction circuits complete their laps." },
    { CL_ITEM,    "DEV: four more regression scenarios - Courmayeur" },
    { CL_ITEM,    "  loads without crashing, the game survives a forced" },
    { CL_ITEM,    "  GPU reset, city time trials no longer end instantly," },
    { CL_ITEM,    "  and power-ups stay out of SIMULATION races." },
    { CL_ITEM,    "DEV: the test harness now catches game crashes instead" },
    { CL_ITEM,    "  of hiding them - it saves the crash report and marks" },
    { CL_ITEM,    "  the run CRASHED; GPU crash logs now name the scene." },
    { CL_ITEM,    "DEV: GPU crash reports now list the last 256 draws +" },
    { CL_ITEM,    "  each frame's Present, so a crash points at the exact" },
    { CL_ITEM,    "  GPU call (a rare driver fault sits in Present, not a" },
    { CL_ITEM,    "  draw - still under investigation)." },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 21" },
    { CL_ITEM,    "NEW: the game speaks Spanish! OPTIONS -> LANGUAGE picks" },
    { CL_ITEM,    "  ENGLISH or ESPANOL (AR) - rioplatense Spanish across" },
    { CL_ITEM,    "  menus, race options, lobbies, HUD, pause and results." },
    { CL_ITEM,    "  Switches live (no restart), remembered in td5re.ini," },
    { CL_ITEM,    "  and accented text renders properly in every menu font." },
    { CL_ITEM,    "  Translations live in re/assets/frontend/lang/es_AR.txt" },
    { CL_ITEM,    "  - edit that file to tweak or add wording." },
    { CL_ITEM,    "DEV: live-control v2 - remote testing can now read per-" },
    { CL_ITEM,    "  car race state (position/lap/speed/damage/power-ups)," },
    { CL_ITEM,    "  drive any car's controls per slot, and capture clean" },
    { CL_ITEM,    "  screenshots even with the window hidden. Powers a new" },
    { CL_ITEM,    "  automated scenario suite (cop chase, drag finish," },
    { CL_ITEM,    "  crash damage, power-ups, menu navigation)." },
    { CL_ITEM,    "FIX: starting a race right after a drag race no longer" },
    { CL_ITEM,    "  crashes the game (a stale route buffer was freed too" },
    { CL_ITEM,    "  early and read back during setup)" },
    { CL_ITEM,    "NEW: one RACE OPTIONS screen for every mode. GAME" },
    { CL_ITEM,    "  OPTIONS is gone - every game-behaviour setting" },
    { CL_ITEM,    "  (traffic, police, difficulty, dynamics, checkpoints," },
    { CL_ITEM,    "  power-ups, damage, collisions, lane assist, tutorial)" },
    { CL_ITEM,    "  now lives on RACE OPTIONS, reachable from each mode's" },
    { CL_ITEM,    "  track select and shown for drag/cup as a pre-launch" },
    { CL_ITEM,    "  step. Each mode shows only the rows it needs (paged" },
    { CL_ITEM,    "  when long, with a PAGE x/y counter that wraps)." },
    { CL_ITEM,    "  Online: the host's race options apply to everyone." },
    { CL_ITEM,    "NEW: each options screen has its own title (MULTIPLAYER" },
    { CL_ITEM,    "  OPTIONS, SOUND OPTIONS, ...) and no longer asks" },
    { CL_ITEM,    "  \"GO BACK?\" when you leave it." },
    { CL_ITEM,    "NEW: your name is now ONE multiplayer nickname used" },
    { CL_ITEM,    "  everywhere (race results, high scores, online) -" },
    { CL_ITEM,    "  the separate Options PLAYER NAME was merged into it." },
    { CL_ITEM,    "NEW: Multiplayer Options adds GAME PORT + UPnP toggles;" },
    { CL_ITEM,    "  the redundant PLAYERS + NET MODE rows were removed." },
    { CL_ITEM,    "NEW: CATCHUP (AI rubber-band) is now a per-race option" },
    { CL_ITEM,    "  on RACE OPTIONS in multiplayer, not a global toggle." },
    { CL_ITEM,    "NEW: Quick Race has its own RACE OPTIONS screen (opponents," },
    { CL_ITEM,    "  physics + dev debug: player-AI, auto-throttle, AI" },
    { CL_ITEM,    "  screens, span offset, game speed, end-at-checkpoint)." },
    { CL_ITEM,    "FIX: a GPU driver reset (TDR) during a race no longer" },
    { CL_ITEM,    "  crashes on the way to the results screen - the HUD" },
    { CL_ITEM,    "  dial and text now rebuild after a device reset" },
    { CL_ITEM,    "FIX: split-screen force feedback now follows your OWN" },
    { CL_ITEM,    "  car again - after swapping screens your wheel/pad no" },
    { CL_ITEM,    "  longer rumbles from another player's crashes or gears" },
    { CL_ITEM,    "NEW: traffic density now scales per driver. Each racer" },
    { CL_ITEM,    "  (you and each AI) supports its own stream of up to 16" },
    { CL_ITEM,    "  cars; drivers close together share one stream, and a" },
    { CL_ITEM,    "  driver who breaks away opens their own - so the road" },
    { CL_ITEM,    "  stays busy wherever the action is. Traffic pool" },
    { CL_ITEM,    "  raised to 64 (room for ~4 spread-out drivers at full" },
    { CL_ITEM,    "  density). TD5RE_TRAFFIC_PERPLAYER_CAP=0 = old cap." },
    { CL_ITEM,    "FIX: the chase camera no longer wobbles at the start" },
    { CL_ITEM,    "  of a race after the first one, especially in multi-" },
    { CL_ITEM,    "  player split-screen. Camera smoothing is now reset" },
    { CL_ITEM,    "  for every pane at the start of each race." },
    { CL_ITEM,    "CHANGE: crash screen-shake no longer rattles constantly" },
    { CL_ITEM,    "  in a crowded pack - light bumps don't shake, and a" },
    { CL_ITEM,    "  new shake won't re-trigger until the last one settles." },
    { CL_ITEM,    "DEV: new opt-in live-control socket (--Control=1) lets a" },
    { CL_ITEM,    "  test tool drive a running game (launch races, jump" },
    { CL_ITEM,    "  menus, inject input). Off by default; dev builds only." },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 20" },
    { CL_ITEM,    "FIX: RACE OPTIONS power-ups now offers OFF / CASUAL /" },
    { CL_ITEM,    "  CHAOS (incl. split-screen setup) - CHAOS was hidden" },
    { CL_ITEM,    "  behind an OFF/ON-only toggle." },
    { CL_ITEM,    "NEW: shift-up (green) and shift-down (amber) arrows now" },
    { CL_ITEM,    "  flash above the rev dial when it's time to change gear" },
    { CL_ITEM,    "  - up near the redline, down when the engine is lugging" },
    { CL_ITEM,    "FIX: analog steering now has a proper centre deadzone so" },
    { CL_ITEM,    "  a drifting stick no longer steers the car on its own" },
    { CL_ITEM,    "  (helped extra split-screen pads); full lock is kept" },
    { CL_ITEM,    "FIX: Traffic Battle no longer runs out of traffic - a" },
    { CL_ITEM,    "  wrecked car now clears itself after 10 seconds so its" },
    { CL_ITEM,    "  slot frees up and fresh cars keep coming." },
    { CL_ITEM,    "FIX: recovering from a graphics-card hang (driver TDR)" },
    { CL_ITEM,    "  no longer crashes on the first frame back - the" },
    { CL_ITEM,    "  display layer was re-binding a texture from the old," },
    { CL_ITEM,    "  freed device. Seen after a TDR while exiting the" },
    { CL_ITEM,    "  attract/demo race. Now rebuilds textures on use." },
    { CL_BLANK,   "" },
    { CL_DATE,    "July 19" },
    { CL_ITEM,    "FIX: View Replay cameras now cut between trackside" },
    { CL_ITEM,    "  shots again and stop drifting at the race start -" },
    { CL_ITEM,    "  the replay was freezing the car's track position, so" },
    { CL_ITEM,    "  the cinematic camera never switched view" },
    { CL_ITEM,    "FIX: frame rate is now capped when VSync is off, so" },
    { CL_ITEM,    "  menus/results no longer run at tens of thousands of" },
    { CL_ITEM,    "  FPS and overload the GPU (this prevents the hang" },
    { CL_ITEM,    "  below). Set TD5RE_FRAME_CAP=0 for uncapped." },
    { CL_ITEM,    "FIX: if the graphics card hangs (a driver TDR) the" },
    { CL_ITEM,    "  game now rebuilds the display and keeps running" },
    { CL_ITEM,    "  instead of freezing on a black screen - seen when" },
    { CL_ITEM,    "  finishing a race on some tracks (e.g. Montego Bay)" },
    { CL_BLANK,   "" },
    { CL_DATE,    "July 18" },
    { CL_ITEM,    "FIX: View Replay now matches the race you drove - it" },
    { CL_ITEM,    "  records the exact path of every car and traffic" },
    { CL_ITEM,    "  vehicle each tick and plays it straight back, so" },
    { CL_ITEM,    "  opponents and traffic no longer drift off into a" },
    { CL_ITEM,    "  different race" },
    { CL_ITEM,    "FIX: headlights no longer switch on in broad daylight" },
    { CL_ITEM,    "  on Montego Bay and Tokyo - the auto-dark sky test" },
    { CL_ITEM,    "  was set too high and mistook their bright daytime" },
    { CL_ITEM,    "  skies for dusk; night/dusk tracks (Moscow," },
    { CL_ITEM,    "  Washington) still light up correctly" },
    { CL_ITEM,    "TUNE: cars hold speed better on uphill climbs - the" },
    { CL_ITEM,    "  slope slow-down is now much gentler (65% weaker)" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 11" },
    { CL_ITEM,    "FIX: roadside fences, foliage and scenery no longer" },
    { CL_ITEM,    "  render from one side only or lose their textures -" },
    { CL_ITEM,    "  the banner detector was mistaking double-sided" },
    { CL_ITEM,    "  fences for signs and culling a face; now off by" },
    { CL_ITEM,    "  default so they render correctly on every track" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 10" },
    { CL_ITEM,    "FIX: Game Options now save when you leave with Back," },
    { CL_ITEM,    "  not only with OK - toggling TUTORIAL (or any option)" },
    { CL_ITEM,    "  off and backing out now sticks instead of reverting" },
    { CL_ITEM,    "NEW: breaking down no longer loses you the race. The" },
    { CL_ITEM,    "  car parks with a CAR BROKE DOWN / PRESS TO CONTINUE" },
    { CL_ITEM,    "  prompt; press recovery to be towed 30 spans back," },
    { CL_ITEM,    "  fully repaired, with the camera gliding to the new" },
    { CL_ITEM,    "  spot and a brief invulnerable ghost that blinks out" },
    { CL_ITEM,    "  (needs CAR DAMAGE on)" },
    { CL_ITEM,    "FIX: Montego Bay's countdown camera fly-in is back -" },
    { CL_ITEM,    "  now that the camera no longer dips underground, the" },
    { CL_ITEM,    "  cinematic sweep plays during the 3-2-1 like on every" },
    { CL_ITEM,    "  other track" },
    { CL_ITEM,    "FIX: the race-end wipe (the black bars that close" },
    { CL_ITEM,    "  in when you DON'T finish first) is now solid" },
    { CL_ITEM,    "  black instead of see-through - the foliage" },
    { CL_ITEM,    "  anti-aliasing was forcing it half-transparent" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 7" },
    { CL_ITEM,    "FIX: police now actually give chase - the pursuit" },
    { CL_ITEM,    "  trigger window is much wider so cops lock on when" },
    { CL_ITEM,    "  you speed past instead of almost never" },
    { CL_ITEM,    "FIX: a cop that crashes mid-chase now recovers and" },
    { CL_ITEM,    "  rejoins the pursuit instead of staying wrecked" },
    { CL_ITEM,    "  for the rest of the race" },
    { CL_ITEM,    "FIX: traffic cars change lanes smoothly - no more" },
    { CL_ITEM,    "  rapid lane flip-flopping that disrupted the flow" },
    { CL_ITEM,    "FIX: traffic cars that get wedged/stuck now free" },
    { CL_ITEM,    "  themselves after a few seconds instead of" },
    { CL_ITEM,    "  blocking the road for the whole race" },
    { CL_ITEM,    "FIX: the end-of-race transition is now fully opaque -" },
    { CL_ITEM,    "  the race no longer shows through the RESULTS screen" },
    { CL_ITEM,    "  as it fades out" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 6" },
    { CL_ITEM,    "FIX: START/FINISH banners and other track signs no" },
    { CL_ITEM,    "  longer look see-through - they now render fully" },
    { CL_ITEM,    "  solid instead of 50% transparent" },
    { CL_ITEM,    "FIX: in split-screen on Montego Bay, player 1's view no" },
    { CL_ITEM,    "  longer dips below the ground for a few frames during" },
    { CL_ITEM,    "  the countdown of the first race of a session" },
    { CL_ITEM,    "FIX: the PENDING TO TEST screen no longer pops the first" },
    { CL_ITEM,    "  item's details box the moment you open it - the box" },
    { CL_ITEM,    "  now opens only when you press ENTER on a row" },
    { CL_ITEM,    "FIX: the race-countdown camera sweep is back (it was" },
    { CL_ITEM,    "  accidentally disabled on EVERY track while fixing" },
    { CL_ITEM,    "  Montego Bay's out-of-frame countdown; Montego alone" },
    { CL_ITEM,    "  keeps the steady close-up camera)" },
    { CL_ITEM,    "FIX: buildings/walls no longer show through each other" },
    { CL_ITEM,    "  (regression from the July 5 foliage-AA update: any" },
    { CL_ITEM,    "  cutout texture stopped writing depth)" },
    { CL_ITEM,    "FIX: street lamps no longer render as solid black" },
    { CL_ITEM,    "  balls (Moscow etc.) - glow sprites keep the game's" },
    { CL_ITEM,    "  own blending instead of the foliage-AA override" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 5" },
    { CL_ITEM,    "FIX: DEFORMATION can now turn body dents fully OFF -" },
    { CL_ITEM,    "  it's now Low / Normal / High / Off. Independent of" },
    { CL_ITEM,    "  CAR TOUGHNESS -- health/wreck still work as set." },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 4" },
    { CL_ITEM,    "First-race tutorial now explains special modes (Cop" },
    { CL_ITEM,    "  Chase, Drag Race, Traffic Battle, Infect, Cup) in" },
    { CL_ITEM,    "  one short line" },
    { CL_ITEM,    "Pause menu confirm popup (END RACE NOW, RESTART, etc.)" },
    { CL_ITEM,    "  now scales correctly on high-resolution displays" },
    { CL_ITEM,    "Race-end transition: HUD text no longer flashes through" },
    { CL_ITEM,    "  the black screen wipe (most visible in split-screen)" },
    { CL_ITEM,    "Cop Chase RANDOM COP: whoever gets drawn as the cop" },
    { CL_ITEM,    "  now drives a police car, not their originally-" },
    { CL_ITEM,    "  picked car" },
    { CL_ITEM,    "Fixed: joystick 1 could show an older CHANGE VIEW" },
    { CL_ITEM,    "  button than other joysticks after visiting Controller" },
    { CL_ITEM,    "  Setup; all pads now share the same default" },
    { CL_ITEM,    "Controls tutorial: shorter arrows for BRAKE, ACCELERATE," },
    { CL_ITEM,    "  RESET CAR, PAUSE and REAR VIEW; race audio now mutes" },
    { CL_ITEM,    "  while the tutorial is on screen" },
    { CL_ITEM,    "FIX: CAR TOUGHNESS can now turn damage fully OFF -" },
    { CL_ITEM,    "  it's now Low / Medium / High / Off (was Low/Norm/High," },
    { CL_ITEM,    "  with no way to disable damage from Race Options)" },
    { CL_ITEM,    "Fixed: reset-car recovery now only patches you up 20%" },
    { CL_ITEM,    "  (was a free full repair) and the camera snaps back to" },
    { CL_ITEM,    "  normal instead of staying spun after a broken-down car" },
    { CL_ITEM,    "  recovers" },
    { CL_ITEM,    "FIX: 2D tree/foliage edges no longer pick up a fixed" },
    { CL_ITEM,    "  sky-blue tint regardless of what's actually behind" },
    { CL_ITEM,    "  them, and no longer show a faint border line at the" },
    { CL_ITEM,    "  very edge of the sprite (both were side effects of" },
    { CL_ITEM,    "  the anti-aliasing added earlier today)" },
    { CL_ITEM,    "Fixed: split-screen headlights could turn off and stay" },
    { CL_ITEM,    "  off for a player even in a later tunnel - each car" },
    { CL_ITEM,    "  now senses its own surroundings" },
    { CL_ITEM,    "FIX: Bern's START banner no longer reads backwards -" },
    { CL_ITEM,    "  a leftover from the overhead-banner mirror fix that" },
    { CL_ITEM,    "  needed a per-track correction on this one gantry" },
    { CL_ITEM,    "Fixed: split-screen Drag Race sometimes launched the" },
    { CL_ITEM,    "  wrong track (leftover from a prior race) instead of" },
    { CL_ITEM,    "  the drag strip" },
    { CL_ITEM,    "Cop Chase (MP): cops' sirens now start ON by default" },
    { CL_ITEM,    "  each race - press horn to turn one off if you want" },
    { CL_ITEM,    "Cop Chase (Net play): RESTART RACE now re-rolls who" },
    { CL_ITEM,    "  gets picked as the cop, instead of the same player" },
    { CL_ITEM,    "  every time" },
    { CL_ITEM,    "Net play: the host can now pick the GAME MODE from" },
    { CL_ITEM,    "  the network lobby - Race, Drag Race, Traffic" },
    { CL_ITEM,    "  Battle and Cop Chase all play over the network" },
    { CL_ITEM,    "Net play: ARCADE dynamics work online too (power-up" },
    { CL_ITEM,    "  boxes + big-hit collisions, in sync on every PC)" },
    { CL_ITEM,    "Net play: CUP championships run over the network -" },
    { CL_ITEM,    "  multi-race series, points, standings and auto-teams" },
    { CL_ITEM,    "Net play: Cop Chase INFECT + the COPS / SUSPECTS" },
    { CL_ITEM,    "  results table now work online" },
    { CL_ITEM,    "Net play: other players now show their names AND" },
    { CL_ITEM,    "  their own colour on results / standings / podium" },
    { CL_ITEM,    "Lane Assist no longer aims at the sidewalk on some TD6" },
    { CL_ITEM,    "  tracks (was pulling the car off the true road centre)" },
    { CL_ITEM,    "Headlights now sense the surroundings: they switch on" },
    { CL_ITEM,    "  in tunnels and dim stretches (e.g. Bern's tunnels)" },
    { CL_ITEM,    "  and across dark tracks with a night sky (e.g. Moscow)," },
    { CL_ITEM,    "  and switch off again in bright daylight" },
    { CL_ITEM,    "Cars no longer pick up a coloured tint from the track" },
    { CL_ITEM,    "  lighting (e.g. the reddish cast on Bern) - car bodies" },
    { CL_ITEM,    "  stay neutral while the scenery keeps its colour" },
    { CL_ITEM,    "Track select: new RACE OPTIONS button opens a screen" },
    { CL_ITEM,    "  gathering every race option in one place -- opponents," },
    { CL_ITEM,    "  traffic, police, difficulty and dynamics, plus new" },
    { CL_ITEM,    "  checkpoint timers, power-ups, car toughness and" },
    { CL_ITEM,    "  deformation. The main column keeps track, direction" },
    { CL_ITEM,    "  and laps." },
    { CL_ITEM,    "FIX: the LAPS selector now shows on TD5 circuit" },
    { CL_ITEM,    "  tracks -- it was wrongly hidden on reverse-capable" },
    { CL_ITEM,    "  lap circuits such as Newcastle." },
    { CL_ITEM,    "2D trees / foliage now have smooth anti-aliased edges" },
    { CL_ITEM,    "  instead of jagged, blocky cutouts (Switzerland etc.)" },
    { CL_ITEM,    "FIX: overhead track banners no longer render garbled /" },
    { CL_ITEM,    "  mirrored (e.g. Tokyo's STAGE banners) - the wrong-facing" },
    { CL_ITEM,    "  side of double-sided signs is now hidden on every track" },
    { CL_ITEM,    "HIGH SCORES now show the same values as the race" },
    { CL_ITEM,    "  results (added COLLISIONS and AIR TIME columns)" },
    { CL_ITEM,    "Leaderboard celebrity names now show in FULL" },
    { CL_ITEM,    "  (e.g. Michael Schumacher, Lewis Hamilton)" },
    { CL_ITEM,    "Default best times reset to a 5-10 minute range" },
    { CL_ITEM,    "Single-player CUPS removed from the High Scores list" },
    { CL_ITEM,    "Split-screen multiplayer results are now recorded to" },
    { CL_ITEM,    "  the high scores (every player, by profile name)" },
    { CL_ITEM,    "FIX: race-start camera stays close to your car instead of" },
    { CL_ITEM,    "  swinging out over open water/off-track on coastal grids" },
    { CL_ITEM,    "  like Montego Bay" },
    { CL_ITEM,    "Game Options: PLAYER NAME is now edited in place, at" },
    { CL_ITEM,    "  full size, instead of a separate pop-up box" },
    { CL_ITEM,    "Game Options: the DAMAGE BAR row is now just DAMAGE -" },
    { CL_ITEM,    "  ON enables car damage AND the damage bar, OFF turns" },
    { CL_ITEM,    "  both off" },
    { CL_ITEM,    "Game Options: the PREV / OK / NEXT buttons now line up" },
    { CL_ITEM,    "  under the width of the option rows above them" },
    { CL_ITEM,    "Controller tutorial now appears whenever TUTORIAL is ON," },
    { CL_ITEM,    "  including on keyboard (it used to be skipped unless a" },
    { CL_ITEM,    "  gamepad was in use)" },
    { CL_ITEM,    "PENDING TO TEST: ENTER now opens a details popup with" },
    { CL_ITEM,    "  what to check for that item, instead of marking it" },
    { CL_ITEM,    "  tested; SUPR/DELETE still removes an item you've" },
    { CL_ITEM,    "  verified (no more checkbox / cross-out)" },
    { CL_ITEM,    "Arcade power-ups overhauled: NITRO gets a glowing speed" },
    { CL_ITEM,    "  trail + higher top speed; GHOST cars can't trigger a" },
    { CL_ITEM,    "  cop chase AND now shakes off one already in progress" },
    { CL_ITEM,    "WRECK renamed INDESTRUCTIBLE, now common (was rare)," },
    { CL_ITEM,    "  only appears when car damage is on, and no longer" },
    { CL_ITEM,    "  takes damage/speed loss from traffic or other racers" },
    { CL_ITEM,    "  (wall crashes are unaffected, same as any other car)" },
    { CL_ITEM,    "SHIELD and ROCKET power-ups removed" },
    { CL_ITEM,    "FREEZE reworked: ramming a car now slows IT to 1/3 speed," },
    { CL_ITEM,    "  glowing as it eases back to normal over ~3 seconds" },
    { CL_ITEM,    "MAGNET now only appears in Traffic Battle mode" },
    { CL_ITEM,    "REPAIR now actually fixes car damage (was oil/freeze only)," },
    { CL_ITEM,    "  and only appears when car damage is on" },
    { CL_ITEM,    "POWER-UPS option is now OFF / CASUAL / CHAOS - CHAOS packs" },
    { CL_ITEM,    "  one box into every lane at each spawn point" },
    { CL_ITEM,    "CHOOSE YOUR TEAM: new TEAM ROSTER box (top right) lists" },
    { CL_ITEM,    "  every team's members by name, updating live as picks" },
    { CL_ITEM,    "  and host AI-team assignments change" },
    { CL_ITEM,    "FIX: mode select buttons no longer overlap the HOST" },
    { CL_ITEM,    "  banner text at the top of the screen" },
    { CL_ITEM,    "Removed multiplayer TIME TRIAL from the mode select" },
    { CL_ITEM,    "  screen (ghost pass-through, checkpoint start/finish)" },
    { CL_ITEM,    "FIX: on the multiplayer split-screen profile" },
    { CL_ITEM,    "  screen, the NAME and COLOUR buttons now centre" },
    { CL_ITEM,    "  their labels like the other buttons in the stack" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 3" },
    { CL_ITEM,    "NEW dev screen: UI GUIDE (button on this screen) -" },
    { CL_ITEM,    "  one-page gallery of every menu widget: buttons," },
    { CL_ITEM,    "  selector arrows, MP host badge, confirm prompt" },
    { CL_ITEM,    "Removed two dead menu screens (language select and" },
    { CL_ITEM,    "  its legal splash) that nothing could ever reach -" },
    { CL_ITEM,    "  boot legal text and languages are unaffected" },
    { CL_ITEM,    "Test harness: drive the game from a text file of" },
    { CL_ITEM,    "  timed inputs - gas, brake, handbrake, horn, gears," },
    { CL_ITEM,    "  camera, menus, any key ([Trace] InputScript=file)" },
    { CL_ITEM,    "Jumping to a menu screen (StartScreen) now navigates" },
    { CL_ITEM,    "  there for real, so it looks and behaves exactly" },
    { CL_ITEM,    "  as if you clicked your way through the menus" },
    { CL_ITEM,    "Street-lamp light pools: EXPERIMENTAL, off by default" },
    { CL_ITEM,    "  pending a look-dev pass ([Lighting] StreetLights=1" },
    { CL_ITEM,    "  to try: nearest lamps cast warm pools when dark)" },
    { CL_ITEM,    "FIX: shadows no longer appear as several offset" },
    { CL_ITEM,    "  duplicate copies (ray-march dithering)" },
    { CL_ITEM,    "NEW lighting engine (phase 3): REFLECTIONS. Car" },
    { CL_ITEM,    "  paint and glass mirror the world, and in the rain" },
    { CL_ITEM,    "  the road turns wet and reflective, all ray-traced" },
    { CL_ITEM,    "  against the scene ([Lighting] Reflections=0 = off," },
    { CL_ITEM,    "  WetRoads=0 keeps roads dry)" },
    { CL_ITEM,    "Roads and buildings now have surface data too, so" },
    { CL_ITEM,    "  shadows and headlights shade them correctly" },
    { CL_ITEM,    "NEW lighting engine (phase 2): real-time SHADOWS." },
    { CL_ITEM,    "  Cars, walls and buildings now cast shadows onto" },
    { CL_ITEM,    "  the road and each other, ray-traced against the" },
    { CL_ITEM,    "  scene each frame ([Lighting] SunShadows=0 = off," },
    { CL_ITEM,    "  ShadowStrength=45 tunes how dark they are)" },
    { CL_ITEM,    "Headlight beams are now blocked by geometry - a car" },
    { CL_ITEM,    "  in front of you casts a shadow in your headlights" },
    { CL_ITEM,    "  instead of the beam passing through it" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 2" },
    { CL_ITEM,    "NEW lighting engine (phase 1): tracks now show the" },
    { CL_ITEM,    "  colour lighting their artists authored in 1998" },
    { CL_ITEM,    "  (sunsets, tunnels, dusk zones were always grey)" },
    { CL_ITEM,    "Headlights now respect surface angle and no longer" },
    { CL_ITEM,    "  shine through walls ([Lighting] Mode=0 = old look)" },
    { CL_ITEM,    "NEW Game Options: PLAYER NAME - your name shows in" },
    { CL_ITEM,    "  race results and standings, and is prefilled in" },
    { CL_ITEM,    "  the high-score name entry (still editable there)" },
    { CL_ITEM,    "Damage bar now sits at the top centre of the screen," },
    { CL_ITEM,    "  styled like the pause-menu bars (blue to red fill);" },
    { CL_ITEM,    "  the checkpoint timer and other top-centre HUD items" },
    { CL_ITEM,    "  slide down below it so nothing overlaps" },
    { CL_ITEM,    "FIX: brakes no longer cut out in the last stretch" },
    { CL_ITEM,    "  of a police pull-over, which was costing you time" },
    { CL_ITEM,    "Pause menu: END RACE NOW only shows in local" },
    { CL_ITEM,    "  split-screen multiplayer (not single-player or" },
    { CL_ITEM,    "  network-only races)" },
    { CL_ITEM,    "Pause menu: RESTART RACE / QUIT TO MENU / EXIT GAME /" },
    { CL_ITEM,    "  BACK TO LOBBY now ask to confirm in local split-screen" },
    { CL_ITEM,    "  MP, so one pad can't silently end the race for everyone" },
    { CL_ITEM,    "Fixed: using END RACE NOW left the camera stuck" },
    { CL_ITEM,    "  off-center at the start of the next race. Camera" },
    { CL_ITEM,    "  now always resets normally for a new race." },
    { CL_ITEM,    "FIX: game sounds no longer vanish after playing" },
    { CL_ITEM,    "  several races in one session (audio buffer pool" },
    { CL_ITEM,    "  now recycles freed slots instead of filling up)" },
    { CL_ITEM,    "Car track position no longer warps sideways on rare" },
    { CL_ITEM,    "  degenerate road quads (now matches the original)" },
    { CL_BLANK,   "" },

    { CL_DATE,    "July 1" },
    { CL_ITEM,    "NEW Drag Race multiplayer split-screen game mode" },
    { CL_ITEM,    "  (SELECT GAME MODE -> DRAG RACE): no track picker," },
    { CL_ITEM,    "  no AI opponents - just the human players" },
    { CL_ITEM,    "Drag mode options: TRAFFIC (oncoming, no lane-weaving)," },
    { CL_ITEM,    "  DISTANCE (SHORT/MEDIUM/LONG/EPIC), EXTRA LANES" },
    { CL_ITEM,    "LONG and EPIC now truly extend the strip - the road" },
    { CL_ITEM,    "  and stadium continue and the finish moves down it" },
    { CL_ITEM,    "Drag cars centre in the widened road; empty extra" },
    { CL_ITEM,    "  lanes give room to move (no filler CPU cars)" },
    { CL_ITEM,    "New: dynamic headlights. Cars cast real headlight" },
    { CL_ITEM,    "  beams that flood the road ahead per-pixel, lighting" },
    { CL_ITEM,    "  whatever they fall on. They switch ON automatically" },
    { CL_ITEM,    "  in poorly-lit conditions (rain / storm / overcast /" },
    { CL_ITEM,    "  dusk) and stay off in bright daylight. Tune via" },
    { CL_ITEM,    "  [Lighting] (Enabled, Auto, Headlights, DarkMode)." },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 30" },
    { CL_ITEM,    "Fixed: in split-screen Cup, a player could end up" },
    { CL_ITEM,    "  unable to accelerate on a later race (but still" },
    { CL_ITEM,    "  able to change camera). Their car now always" },
    { CL_ITEM,    "  responds to the throttle at every race start." },
    { CL_ITEM,    "New: END RACE NOW in the pause menu. If a player is" },
    { CL_ITEM,    "  stuck and can't reach the finish, pause and choose" },
    { CL_ITEM,    "  END RACE NOW to end the race for everyone. A YES/NO" },
    { CL_ITEM,    "  prompt confirms first; any player can trigger it." },
    { CL_ITEM,    "  Final places are ranked by how far along the track" },
    { CL_ITEM,    "  each car has got (no DNFs)." },
    { CL_ITEM,    "Fixed split-screen: a controller that the system saw" },
    { CL_ITEM,    "  as more than one gamepad could join as several" },
    { CL_ITEM,    "  players and then flip those players' camera views" },
    { CL_ITEM,    "  from its one change-camera button. One physical pad" },
    { CL_ITEM,    "  now joins as exactly one player." },
    { CL_ITEM,    "New: your car now starts in your PROFILE colour." },
    { CL_ITEM,    "  Paintable cars default to your player colour -" },
    { CL_ITEM,    "  exact for newer cars, nearest match for the" },
    { CL_ITEM,    "  classic 4-paint cars. Cycle PAINT to override." },
    { CL_ITEM,    "Profiles: type a new player name but forget to" },
    { CL_ITEM,    "  SAVE it? It's now saved automatically when the" },
    { CL_ITEM,    "  race starts, so the new name isn't lost." },
    { CL_ITEM,    "High-score boards now show celebrity names instead of" },
    { CL_ITEM,    "  generic placeholders on tracks you haven't raced yet." },
    { CL_ITEM,    "  Enable CelebrityNamesAPI=1 in td5re.ini to fetch fresh" },
    { CL_ITEM,    "  names from the internet each launch." },
    { CL_ITEM,    "NEW: in-game INTERNET RADIO! Music now streams a" },
    { CL_ITEM,    "  live station while you race. Set your own station" },
    { CL_ITEM,    "  in td5re.ini ([Audio] RadioURL); RadioEnabled=0" },
    { CL_ITEM,    "  turns it off. Needs an internet connection." },
    { CL_ITEM,    "  Plays quietly and only while racing -- it mutes" },
    { CL_ITEM,    "  when minimized, paused, or in the menus." },
    { CL_ITEM,    "  Adjust radio volume on the pause menu (RADIO row)." },
    { CL_ITEM,    "Music now runs through a swappable backend, so other" },
    { CL_ITEM,    "  song sources can be plugged in later." },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 29" },
    { CL_ITEM,    "Fixed Alt+Enter fullscreen dropping to 60Hz on a" },
    { CL_ITEM,    "  high-refresh display - it now uses the screen's" },
    { CL_ITEM,    "  native refresh rate (e.g. 120Hz or 144Hz)." },
    { CL_ITEM,    "Car paint: paintable cars now take a SECOND colour" },
    { CL_ITEM,    "  and a PATTERN (Solid / Two-Tone / Stripes / Split)." },
    { CL_ITEM,    "  Open PAINT in Select Car: the panel now has a" },
    { CL_ITEM,    "  PATTERN row and a COLOR row (MAIN / 2ND) above the" },
    { CL_ITEM,    "  swatches, and the quick-pick palette grew to 32." },
    { CL_ITEM,    "Lane Assist now picks a side at a fork: it steers" },
    { CL_ITEM,    "  toward one branch a few spans early instead of" },
    { CL_ITEM,    "  aiming at the barrier between the two roads." },
    { CL_ITEM,    "Fixed RESET CAR in split-screen: it no longer sends" },
    { CL_ITEM,    "  you back to the start or drops you into a wall. The" },
    { CL_ITEM,    "  car now resets where it stands, and a reset fully" },
    { CL_ITEM,    "  repairs it (health + dents) so it can't be wrecked." },
    { CL_ITEM,    "Controller tutorial now shows at the START of EVERY" },
    { CL_ITEM,    "  race (it used to appear only once, ever). Turn it" },
    { CL_ITEM,    "  off with the new TUTORIAL row in Game Options." },
    { CL_ITEM,    "Game Options now has TWO pages (< PREV / NEXT >) so" },
    { CL_ITEM,    "  all the rows fit comfortably." },
    { CL_ITEM,    "Traffic now stays visible much further down the road" },
    { CL_ITEM,    "  instead of popping out of view at short range. Cars" },
    { CL_ITEM,    "  (and rivals) are drawn ~60% further on open tracks." },
    { CL_ITEM,    "Fixed: the on-screen DAMAGE BAR now shows for every" },
    { CL_ITEM,    "  player in split-screen (it was invisible before)." },
    { CL_ITEM,    "New: DAMAGE BAR on/off in Game Options. Turn it OFF" },
    { CL_ITEM,    "  to hide the top-of-screen damage bar and stop your" },
    { CL_ITEM,    "  car being wrecked out of the race when it fills." },
    { CL_ITEM,    "  Dents and collisions still work. In split-screen" },
    { CL_ITEM,    "  it applies to every player at once." },
    { CL_ITEM,    "Police overhaul: chasing cops now ACCELERATE hard" },
    { CL_ITEM,    "  enough to out-drag a faster car on a straight (not" },
    { CL_ITEM,    "  just match top speed), are much tougher so a wall" },
    { CL_ITEM,    "  scrape no longer ends the chase, and ease off for" },
    { CL_ITEM,    "  corners instead of flooring into the outside wall." },
    { CL_ITEM,    "Police are harder to shake: they chase much further" },
    { CL_ITEM,    "  before giving up and accelerate harder to catch" },
    { CL_ITEM,    "  you. Speed past a group of cops and they ALL give" },
    { CL_ITEM,    "  chase now, not just the first one." },
    { CL_ITEM,    "Fixed traffic vanishing right in front of you when" },
    { CL_ITEM,    "  a car briefly snags on a bend." },
    { CL_ITEM,    "NEW dynamic Drag Race: the strip now WIDENS with the" },
    { CL_ITEM,    "  number of cars - every racer gets its own lane and" },
    { CL_ITEM,    "  lines up across the start (one lane per player)" },
    { CL_ITEM,    "Drag steering changes LANES instead of turning the car" },
    { CL_ITEM,    "  (Need-for-Speed-Underground style): tap left/right" },
    { CL_ITEM,    "Drag races can be made longer (finish pushed down the" },
    { CL_ITEM,    "  strip's existing road) via TD5RE_DRAG_LENGTH" },
    { CL_ITEM,    "New: optional LANE ASSIST steering aid. It eases you" },
    { CL_ITEM,    "  toward the centre of the drivable road, pulling" },
    { CL_ITEM,    "  gently near the middle and firmer the further off" },
    { CL_ITEM,    "  you drift; it never steers you onto grass, fades" },
    { CL_ITEM,    "  out the moment you steer, and stays smooth across" },
    { CL_ITEM,    "  forks and merges. Off by default." },
    { CL_ITEM,    "  Turn it on in Game Options (single player), per" },
    { CL_ITEM,    "  player on the multiplayer Profile screen (next to" },
    { CL_ITEM,    "  Automatic/Manual), or with the L key mid-race." },
    { CL_ITEM,    "NEW MODE - Traffic Battle (multiplayer split-screen +" },
    { CL_ITEM,    "  solo vs traffic): ONCOMING traffic pours at you and you" },
    { CL_ITEM,    "  score by WRECKING cars. No rivals, no cops - the winner" },
    { CL_ITEM,    "  is whoever destroyed the most. Pick it below CUP." },
    { CL_ITEM,    "  Win by MOST WRECKS or CHECKPOINTS (a deadline creeps" },
    { CL_ITEM,    "  up the track - crash AND keep moving). Crashes wreck" },
    { CL_ITEM,    "  at ANY angle; wrecks fly + go see-through to drive thru" },
    { CL_ITEM,    "Arcade: FIVE new power-ups - SHIELD, EMP (freeze), MAGNET" },
    { CL_ITEM,    "  (drag traffic in), ROCKET (dash+plow), REPAIR" },
    { CL_ITEM,    "Car damage is now ON for all races, with two new" },
    { CL_ITEM,    "  Game Options rows: CAR TOUGHNESS and DEFORMATION" },
    { CL_ITEM,    "  (Low / Normal / High), saved across sessions" },
    { CL_ITEM,    "Damaged panels now scuff/darken where they're hit," },
    { CL_ITEM,    "  not just crumple; cars are tougher overall" },
    { CL_ITEM,    "Finishing (or wrecking) orbits the camera around" },
    { CL_ITEM,    "  your car so you can see the damage" },
    { CL_ITEM,    "Fixed a chase-camera jitter at race start: on high" },
    { CL_ITEM,    "  refresh-rate monitors the view could shake/vibrate" },
    { CL_ITEM,    "  for a long time. The camera now locks onto the car" },
    { CL_ITEM,    "  vertically the same way it already did sideways, so" },
    { CL_ITEM,    "  the car stays rock-steady in frame at any FPS" },
    { CL_ITEM,    "Split-screen car select redesigned for 5+ players: a" },
    { CL_ITEM,    "  big car preview on top, then the buttons and the" },
    { CL_ITEM,    "  SPEED / ACCEL / HANDLING bars side by side so both" },
    { CL_ITEM,    "  stay readable. Buttons shrink with the pane (7-9" },
    { CL_ITEM,    "  players) to keep the car big. Labels tidied" },
    { CL_ITEM,    "  (AUTO, no MORE STATS button in this mode)" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 28" },
    { CL_ITEM,    "New: GTA-style car damage. Cars dent where" },
    { CL_ITEM,    "  they're hit (cars AND walls), smoke as damage" },
    { CL_ITEM,    "  builds, handle worse, and can be wrecked out" },
    { CL_ITEM,    "  of the race. A health bar shows your condition" },
    { CL_ITEM,    "Multiplayer car select: the host can now press X / TAB" },
    { CL_ITEM,    "  to open a host-only menu that sets EVERYONE's car -" },
    { CL_ITEM,    "  give all your car, or roll all a random slow / average" },
    { CL_ITEM,    "  / fast car - a low/mid/high speed class by accel + top" },
    { CL_ITEM,    "  speed (never the very slowest/fastest; each player a" },
    { CL_ITEM,    "  different car)" },
    { CL_ITEM,    "Multiplayer cup fix: player 1 no longer reverts to the" },
    { CL_ITEM,    "  car used in a race BEFORE the cup on the 2nd race -" },
    { CL_ITEM,    "  every cup race now keeps your chosen car" },
    { CL_ITEM,    "Arcade power-ups tuned:" },
    { CL_ITEM,    "  the timer bar up top now counts the WHOLE duration" },
    { CL_ITEM,    "  (was stuck full, only shrinking the last second)" },
    { CL_ITEM,    "  the HAZARD (oil-slick) power-up has been removed" },
    { CL_ITEM,    "  item boxes sit one lane closer to the centre" },
    { CL_ITEM,    "  every power-up effect now lasts 20% longer" },
    { CL_ITEM,    "Power-ups are now ARCADE-only: picking SIMULATION no" },
    { CL_ITEM,    "  longer leaves item-box power-ups on the track" },
    { CL_ITEM,    "Splitscreen: a gold HOST tag marks the host on every" },
    { CL_ITEM,    "  multiplayer selector - profile, screen, game mode" },
    { CL_ITEM,    "  and car select - so you always see who's host" },
    { CL_ITEM,    "New: a controller tutorial appears on your FIRST race" },
    { CL_ITEM,    "  (when using a gamepad) - a dimmed Xbox pad diagram" },
    { CL_ITEM,    "  with an arrow from each button to what it does, read" },
    { CL_ITEM,    "  from your bindings. All players press a button to" },
    { CL_ITEM,    "  start; it won't show again (TutorialOverlay option)" },
    { CL_ITEM,    "Cop Chase: suspects can now pick TD6 cars too, not" },
    { CL_ITEM,    "  just the TD5 line-up (cops still drive police cars)" },
    { CL_ITEM,    "You can now race the 7 lap circuits in REVERSE" },
    { CL_ITEM,    "  (Newcastle, Maui, Cheddar, Jarash, Courmayeur," },
    { CL_ITEM,    "  Montego Bay, House of Bez): the Direction toggle" },
    { CL_ITEM,    "  appears for them and the grid lines up on the" },
    { CL_ITEM,    "  start/finish straight" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 27" },
    { CL_ITEM,    "Controller: the Y button now changes the camera view" },
    { CL_ITEM,    "  (was an awkward stick-click); the horn moves to the" },
    { CL_ITEM,    "  left-stick click. SELECT still resets your car" },
    { CL_ITEM,    "Time-trial fix: on the city tracks (Hong Kong," },
    { CL_ITEM,    "  London, Paris...) a time trial that starts from a" },
    { CL_ITEM,    "  checkpoint partway along the track no longer ends" },
    { CL_ITEM,    "  the instant it begins" },
    { CL_ITEM,    "Watching a replay no longer counts as a new race:" },
    { CL_ITEM,    "  the results / cup standings keep the REAL race" },
    { CL_ITEM,    "  outcome instead of the replay's partial result" },
    { CL_ITEM,    "Cop Chase HUD overhaul (multiplayer):" },
    { CL_ITEM,    "  the bust ARROW now only pops up over a suspect when" },
    { CL_ITEM,    "  you crash into it, not over every car at once" },
    { CL_ITEM,    "  other players' name labels are hidden in this mode" },
    { CL_ITEM,    "  no more 1st/2nd position - the top now shows an" },
    { CL_ITEM,    "  ARRESTS scoreboard listing every cop's tally" },
    { CL_ITEM,    "  cops must have SIRENS ON to arrest a suspect; ram" },
    { CL_ITEM,    "  one with the siren off and you're told to turn it on" },
    { CL_ITEM,    "  (press HORN to toggle your siren, per cop)" },
    { CL_ITEM,    "Multiplayer game-mode vote redesigned: each player now" },
    { CL_ITEM,    "  presses A to vote and a border in their own profile" },
    { CL_ITEM,    "  colour wraps the chosen mode (more voters = more" },
    { CL_ITEM,    "  rings); the arrow goes once they vote, and the host" },
    { CL_ITEM,    "  still makes the final pick" },
    { CL_ITEM,    "Fixed Time Trials misbehaving after a cup: the race" },
    { CL_ITEM,    "  no longer ends right after the countdown, keeps the" },
    { CL_ITEM,    "  car you picked when you Race Again, and no longer" },
    { CL_ITEM,    "  drops rival cars onto your start lane" },
    { CL_ITEM,    "Snowy tracks (e.g. Bern) are now easier to drive:" },
    { CL_ITEM,    "  the icy surface gives more grip so the car slides" },
    { CL_ITEM,    "  far less - dry tracks are completely unchanged" },
    { CL_ITEM,    "Multiplayer CUP podium colours each racer correctly:" },
    { CL_ITEM,    "  humans in their chosen profile colour, CPU in grey" },
    { CL_ITEM,    "Police now keep chasing all race long: crashing while" },
    { CL_ITEM,    "  being chased no longer makes the cops ignore you for" },
    { CL_ITEM,    "  the rest of the race (was: one chase, then never)" },
    { CL_ITEM,    "Split-screen fix: the reset-car and change-camera" },
    { CL_ITEM,    "  buttons now affect YOUR car, not the other" },
    { CL_ITEM,    "  player's, when you've picked your own screen" },
    { CL_ITEM,    "Deleting a saved player profile now asks you to" },
    { CL_ITEM,    "  confirm first, and names the exact profile it will" },
    { CL_ITEM,    "  remove - only that one selected profile is deleted" },
    { CL_ITEM,    "Multiplayer setup no longer shows the ARCADE/SIM" },
    { CL_ITEM,    "  physics selector twice: it was removed from the" },
    { CL_ITEM,    "  mode-options screen and now lives only on track" },
    { CL_ITEM,    "  selection (where you already set it)" },
    { CL_ITEM,    "ARCADE now scatters about twice as many item boxes" },
    { CL_ITEM,    "  along the track so power-ups come round more often" },
    { CL_ITEM,    "Power-up effects last twice as long (GHOST, WRECK," },
    { CL_ITEM,    "  and the oil-slick spin-out)" },
    { CL_ITEM,    "NITRO is now a sustained 2.5x ACCELERATION boost for" },
    { CL_ITEM,    "  several seconds (was a single instant speed kick)" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 26" },
    { CL_ITEM,    "Car collisions now follow the actual car shape:" },
    { CL_ITEM,    "  crashes register when the models really touch," },
    { CL_ITEM,    "  no more colliding through an empty gap" },
    { CL_ITEM,    "AI cars no longer grind into each other (or you)" },
    { CL_ITEM,    "  forever: when an AI gets wedged it now steers" },
    { CL_ITEM,    "  away to free itself instead of pushing endlessly" },
    { CL_ITEM,    "ARCADE power-ups are now Mario-Kart item BOXES that" },
    { CL_ITEM,    "  hang over the road - drive through one to grab it" },
    { CL_ITEM,    "Each box is a glowing, spinning, pulsing cube with a" },
    { CL_ITEM,    "  distinctive icon (NITRO/GHOST/WRECK/HAZARD)" },
    { CL_ITEM,    "A grabbed box vanishes, respawning after 5 seconds" },
    { CL_ITEM,    "Each box holds a RANDOM power-up; you can only hold" },
    { CL_ITEM,    "  one at a time (grab another once it wears off)" },
    { CL_ITEM,    "More human players = more boxes; 5+ players can spawn" },
    { CL_ITEM,    "  a pair (one on each shoulder) at a spot" },
    { CL_ITEM,    "HAZARD drops a wide dark OIL SLICK with danger marks;" },
    { CL_ITEM,    "  any car that hits it drifts out of control briefly" },
    { CL_ITEM,    "Game Options has a POWER-UPS on/off toggle" },
    { CL_ITEM,    "Your CAR ITSELF glows in the power-up's colour while" },
    { CL_ITEM,    "  active; the effect name shows centred below the" },
    { CL_ITEM,    "  checkpoint timer" },
    { CL_ITEM,    "GHOST turns your car translucent and lets you pass" },
    { CL_ITEM,    "  through traffic as well as rival cars" },
    { CL_ITEM,    "Item boxes now sit on the road edges - steer over" },
    { CL_ITEM,    "  to one to grab it" },
    { CL_ITEM,    "Quick Race setup now has a PHYSICS option" },
    { CL_ITEM,    "  (ARCADE / SIMULATION) right on the screen" },
    { CL_ITEM,    "Minimap fix: driving onto a fork no longer blanks" },
    { CL_ITEM,    "  the road - both tracks of a branch show again" },
    { CL_ITEM,    "MORE STATS: POWER now explained (engine output) and" },
    { CL_ITEM,    "  WEIGHT moved down to sit under GRIP" },
    { CL_ITEM,    "MORE STATS BALANCE is now a visual front/rear weight" },
    { CL_ITEM,    "  bar (amber front, blue rear, centre = 50/50)" },
    { CL_ITEM,    "Quick stat bars (under PAINT) now use the same scale" },
    { CL_ITEM,    "  as MORE STATS so SPEED/ACCEL/HANDLING line up" },
    { CL_ITEM,    "MORE STATS: press LEFT / RIGHT to switch cars without" },
    { CL_ITEM,    "  leaving the stats screen, so you can compare them" },
    { CL_ITEM,    "MORE STATS now has plain-language captions under the" },
    { CL_ITEM,    "  less obvious bars (e.g. ACCEL = power-to-weight)" },
    { CL_ITEM,    "MORE STATS text nudged right so it no longer overlaps" },
    { CL_ITEM,    "  the RANDOMIZE button" },
    { CL_ITEM,    "Menu navigation reworked: every menu now moves the" },
    { CL_ITEM,    "  cursor by what you SEE (top-to-bottom, left-to-" },
    { CL_ITEM,    "  right), so no option gets skipped - and LEFT/RIGHT" },
    { CL_ITEM,    "  now steps between side-by-side buttons (OK/BACK)" },
    { CL_ITEM,    "  on a GAMEPAD too, not just keyboard" },
    { CL_ITEM,    "Track Select tidied up: the DYNAMICS option now has" },
    { CL_ITEM,    "  its left/right arrows and sits right above OK/BACK," },
    { CL_ITEM,    "  with the other rows spaced closer so it all fits" },
    { CL_ITEM,    "ARCADE crashes no longer fling cars off the map:" },
    { CL_ITEM,    "  airborne launch dialled way down so it's fun" },
    { CL_ITEM,    "  instead of unplayable" },
    { CL_ITEM,    "MORE STATS rebuilt: the car-select stats are now" },
    { CL_ITEM,    "  the car's REAL physics - weight, power, grip," },
    { CL_ITEM,    "  braking, handling, downforce, drivetrain - instead" },
    { CL_ITEM,    "  of cosmetic spec text, in 1P and split-screen" },
    { CL_ITEM,    "Car weight now matters: heavy cars hit harder and" },
    { CL_ITEM,    "  shove lighter cars aside, but climb hills slower;" },
    { CL_ITEM,    "  light cars get flung in crashes but climb easily" },
    { CL_ITEM,    "Power-to-weight: lighter cars accelerate quicker" },
    { CL_ITEM,    "Slipstream: tuck in behind a car for a speed boost" },
    { CL_ITEM,    "Downforce: grippy cars stay planted in fast bends" },
    { CL_ITEM,    "NEW ARCADE mode is a wilder playstyle: collisions" },
    { CL_ITEM,    "  hit harder and shove cars around more than SIM," },
    { CL_ITEM,    "  but stay controllable (no flying off the map)" },
    { CL_ITEM,    "Drive over glowing road PADS to grab power-ups:" },
    { CL_ITEM,    "  NITRO (speed burst), GHOST (phase through cars)," },
    { CL_ITEM,    "  WRECKING BALL (you're immune, others fly), and" },
    { CL_ITEM,    "  HAZARD (drop an oil slick to spin out chasers)" },
    { CL_ITEM,    "Your active power-up shows as a chip in your pane" },
    { CL_ITEM,    "SIMULATION mode reworked: arcade grip/power but" },
    { CL_ITEM,    "  realistic (lighter) gravity; AI cars match" },
    { CL_ITEM,    "ARCADE / SIMULATION is now chosen on the track and" },
    { CL_ITEM,    "  multiplayer screens (it left Game Options)" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 25" },
    { CL_ITEM,    "New Cop Chase option RANDOM COP: turn it on and the" },
    { CL_ITEM,    "  cop is picked at random when the race starts - you" },
    { CL_ITEM,    "  pick any car normally and find out if you're the" },
    { CL_ITEM,    "  cop only once you're on the track" },
    { CL_ITEM,    "PENDING TO TEST menu: press SUPR / DELETE to remove" },
    { CL_ITEM,    "  the highlighted item (vs ENTER, which marks tested)" },
    { CL_ITEM,    "Idle the main menu for a minute and a random demo" },
    { CL_ITEM,    "  race now plays itself: random track, car," },
    { CL_ITEM,    "  opponents and traffic, and never any police" },
    { CL_ITEM,    "The demo returns to the main menu when it ends," },
    { CL_ITEM,    "  with no results screen" },
    { CL_ITEM,    "Cop Chase has a new INFECT option: an arrested car" },
    { CL_ITEM,    "  turns into a cop (a random police car) instead of" },
    { CL_ITEM,    "  stopping, so players who get caught keep playing" },
    { CL_ITEM,    "  as cops; the round ends when everyone's infected" },
    { CL_ITEM,    "Cars and traffic now crash exactly when their" },
    { CL_ITEM,    "  models actually touch: the collision box is" },
    { CL_ITEM,    "  measured from each car's own 3D shape instead of" },
    { CL_ITEM,    "  a fixed size, so no more crashing across a gap or" },
    { CL_ITEM,    "  sliding through one another" },
    { CL_ITEM,    "Split-screen Cop Chase has its own results screen:" },
    { CL_ITEM,    "  COPS listed with their arrest counts, SUSPECTS" },
    { CL_ITEM,    "  below with the time they were busted (- if they" },
    { CL_ITEM,    "  got away); the race ends as soon as every suspect" },
    { CL_ITEM,    "  is caught or all the survivors reach the finish" },
    { CL_ITEM,    "Italy (Courmayeur) no longer crashes when you start" },
    { CL_ITEM,    "  the race" },
    { CL_ITEM,    "Cop Chase: you can no longer start a race with no" },
    { CL_ITEM,    "  cops or no suspects (pick at least one of each)" },
    { CL_ITEM,    "Arrested cars now stop dead and can't be driven" },
    { CL_ITEM,    "A big red ARRESTED appears in the middle of the" },
    { CL_ITEM,    "  busted car's screen; its floating bar disappears" },
    { CL_ITEM,    "Arrested cars vanish from the split-screen map" },
    { CL_ITEM,    "Both cop and suspect feel a strong rumble on arrest" },
    { CL_ITEM,    "Every suspect shows its own bust-progress bar that" },
    { CL_ITEM,    "  shrinks with distance and shows twice as far" },
    { CL_ITEM,    "CHOOSE YOUR TEAM and COP CHASE - ROLES now show" },
    { CL_ITEM,    "  each player's profile name instead of PLAYER 1/2" },
    { CL_ITEM,    "Cup team mode: the host can scroll to the AI" },
    { CL_ITEM,    "  opponents and set each one's team and skill" },
    { CL_ITEM,    "  (per-opponent slider) — they really drive at it" },
    { CL_ITEM,    "Dev: host can also assign teams to ADD AI PLAYER bots" },
    { CL_ITEM,    "Cup final standings now show each player's profile" },
    { CL_ITEM,    "  name instead of PLAYER 1 / PLAYER 2" },
    { CL_ITEM,    "WHAT NEXT? menu: CAR SELECTION goes straight to the" },
    { CL_ITEM,    "  car grid (was sending you back to profile select)" },
    { CL_ITEM,    "WHAT NEXT? buttons now line up under the title like" },
    { CL_ITEM,    "  every other menu screen" },
    { CL_ITEM,    "Game is now crisp on high-DPI / scaled displays:" },
    { CL_ITEM,    "  no more blur on 4K screens at 150%/300% scaling" },
    { CL_ITEM,    "Fixed menu UP/LEFT going dead with several controllers" },
    { CL_ITEM,    "  connected (often after a race or entering a game" },
    { CL_ITEM,    "  mode): a stuck/off-centre stick no longer jams those" },
    { CL_ITEM,    "  directions for everyone" },
    { CL_ITEM,    "Fixed controller rumble dying after a few races: force" },
    { CL_ITEM,    "  feedback now keeps working on every pad race after race" },
    { CL_ITEM,    "Multiplayer results table tidied: name column lines" },
    { CL_ITEM,    "  up under the title, columns closer, cleaner divider" },
    { CL_ITEM,    "Cup races now show a CUP RESULTS screen with a POINTS" },
    { CL_ITEM,    "  column (points this race + running cup total)" },
    { CL_ITEM,    "Empty split-screen cells never repeat: with 7" },
    { CL_ITEM,    "  players one shows the MAP, the other the STANDINGS" },
    { CL_ITEM,    "Split-screen map now zooms and turns smoothly" },
    { CL_ITEM,    "  instead of flickering and snapping around" },
    { CL_ITEM,    "Split-screen overview map no longer draws a stray" },
    { CL_ITEM,    "  diagonal line across point-to-point tracks (Sydney)" },
    { CL_ITEM,    "CUP - WHAT NEXT? menu tidied: title moved to the top" },
    { CL_ITEM,    "  and the buttons realigned under it, a bit narrower" },
    { CL_ITEM,    "Fixed 7th+ split-screen car driving rolled onto its" },
    { CL_ITEM,    "  side / wobbling — big fields now sit flat on the road" },
    { CL_ITEM,    "Multiplayer cups: choose the track, traffic and" },
    { CL_ITEM,    "  police for every race, one at a time; set how" },
    { CL_ITEM,    "  many AI opponents race for points; and the race" },
    { CL_ITEM,    "  now ends the moment all humans finish" },
    { CL_ITEM,    "Dev: ADD AI PLAYER in the multiplayer lobby fills" },
    { CL_ITEM,    "  seats with auto-driving bots (random name/colour/" },
    { CL_ITEM,    "  car) so you can test split-screen MP on your own" },
    { CL_ITEM,    "CHANGELOG screen: bulleted items, more spacing, and" },
    { CL_ITEM,    "  the PENDING TO TEST button moved up by the title" },
    { CL_ITEM,    "New split-screen post-race menu (race again / view" },
    { CL_ITEM,    "  replay / back to lobby / car / mode / main menu)" },
    { CL_ITEM,    "Police chase: cops 2.5x tougher than traffic, never" },
    { CL_ITEM,    "  launch airborne on impact, and dodge traffic" },
    { CL_ITEM,    "Car-select 3rd stat bar now shows HANDLING (real" },
    { CL_ITEM,    "  car inertia) instead of an empty GRIP bar" },
    { CL_ITEM,    "Force feedback: new rumble backend lifts the 4-pad" },
    { CL_ITEM,    "  cap, so a 5th+ controller can rumble" },
    { CL_ITEM,    "Split-screen confirms before backing out on every" },
    { CL_ITEM,    "  setup screen (no more accidental drop-back)" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 24" },
    { CL_ITEM,    "Aston Martin Vantage stat bars no longer draw blank" },
    { CL_ITEM,    "Reinstated the car horn + Test Drive 6 driver horns" },
    { CL_ITEM,    "Shorter controller names so they fit the lobby row" },
    { CL_ITEM,    "Catch-up now paces off the opponent directly ahead" },
    { CL_ITEM,    "Traffic: lighter on impact, no despawning in front" },
    { CL_ITEM,    "  of you, and fills sparse stretches of road" },
    { CL_ITEM,    "Controller slots stay put across a pad disconnect" },
    { CL_ITEM,    "Opponent name plates sit below the wheels at 50%" },
    { CL_ITEM,    "Reset-car moved to SELECT; CHANGE VIEW moved to L3" },
    { CL_ITEM,    "Force feedback routed to the correct split-screen pad" },
    { CL_ITEM,    "Auto stuck-recovery removed: manual only + 5s cooldown" },
    { CL_ITEM,    "Cop Chase: multi-cop roles + cop-only car select" },
    { CL_ITEM,    "Empty split-screen map hides finished cars and zooms" },
    { CL_ITEM,    "  to the live field, with cleaner roads" },
    { CL_ITEM,    "Fixed circuit finish placing you 2nd despite winning" },
    { CL_ITEM,    "Per-viewport engine audio panning for 3+ players" },
    { CL_ITEM,    "6-player car-select: two columns, no clipped text" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 23" },
    { CL_ITEM,    "Player colours now reach the mode-vote screen" },
    { CL_ITEM,    "AI commits to track branches earlier (no missed forks)" },
    { CL_ITEM,    "TD6 city checkpoints add time; timeout hides the star" },
    { CL_ITEM,    "Traffic drives one-way with a pile-up braking floor" },
    { CL_ITEM,    "Traffic renders in 6+ opponent single-player fields" },
    { CL_ITEM,    "TD5 app icon shows on the taskbar of other PCs" },
    { CL_ITEM,    "Track Studio: web tool to import & edit custom tracks" },
    { CL_ITEM,    "  (textures, skybox, lanes, branches) + textured road" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 22" },
    { CL_ITEM,    "Custom-track converter: a centerline becomes a" },
    { CL_ITEM,    "  drivable level, with branch/junction support" },
    { CL_ITEM,    "Car Studio: browser tool to view/edit/build cars;" },
    { CL_ITEM,    "  imports glTF / OBJ / FBX / .blend models" },
    { CL_ITEM,    "Multiplayer game modes: Time Trial, Cup, Cop Chase" },
    { CL_ITEM,    "Shared frontend screen routine + consistent titles" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 21" },
    { CL_ITEM,    "Custom-car pipeline with drop-in auto-enumerated slots" },
    { CL_ITEM,    "Cop Chase polish: strobe, banner, siren, indicator" },
    { CL_ITEM,    "Tamed the violent launch / roll on steep descents" },
    { CL_ITEM,    "Gentle flip-recovery (coast, then settle upright)" },
    { CL_ITEM,    "Per-device MP profiles + pad-reconnect modal" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 19-20" },
    { CL_ITEM,    "Netplay render decoupled from the lockstep barrier" },
    { CL_ITEM,    "  so the client frame-rate is no longer host-capped" },
    { CL_ITEM,    "Multi-cop, deterministic traffic pursuit + LOST screen" },
    { CL_ITEM,    "TD6 batch: reverse banners, spacing, gear-1, circuits" },
    { CL_BLANK,   "" },

    { CL_DATE,    "June 18" },
    { CL_ITEM,    "TD6 AI drives the track's authored racing line" },
    { CL_ITEM,    "Reverse-direction checkpoints; grass bleeds speed" },
    { CL_BLANK,   "" },
    { CL_BLANK,   "" },

    { CL_SECTION, "EARLIER HIGHLIGHTS" },
    { CL_DATE,    "since the port began, March 2026" },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Clean-room C source port from a full Ghidra decompile;" },
    { CL_ITEM,    "  the DirectDraw/D3D3 layer is replaced by a D3D11" },
    { CL_ITEM,    "  backend, so the game runs with no original DLLs." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Online netplay: Winsock2 UDP lockstep (replacing" },
    { CL_ITEM,    "  DirectPlay), LAN lobby with roster + passwords," },
    { CL_ITEM,    "  and UPnP port mapping for hosting." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Split-screen up to 9 players / 16 racer slots, a" },
    { CL_ITEM,    "  press-to-join lobby, and full multi-device joystick" },
    { CL_ITEM,    "  + force-feedback support." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Test Drive 6 content ported in: extra cars and the" },
    { CL_ITEM,    "  point-to-point city tracks (London, Hong Kong)" },
    { CL_ITEM,    "  with lighting zones and breakable street props." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Custom content: Car Studio + Track Studio tools and" },
    { CL_ITEM,    "  import pipelines for your own cars and tracks." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Rendering overhaul: procedural wheels, terrain-hugging" },
    { CL_ITEM,    "  shadows, texture-free VFX, multi-threaded panes, and" },
    { CL_ITEM,    "  an FPS-independent camera with working VSync." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "AI overhaul: ray-sensing opponents and GTA-style" },
    { CL_ITEM,    "  dynamic traffic." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Physics: sub-tick render interpolation, hill-climb" },
    { CL_ITEM,    "  assist, and steep-slope launch/roll fixes." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Frontend revamp: crisp TTF vector text, reworked" },
    { CL_ITEM,    "  Options/Configure, car-select stat bars, saves." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Editable assets: JSON/PNG sources are packed on load," },
    { CL_ITEM,    "  retiring the binary .DAT files; tidy INI config." },
    { CL_BLANK,   "" },
    { CL_ITEM,    "Plus a LAN release auto-updater and publish tooling." },
    { CL_BLANK,   "" },
    { CL_BLANK,   "" },
    { CL_DATE,    "-- end of changelog --" },
    { CL_BLANK,   "" },
};

#define TD5_CHANGELOG_LINE_COUNT \
    ((int)(sizeof(k_changelog_lines) / sizeof(k_changelog_lines[0])))

#endif /* TD5_CHANGELOG_H */
