/* td5_geo_fork_verdicts.h -- MEASURED per-fork AI verdicts for geo routes (round 1017 R).
 *
 * GENERATED by verify/geo_fork_verdicts_gen.py from the harness' verify/out/fork_validate.json
 * runs (verify/geo_fork_validate.ps1); do not hand-edit between the markers. Header-only on
 * purpose: no new module, no extern, no runtime file to ship.
 *
 * A record is keyed by (place slug, route fingerprint): the fingerprint is an FNV-1a over the
 * conditioned route's node x, z and lane count, logged by the generator as
 * "[REAL FORK] route fingerprint XXXXXXXX", so a verdict only ever applies to the exact route it
 * was measured on (a different route, or a changed selector input, finds no record). The fork
 * inside the record is keyed by its main-span F and R.
 *
 *   TD5RE_GEO_FORK_VERDICTS=0     ignore this table (build what the selector picks)
 *   TD5RE_GEO_FORK_UNVERIFIED=0   a route with NO record builds no relaxed / merged fork (1 = default)
 *
 * With a record for the route: a picked fork that is listed FAIL / UNTESTED / WARN (not marked
 * keep) is dropped and the selection is made again without it (so a merged fork that fails
 * falls back to the pieces it was made of); a RELAXED or MERGED fork the record does not list
 * is dropped too; a fork built by the round-1016 rules that the record does not list is kept.
 */
#ifndef TD5_GEO_FORK_VERDICTS_H
#define TD5_GEO_FORK_VERDICTS_H

#define TD5_FV_PASS      0
#define TD5_FV_WARN_KEEP 1     /* WARN, kept for the reason in the comment next to the record */
#define TD5_FV_WARN      2
#define TD5_FV_FAIL      3
#define TD5_FV_UNTESTED  4

typedef struct { const char *place; unsigned int fp; int F, R, verdict; } TD5_ForkVerdict;

/* GENERATED-BEGIN */
static const TD5_ForkVerdict k_td5_fork_verdicts[] = {
    { "la_plata_partido", 0x4B56DECBU, 46, 209, TD5_FV_PASS },   /* masterB:PASS(6seeds) piecesB:PASS(6seeds) */
    { "la_plata_partido", 0x4B56DECBU, 46, 565, TD5_FV_PASS },   /* fullB:PASS(6seeds) */
    { "la_plata_partido", 0x4B56DECBU, 210, 327, TD5_FV_PASS },   /* masterB:PASS(6seeds) piecesB:PASS(6seeds) */
    { "la_plata_partido", 0x4B56DECBU, 328, 565, TD5_FV_PASS },   /* masterB:PASS(6seeds) piecesB:PASS(6seeds) */
    { "la_plata_partido", 0x4B56DECBU, 707, 790, TD5_FV_WARN },   /* piecesB:WARN(6seeds) fullB:PASS(6seeds) o707B:WARN(6seeds) */
    { "la_plata_partido", 0x4B56DECBU, 901, 1030, TD5_FV_PASS },   /* masterB:PASS(6seeds) piecesB:PASS(6seeds) */
    { "la_plata_partido", 0x4B56DECBU, 901, 1174, TD5_FV_WARN_KEEP },   /* fullB:WARN(6seeds) o901B:PASS(6seeds) KEEP: merged Avenida 60 + Plaza Dardo Rocha + Avenida 7: PASS alone over 6 seeds on BOTH the pre-24b01f00 and the post-24b01f00 AI (8 hits, 0 crashes, 0 sta (full text: verify/geo_fork_keep.json) */
    { "la_plata_partido", 0x4B56DECBU, 1031, 1129, TD5_FV_PASS },   /* masterB:PASS(6seeds) piecesB:PASS(6seeds) */
    { "la_plata_partido", 0x4B56DECBU, 1130, 1174, TD5_FV_PASS },   /* masterB:PASS(6seeds) piecesB:PASS(6seeds) */
};
static const int k_td5_fork_verdicts_n = 9;
/* GENERATED-END */

/* Does the table hold ANY record for this route? */
static inline int td5_fork_verdict_route_known(const char *place, unsigned int fp)
{
    int i;
    for (i = 0; i < k_td5_fork_verdicts_n; i++)
        if (k_td5_fork_verdicts[i].fp == fp && !strcmp(k_td5_fork_verdicts[i].place, place)) return 1;
    return 0;
}

/* The verdict of fork (F,R) on this route, or -1 when it is not listed. */
static inline int td5_fork_verdict_get(const char *place, unsigned int fp, int F, int R)
{
    int i;
    for (i = 0; i < k_td5_fork_verdicts_n; i++) {
        const TD5_ForkVerdict *v = &k_td5_fork_verdicts[i];
        if (v->fp == fp && v->F == F && v->R == R && !strcmp(v->place, place)) return v->verdict;
    }
    return -1;
}
#endif /* TD5_GEO_FORK_VERDICTS_H */
