/* GENERATED by re/tools/tg_prefab_audit.py --emit-close -- do not edit.
 *
 * Closing geometry for the shipped LANDMARK PREFABS that are OPEN SHELLS.
 *
 * td5_tg_prefab_data.h lifts set pieces verbatim out of the shipped L23
 * level. A piece that only ever faced the road there can be modelled with
 * no back and no roof, which is invisible in the original and very visible
 * once the auto-track stands it alone in the open -- Mariano, 2026-10-03,
 * "todavia hay edificios que no tienen lados".
 *
 * Each quad completes the BOUNDING BOX of one open component, on the planes
 * that component does not already wall, taking that component's dominant
 * texture page. The floor is never emitted. Coordinates are LOCAL, the same
 * space as td5_tg_prefab_data.h, so they rotate and translate with the piece.
 *
 *   L23.lm04: open component 7x9m h8m walls=2 roof=1 -> 2 closing quad(s) on page_local 53
 *   L23.lm04: open component 14x5m h11m walls=1 roof=1 -> 4 closing quad(s) on page_local 54
 *   L23.lm12: open component 22x18m h10m -- walls fill only 20% of it, closure NOT SOUND, prefab EXCLUDED from the pool
 *   L23.lm15: open component 13x35m h6m walls=1 roof=1 -> 4 closing quad(s) on page_local 43
 *   L23.lm15: open component 6x29m h20m walls=1 roof=0 -> 5 closing quad(s) on page_local 129
 *   L23.lm16: open component 15x15m h19m walls=2 roof=0 -> 3 closing quad(s) on page_local 133
 *   L23.lm22: open component 12x23m h22m walls=2 roof=0 -> 5 closing quad(s) on page_local 68
 */
#ifndef TD5_TG_PREFAB_CLOSE_DATA_H
#define TD5_TG_PREFAB_CLOSE_DATA_H

typedef struct {
    unsigned short page_local;
    float          v[20];      /* 4 verts x (x,y,z,u,v) */
} TG_PrefabCloseQuad;

static const TG_PrefabCloseQuad k_pfclose_quads[] = {
    { 53, { -3015.8f,4539.1f,-855.5f,0.00000f,0.00000f, -3015.8f,4539.1f,2933.6f,1.00000f,0.00000f, -3015.8f,6539.1f,2933.6f,1.00000f,1.00000f, -3015.8f,6539.1f,-855.5f,0.00000f,1.00000f } },
    { 53, { -3015.8f,4539.1f,2933.6f,0.00000f,0.00000f, -320.4f,4539.1f,2933.6f,1.00000f,0.00000f, -320.4f,6539.1f,2933.6f,1.00000f,1.00000f, -3015.8f,6539.1f,2933.6f,0.00000f,1.00000f } },
    { 54, { -8312.5f,39.1f,-1566.4f,0.00000f,0.00000f, -8312.5f,39.1f,347.7f,1.00000f,0.00000f, -8312.5f,4539.1f,347.7f,1.00000f,1.00000f, -8312.5f,4539.1f,-1566.4f,0.00000f,1.00000f } },
    { 54, { -2625.0f,39.1f,-1566.4f,0.00000f,0.00000f, -2625.0f,39.1f,347.7f,1.00000f,0.00000f, -2625.0f,4539.1f,347.7f,1.00000f,1.00000f, -2625.0f,4539.1f,-1566.4f,0.00000f,1.00000f } },
    { 54, { -8312.5f,39.1f,-1566.4f,0.00000f,0.00000f, -2625.0f,39.1f,-1566.4f,1.00000f,0.00000f, -2625.0f,4539.1f,-1566.4f,1.00000f,1.00000f, -8312.5f,4539.1f,-1566.4f,0.00000f,1.00000f } },
    { 54, { -8312.5f,39.1f,347.7f,0.00000f,0.00000f, -2625.0f,39.1f,347.7f,1.00000f,0.00000f, -2625.0f,4539.1f,347.7f,1.00000f,1.00000f, -8312.5f,4539.1f,347.7f,0.00000f,1.00000f } },
    { 43, { -480.5f,820.3f,-7441.4f,0.00000f,0.00000f, -480.5f,820.3f,3949.2f,1.00000f,0.00000f, -480.5f,2320.3f,3949.2f,1.00000f,1.00000f, -480.5f,2320.3f,-7441.4f,0.00000f,1.00000f } },
    { 43, { 3300.8f,820.3f,-7441.4f,0.00000f,0.00000f, 3300.8f,820.3f,3949.2f,1.00000f,0.00000f, 3300.8f,2320.3f,3949.2f,1.00000f,1.00000f, 3300.8f,2320.3f,-7441.4f,0.00000f,1.00000f } },
    { 43, { -480.5f,820.3f,-7441.4f,0.00000f,0.00000f, 3300.8f,820.3f,-7441.4f,1.00000f,0.00000f, 3300.8f,2320.3f,-7441.4f,1.00000f,1.00000f, -480.5f,2320.3f,-7441.4f,0.00000f,1.00000f } },
    { 43, { -480.5f,820.3f,3949.2f,0.00000f,0.00000f, 3300.8f,820.3f,3949.2f,1.00000f,0.00000f, 3300.8f,2320.3f,3949.2f,1.00000f,1.00000f, -480.5f,2320.3f,3949.2f,0.00000f,1.00000f } },
    { 129, { -2183.6f,1906.2f,-4293.0f,0.00000f,0.00000f, -2183.6f,1906.2f,7441.4f,1.00000f,0.00000f, -2183.6f,10273.4f,7441.4f,1.00000f,1.00000f, -2183.6f,10273.4f,-4293.0f,0.00000f,1.00000f } },
    { 129, { 316.4f,1906.2f,-4293.0f,0.00000f,0.00000f, 316.4f,1906.2f,7441.4f,1.00000f,0.00000f, 316.4f,10273.4f,7441.4f,1.00000f,1.00000f, 316.4f,10273.4f,-4293.0f,0.00000f,1.00000f } },
    { 129, { -2183.6f,1906.2f,-4293.0f,0.00000f,0.00000f, 316.4f,1906.2f,-4293.0f,1.00000f,0.00000f, 316.4f,10273.4f,-4293.0f,1.00000f,1.00000f, -2183.6f,10273.4f,-4293.0f,0.00000f,1.00000f } },
    { 129, { -2183.6f,1906.2f,7441.4f,0.00000f,0.00000f, 316.4f,1906.2f,7441.4f,1.00000f,0.00000f, 316.4f,10273.4f,7441.4f,1.00000f,1.00000f, -2183.6f,10273.4f,7441.4f,0.00000f,1.00000f } },
    { 129, { -2183.6f,10273.4f,-4293.0f,0.00000f,0.00000f, 316.4f,10273.4f,-4293.0f,1.00000f,0.00000f, 316.4f,10273.4f,7441.4f,1.00000f,1.00000f, -2183.6f,10273.4f,7441.4f,0.00000f,1.00000f } },
    { 133, { 3054.7f,0.0f,-3847.7f,0.00000f,0.00000f, 3054.7f,0.0f,2355.5f,1.00000f,0.00000f, 3054.7f,7890.6f,2355.5f,1.00000f,1.00000f, 3054.7f,7890.6f,-3847.7f,0.00000f,1.00000f } },
    { 133, { -3054.7f,0.0f,-3847.7f,0.00000f,0.00000f, 3054.7f,0.0f,-3847.7f,1.00000f,0.00000f, 3054.7f,7890.6f,-3847.7f,1.00000f,1.00000f, -3054.7f,7890.6f,-3847.7f,0.00000f,1.00000f } },
    { 133, { -3054.7f,7890.6f,-3847.7f,0.00000f,0.00000f, 3054.7f,7890.6f,-3847.7f,1.00000f,0.00000f, 3054.7f,7890.6f,2355.5f,1.00000f,1.00000f, -3054.7f,7890.6f,2355.5f,0.00000f,1.00000f } },
    { 68, { -5187.5f,31.2f,-10968.8f,0.00000f,0.00000f, -5187.5f,31.2f,-1531.2f,1.00000f,0.00000f, -5187.5f,9023.4f,-1531.2f,1.00000f,1.00000f, -5187.5f,9023.4f,-10968.8f,0.00000f,1.00000f } },
    { 68, { -312.5f,31.2f,-10968.8f,0.00000f,0.00000f, -312.5f,31.2f,-1531.2f,1.00000f,0.00000f, -312.5f,9023.4f,-1531.2f,1.00000f,1.00000f, -312.5f,9023.4f,-10968.8f,0.00000f,1.00000f } },
    { 68, { -5187.5f,31.2f,-10968.8f,0.00000f,0.00000f, -312.5f,31.2f,-10968.8f,1.00000f,0.00000f, -312.5f,9023.4f,-10968.8f,1.00000f,1.00000f, -5187.5f,9023.4f,-10968.8f,0.00000f,1.00000f } },
    { 68, { -5187.5f,31.2f,-1531.2f,0.00000f,0.00000f, -312.5f,31.2f,-1531.2f,1.00000f,0.00000f, -312.5f,9023.4f,-1531.2f,1.00000f,1.00000f, -5187.5f,9023.4f,-1531.2f,0.00000f,1.00000f } },
    { 68, { -5187.5f,9023.4f,-10968.8f,0.00000f,0.00000f, -312.5f,9023.4f,-10968.8f,1.00000f,0.00000f, -312.5f,9023.4f,-1531.2f,1.00000f,1.00000f, -5187.5f,9023.4f,-1531.2f,0.00000f,1.00000f } },
};

/* first,count into k_pfclose_quads[], indexed by prefab. */
static const unsigned short k_pfclose[][2] = {
    { 0, 0 },   /* L23.lm00 */
    { 0, 0 },   /* L23.lm01 */
    { 0, 0 },   /* L23.lm02 */
    { 0, 0 },   /* L23.lm03 */
    { 0, 6 },   /* L23.lm04 */
    { 6, 0 },   /* L23.lm05 */
    { 6, 0 },   /* L23.lm06 */
    { 6, 0 },   /* L23.lm07 */
    { 6, 0 },   /* L23.lm08 */
    { 6, 0 },   /* L23.lm09 */
    { 6, 0 },   /* L23.lm10 */
    { 6, 0 },   /* L23.lm11 */
    { 6, 0 },   /* L23.lm12 */
    { 6, 0 },   /* L23.lm13 */
    { 6, 0 },   /* L23.lm14 */
    { 6, 9 },   /* L23.lm15 */
    { 15, 3 },   /* L23.lm16 */
    { 18, 0 },   /* L23.lm17 */
    { 18, 0 },   /* L23.lm18 */
    { 18, 0 },   /* L23.lm19 */
    { 18, 0 },   /* L23.lm20 */
    { 18, 0 },   /* L23.lm21 */
    { 18, 5 },   /* L23.lm22 */
    { 23, 0 },   /* L23.lm23 */
};

/* 1 = this prefab's open part cannot be closed soundly from its own
 * footprint, so it is dropped from the selectable pool instead and the
 * caller extrudes the real footprint. See SOUND_FOOTPRINT_FRAC. */
static const unsigned char k_pfclose_exclude[] = {
    0,   /* L23.lm00 */
    0,   /* L23.lm01 */
    0,   /* L23.lm02 */
    0,   /* L23.lm03 */
    0,   /* L23.lm04 */
    0,   /* L23.lm05 */
    0,   /* L23.lm06 */
    0,   /* L23.lm07 */
    0,   /* L23.lm08 */
    0,   /* L23.lm09 */
    0,   /* L23.lm10 */
    0,   /* L23.lm11 */
    1,   /* L23.lm12 */
    0,   /* L23.lm13 */
    0,   /* L23.lm14 */
    0,   /* L23.lm15 */
    0,   /* L23.lm16 */
    0,   /* L23.lm17 */
    0,   /* L23.lm18 */
    0,   /* L23.lm19 */
    0,   /* L23.lm20 */
    0,   /* L23.lm21 */
    0,   /* L23.lm22 */
    0,   /* L23.lm23 */
};

#define TD5_TG_PREFAB_CLOSE_QUADS 23

#endif /* TD5_TG_PREFAB_CLOSE_DATA_H */
