# gen_module_table.ps1 — regenerate the CLAUDE.md source-port module table
# from srcs.txt + each module's own header comment (the "td5_x.c -- <desc>"
# line every module carries). Keeps the doc from drifting as modules are
# added/split — CLAUDE.md claimed "28 .c files" while the tree had 58.
#
#   pwsh scripts/gen_module_table.ps1          # print the table to stdout
#   pwsh scripts/gen_module_table.ps1 -Write   # splice it into CLAUDE.md
#                                              # between the BEGIN/END markers
param([switch]$Write)

$ErrorActionPreference = 'Stop'
$repo = Split-Path $PSScriptRoot -Parent
$srcDir = Join-Path $repo 'td5mod\src\td5re'
$claudeMd = Join-Path $repo 'CLAUDE.md'

$rows = @()
$srcs = Get-Content (Join-Path $srcDir 'srcs.txt') |
    Where-Object { $_ -notmatch '^\s*(#|$)' } | ForEach-Object { $_.Trim() }

foreach ($src in $srcs) {
    $path = Join-Path $srcDir ($src -replace '/', '\')
    $name = Split-Path $src -Leaf
    $desc = ''
    if (Test-Path $path) {
        # First ~8 lines: find "name.c -- description" (accepts --, —, -)
        $head = Get-Content $path -TotalCount 8
        foreach ($l in $head) {
            if ($l -match [regex]::Escape($name) + '\s*(?:--|—|-)\s*(.+)$') {
                $desc = $Matches[1].Trim() -replace '\s*\*/\s*$', ''
                break
            }
        }
    }
    if (-not $desc) {
        if ($src -match 'deps/') { $desc = '(vendored third-party)' }
        else { $desc = '(no header description — add one: /* ' + $name + ' -- ... */)' }
    }
    $rows += [pscustomobject]@{ File = $name; Desc = $desc }
}

$table = @("| File | Responsibility |", "|------|---------------|")
$table += $rows | ForEach-Object { "| ``$($_.File)`` | $($_.Desc) |" }
$tableText = ($table -join "`n")

if (-not $Write) { $tableText; exit 0 }

$md = Get-Content $claudeMd -Raw
$begin = '<!-- BEGIN MODULE TABLE (generated by scripts/gen_module_table.ps1 - do not hand-edit) -->'
$end = '<!-- END MODULE TABLE -->'
if ($md -notmatch [regex]::Escape($begin)) {
    Write-Error "CLAUDE.md is missing the module-table markers ($begin)"
    exit 1
}
$pattern = [regex]::Escape($begin) + '.*?' + [regex]::Escape($end)
$replacement = $begin + "`n" + $tableText + "`n" + $end
$md = [regex]::Replace($md, $pattern, $replacement.Replace('$', '$$'), 'Singleline')
Set-Content $claudeMd $md -Encoding UTF8 -NoNewline
Write-Host "CLAUDE.md module table regenerated ($($rows.Count) modules)."
