name: Build

on:
  push:
    branches: [main, master]
    paths:
      - 'td5mod/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/_build-td5re.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'td5mod/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/_build-td5re.yml'

jobs:
  build:
    uses: ./.github/workflows/_build-td5re.yml
    with:
      release: false
      run-lint: true
      artifact-name: td5re-${{ github.sha }}
